CREATE FUNCTION [dbo].[fnContingentement_Producteur_Full]
(@ContingentementID INT=Null, @ProducteurID VARCHAR (15)=Null)
RETURNS TABLE 
AS
RETURN 
    (
Select
 [Contingentement_Producteur].[ContingentementID]
,[Contingentement_Producteur].[ProducteurID]
,[Contingentement_Producteur].[Superficie_Contingentee]
,[Contingentement_Producteur].[Volume_Demande]
,[Contingentement_Producteur].[Volume_Facteur]
,[Contingentement_Producteur].[Volume_Fixe]
,[Contingentement_Producteur].[Volume_Supplementaire]
,[Contingentement_Producteur].[Volume_Accorde]
,[Contingentement_Producteur].[Date_Modification]
,[Contingentement_Producteur].[Volume_Inventaire]
,[Contingentement_Producteur].[LastLivraison]
,[Contingentement_Producteur].[VolumeMaximum]
,[Contingentement_Producteur].[Imprime]
,[Contingentement1].[ID] [ContingentementID_ID]
,[Contingentement1].[ContingentUsine] [ContingentementID_ContingentUsine]
,[Contingentement1].[UsineID] [ContingentementID_UsineID]
,[Contingentement1].[RegroupementID] [ContingentementID_RegroupementID]
,[Contingentement1].[Annee] [ContingentementID_Annee]
,[Contingentement1].[PeriodeContingentement] [ContingentementID_PeriodeContingentement]
,[Contingentement1].[PeriodeDebut] [ContingentementID_PeriodeDebut]
,[Contingentement1].[PeriodeFin] [ContingentementID_PeriodeFin]
,[Contingentement1].[EssenceID] [ContingentementID_EssenceID]
,[Contingentement1].[UniteMesureID] [ContingentementID_UniteMesureID]
,[Contingentement1].[Volume_Usine] [ContingentementID_Volume_Usine]
,[Contingentement1].[Facteur] [ContingentementID_Facteur]
,[Contingentement1].[Volume_Fixe] [ContingentementID_Volume_Fixe]
,[Contingentement1].[Date_Calcul] [ContingentementID_Date_Calcul]
,[Contingentement1].[CalculAccepte] [ContingentementID_CalculAccepte]
,[Contingentement1].[Code] [ContingentementID_Code]
,[Contingentement1].[Volume_Regroupement] [ContingentementID_Volume_Regroupement]
,[Contingentement1].[Volume_RegroupementPourcentage] [ContingentementID_Volume_RegroupementPourcentage]
,[Contingentement1].[MaxVolumeFixe_Pourcentage] [ContingentementID_MaxVolumeFixe_Pourcentage]
,[Contingentement1].[MaxVolumeFixe_ContingentementID] [ContingentementID_MaxVolumeFixe_ContingentementID]
,[Contingentement1].[UseVolumeFixeUnique] [ContingentementID_UseVolumeFixeUnique]
,[Contingentement1].[MasseContingentVoyageDefaut] [ContingentementID_MasseContingentVoyageDefaut]
,[Fournisseur2].[ID] [ProducteurID_ID]
,[Fournisseur2].[CleTri] [ProducteurID_CleTri]
,[Fournisseur2].[Nom] [ProducteurID_Nom]
,[Fournisseur2].[AuSoinsDe] [ProducteurID_AuSoinsDe]
,[Fournisseur2].[Rue] [ProducteurID_Rue]
,[Fournisseur2].[Ville] [ProducteurID_Ville]
,[Fournisseur2].[PaysID] [ProducteurID_PaysID]
,[Fournisseur2].[Code_postal] [ProducteurID_Code_postal]
,[Fournisseur2].[Telephone] [ProducteurID_Telephone]
,[Fournisseur2].[Telephone_Poste] [ProducteurID_Telephone_Poste]
,[Fournisseur2].[Telecopieur] [ProducteurID_Telecopieur]
,[Fournisseur2].[Telephone2] [ProducteurID_Telephone2]
,[Fournisseur2].[Telephone2_Desc] [ProducteurID_Telephone2_Desc]
,[Fournisseur2].[Telephone2_Poste] [ProducteurID_Telephone2_Poste]
,[Fournisseur2].[Telephone3] [ProducteurID_Telephone3]
,[Fournisseur2].[Telephone3_Desc] [ProducteurID_Telephone3_Desc]
,[Fournisseur2].[Telephone3_Poste] [ProducteurID_Telephone3_Poste]
,[Fournisseur2].[No_membre] [ProducteurID_No_membre]
,[Fournisseur2].[Resident] [ProducteurID_Resident]
,[Fournisseur2].[Email] [ProducteurID_Email]
,[Fournisseur2].[WWW] [ProducteurID_WWW]
,[Fournisseur2].[Commentaires] [ProducteurID_Commentaires]
,[Fournisseur2].[AfficherCommentaires] [ProducteurID_AfficherCommentaires]
,[Fournisseur2].[DepotDirect] [ProducteurID_DepotDirect]
,[Fournisseur2].[InstitutionBanquaireID] [ProducteurID_InstitutionBanquaireID]
,[Fournisseur2].[Banque_transit] [ProducteurID_Banque_transit]
,[Fournisseur2].[Banque_folio] [ProducteurID_Banque_folio]
,[Fournisseur2].[No_TPS] [ProducteurID_No_TPS]
,[Fournisseur2].[No_TVQ] [ProducteurID_No_TVQ]
,[Fournisseur2].[PayerA] [ProducteurID_PayerA]
,[Fournisseur2].[PayerAID] [ProducteurID_PayerAID]
,[Fournisseur2].[Statut] [ProducteurID_Statut]
,[Fournisseur2].[Rep_Nom] [ProducteurID_Rep_Nom]
,[Fournisseur2].[Rep_Telephone] [ProducteurID_Rep_Telephone]
,[Fournisseur2].[Rep_Telephone_Poste] [ProducteurID_Rep_Telephone_Poste]
,[Fournisseur2].[Rep_Email] [ProducteurID_Rep_Email]
,[Fournisseur2].[EnAnglais] [ProducteurID_EnAnglais]
,[Fournisseur2].[Actif] [ProducteurID_Actif]
,[Fournisseur2].[MRCProducteurID] [ProducteurID_MRCProducteurID]
,[Fournisseur2].[PaiementManuel] [ProducteurID_PaiementManuel]
,[Fournisseur2].[Journal] [ProducteurID_Journal]
,[Fournisseur2].[RecoitTPS] [ProducteurID_RecoitTPS]
,[Fournisseur2].[RecoitTVQ] [ProducteurID_RecoitTVQ]
,[Fournisseur2].[ModifierTrigger] [ProducteurID_ModifierTrigger]
,[Fournisseur2].[IsProducteur] [ProducteurID_IsProducteur]
,[Fournisseur2].[IsTransporteur] [ProducteurID_IsTransporteur]
,[Fournisseur2].[IsChargeur] [ProducteurID_IsChargeur]
,[Fournisseur2].[IsAutre] [ProducteurID_IsAutre]
,[Fournisseur2].[AfficherCommentairesSurPermit] [ProducteurID_AfficherCommentairesSurPermit]
,[Fournisseur2].[PasEmissionPermis] [ProducteurID_PasEmissionPermis]
,[Fournisseur2].[Generique] [ProducteurID_Generique]
,[Fournisseur2].[Membre_OGC] [ProducteurID_Membre_OGC]
,[Fournisseur2].[InscritTPS] [ProducteurID_InscritTPS]
,[Fournisseur2].[InscritTVQ] [ProducteurID_InscritTVQ]
,[Fournisseur2].[IsOGC] [ProducteurID_IsOGC]

From [dbo].[Contingentement_Producteur] [Contingentement_Producteur]
    Inner Join [dbo].[Contingentement] [Contingentement1] On [Contingentement_Producteur].[ContingentementID] = [Contingentement1].[ID]
        Inner Join [dbo].[Fournisseur] [Fournisseur2] On [Contingentement_Producteur].[ProducteurID] = [Fournisseur2].[ID]

Where

    ((@ContingentementID Is Null) Or ([Contingentement_Producteur].[ContingentementID] = @ContingentementID))
And ((@ProducteurID Is Null) Or ([Contingentement_Producteur].[ProducteurID] = @ProducteurID))
)



