CREATE FUNCTION [dbo].[fnContingentement_Full]
(@ID INT=Null, @UsineID VARCHAR (6)=Null, @RegroupementID INT=Null, @EssenceID VARCHAR (6)=Null, @UniteMesureID VARCHAR (6)=Null)
RETURNS TABLE 
AS
RETURN 
    (
Select
 [Contingentement].[ID]
,[Contingentement].[ContingentUsine]
,[Contingentement].[UsineID]
,[Contingentement].[RegroupementID]
,[Contingentement].[Annee]
,[Contingentement].[PeriodeContingentement]
,[Contingentement].[PeriodeDebut]
,[Contingentement].[PeriodeFin]
,[Contingentement].[EssenceID]
,[Contingentement].[UniteMesureID]
,[Contingentement].[Volume_Usine]
,[Contingentement].[Facteur]
,[Contingentement].[Volume_Fixe]
,[Contingentement].[Date_Calcul]
,[Contingentement].[CalculAccepte]
,[Contingentement].[Code]
,[Contingentement].[Volume_Regroupement]
,[Contingentement].[Volume_RegroupementPourcentage]
,[Contingentement].[MaxVolumeFixe_Pourcentage]
,[Contingentement].[MaxVolumeFixe_ContingentementID]
,[Contingentement].[UseVolumeFixeUnique]
,[Contingentement].[MasseContingentVoyageDefaut]
,[Usine1].[ID] [UsineID_ID]
,[Usine1].[Description] [UsineID_Description]
,[Usine1].[UtilisationID] [UsineID_UtilisationID]
,[Usine1].[Paye_producteur] [UsineID_Paye_producteur]
,[Usine1].[Paye_transporteur] [UsineID_Paye_transporteur]
,[Usine1].[Specification] [UsineID_Specification]
,[Usine1].[Compte_a_recevoir] [UsineID_Compte_a_recevoir]
,[Usine1].[Compte_ajustement] [UsineID_Compte_ajustement]
,[Usine1].[Compte_transporteur] [UsineID_Compte_transporteur]
,[Usine1].[Compte_producteur] [UsineID_Compte_producteur]
,[Usine1].[Compte_preleve_plan_conjoint] [UsineID_Compte_preleve_plan_conjoint]
,[Usine1].[Compte_preleve_fond_roulement] [UsineID_Compte_preleve_fond_roulement]
,[Usine1].[Compte_preleve_fond_forestier] [UsineID_Compte_preleve_fond_forestier]
,[Usine1].[Compte_preleve_divers] [UsineID_Compte_preleve_divers]
,[Usine1].[Compte_mise_en_commun] [UsineID_Compte_mise_en_commun]
,[Usine1].[Compte_surcharge] [UsineID_Compte_surcharge]
,[Usine1].[Compte_indexation_carburant] [UsineID_Compte_indexation_carburant]
,[Usine1].[Actif] [UsineID_Actif]
,[Usine1].[NePaiePasTPS] [UsineID_NePaiePasTPS]
,[Usine1].[NePaiePasTVQ] [UsineID_NePaiePasTVQ]
,[Usine1].[NoTPS] [UsineID_NoTPS]
,[Usine1].[NoTVQ] [UsineID_NoTVQ]
,[Usine1].[Compte_chargeur] [UsineID_Compte_chargeur]
,[Usine1].[UsineGestionVolume] [UsineID_UsineGestionVolume]
,[Usine1].[AuSoinsDe] [UsineID_AuSoinsDe]
,[Usine1].[Rue] [UsineID_Rue]
,[Usine1].[Ville] [UsineID_Ville]
,[Usine1].[PaysID] [UsineID_PaysID]
,[Usine1].[Code_postal] [UsineID_Code_postal]
,[Usine1].[Telephone] [UsineID_Telephone]
,[Usine1].[Telephone_Poste] [UsineID_Telephone_Poste]
,[Usine1].[Telecopieur] [UsineID_Telecopieur]
,[Usine1].[Telephone2] [UsineID_Telephone2]
,[Usine1].[Telephone2_Desc] [UsineID_Telephone2_Desc]
,[Usine1].[Telephone2_Poste] [UsineID_Telephone2_Poste]
,[Usine1].[Telephone3] [UsineID_Telephone3]
,[Usine1].[Telephone3_Desc] [UsineID_Telephone3_Desc]
,[Usine1].[Telephone3_Poste] [UsineID_Telephone3_Poste]
,[Usine1].[Email] [UsineID_Email]
,[EssenceRegroupement2].[ID] [RegroupementID_ID]
,[EssenceRegroupement2].[Description] [RegroupementID_Description]
,[EssenceRegroupement2].[Actif] [RegroupementID_Actif]
,[Essence3].[ID] [EssenceID_ID]
,[Essence3].[Description] [EssenceID_Description]
,[Essence3].[RegroupementID] [EssenceID_RegroupementID]
,[Essence3].[ContingentID] [EssenceID_ContingentID]
,[Essence3].[RepartitionID] [EssenceID_RepartitionID]
,[Essence3].[Actif] [EssenceID_Actif]
,[UniteMesure4].[ID] [UniteMesureID_ID]
,[UniteMesure4].[Description] [UniteMesureID_Description]
,[UniteMesure4].[Nb_decimale] [UniteMesureID_Nb_decimale]
,[UniteMesure4].[Actif] [UniteMesureID_Actif]
,[UniteMesure4].[UseMontant] [UniteMesureID_UseMontant]
,[UniteMesure4].[Montant_Preleve_plan_conjoint] [UniteMesureID_Montant_Preleve_plan_conjoint]
,[UniteMesure4].[Montant_Preleve_fond_roulement] [UniteMesureID_Montant_Preleve_fond_roulement]
,[UniteMesure4].[Montant_Preleve_fond_forestier] [UniteMesureID_Montant_Preleve_fond_forestier]
,[UniteMesure4].[Montant_Preleve_divers] [UniteMesureID_Montant_Preleve_divers]
,[UniteMesure4].[Pourc_Preleve_plan_conjoint] [UniteMesureID_Pourc_Preleve_plan_conjoint]
,[UniteMesure4].[Pourc_Preleve_fond_roulement] [UniteMesureID_Pourc_Preleve_fond_roulement]
,[UniteMesure4].[Pourc_Preleve_fond_forestier] [UniteMesureID_Pourc_Preleve_fond_forestier]
,[UniteMesure4].[Pourc_Preleve_divers] [UniteMesureID_Pourc_Preleve_divers]

From [dbo].[Contingentement] [Contingentement]
    Left Outer Join [dbo].[Usine] [Usine1] On [Contingentement].[UsineID] = [Usine1].[ID]
        Left Outer Join [dbo].[EssenceRegroupement] [EssenceRegroupement2] On [Contingentement].[RegroupementID] = [EssenceRegroupement2].[ID]
            Left Outer Join [dbo].[Essence] [Essence3] On [Contingentement].[EssenceID] = [Essence3].[ID]
                Left Outer Join [dbo].[UniteMesure] [UniteMesure4] On [Contingentement].[UniteMesureID] = [UniteMesure4].[ID]

Where

    ((@ID Is Null) Or ([Contingentement].[ID] = @ID))
And ((@UsineID Is Null) Or ([Contingentement].[UsineID] = @UsineID))
And ((@RegroupementID Is Null) Or ([Contingentement].[RegroupementID] = @RegroupementID))
And ((@EssenceID Is Null) Or ([Contingentement].[EssenceID] = @EssenceID))
And ((@UniteMesureID Is Null) Or ([Contingentement].[UniteMesureID] = @UniteMesureID))
)



