CREATE FUNCTION [dbo].[fnFactureUsine_Detail_Full]
(@ID INT=Null, @FactureUsineID INT=Null, @ProducteurID VARCHAR (15)=Null, @ProducteurEntentePaiementID VARCHAR (15)=Null, @ZoneID VARCHAR (2)=Null, @MunicipaliteID VARCHAR (6)=Null, @LotID INT=Null, @UniteMesureID VARCHAR (6)=Null, @LivraisonID INT=Null, @EssenceID VARCHAR (6)=Null)
RETURNS TABLE 
AS
RETURN 
    (
Select
 [FactureUsine_Detail].[ID]
,[FactureUsine_Detail].[FactureUsineID]
,[FactureUsine_Detail].[ContratID]
,[FactureUsine_Detail].[ProducteurID]
,[FactureUsine_Detail].[ProducteurEntentePaiementID]
,[FactureUsine_Detail].[ZoneID]
,[FactureUsine_Detail].[MunicipaliteID]
,[FactureUsine_Detail].[LotID]
,[FactureUsine_Detail].[UniteMesureID]
,[FactureUsine_Detail].[LivraisonID]
,[FactureUsine_Detail].[EssenceID]
,[FactureUsine_Detail].[Code]
,[FactureUsine_Detail].[Volume]
,[FactureUsine_Detail].[Taux]
,[FactureUsine_Detail].[Montant]
,[FactureUsine_Detail].[Taux_Usine_Override]
,[FactureUsine_Detail].[PermisID]
,[FactureUsine1].[ID] [FactureUsineID_ID]
,[FactureUsine1].[DatePermis] [FactureUsineID_DatePermis]
,[FactureUsine1].[DateLivraison] [FactureUsineID_DateLivraison]
,[FactureUsine1].[DatePaye] [FactureUsineID_DatePaye]
,[FactureUsine1].[Annee] [FactureUsineID_Annee]
,[FactureUsine1].[Periode] [FactureUsineID_Periode]
,[FactureUsine1].[ContratID] [FactureUsineID_ContratID]
,[FactureUsine1].[Sciage] [FactureUsineID_Sciage]
,[FactureUsine1].[EssenceSciage] [FactureUsineID_EssenceSciage]
,[FactureUsine1].[NumeroFactureUsine] [FactureUsineID_NumeroFactureUsine]
,[FactureUsine1].[ProducteurID] [FactureUsineID_ProducteurID]
,[FactureUsine1].[Livraison] [FactureUsineID_Livraison]
,[Fournisseur2].[ID] [ProducteurID_ID]
,[Fournisseur2].[CleTri] [ProducteurID_CleTri]
,[Fournisseur2].[Nom] [ProducteurID_Nom]
,[Fournisseur2].[AuSoinsDe] [ProducteurID_AuSoinsDe]
,[Fournisseur2].[Rue] [ProducteurID_Rue]
,[Fournisseur2].[Ville] [ProducteurID_Ville]
,[Fournisseur2].[PaysID] [ProducteurID_PaysID]
,[Fournisseur2].[Code_postal] [ProducteurID_Code_postal]
,[Fournisseur2].[Telephone] [ProducteurID_Telephone]
,[Fournisseur2].[Telephone_Poste] [ProducteurID_Telephone_Poste]
,[Fournisseur2].[Telecopieur] [ProducteurID_Telecopieur]
,[Fournisseur2].[Telephone2] [ProducteurID_Telephone2]
,[Fournisseur2].[Telephone2_Desc] [ProducteurID_Telephone2_Desc]
,[Fournisseur2].[Telephone2_Poste] [ProducteurID_Telephone2_Poste]
,[Fournisseur2].[Telephone3] [ProducteurID_Telephone3]
,[Fournisseur2].[Telephone3_Desc] [ProducteurID_Telephone3_Desc]
,[Fournisseur2].[Telephone3_Poste] [ProducteurID_Telephone3_Poste]
,[Fournisseur2].[No_membre] [ProducteurID_No_membre]
,[Fournisseur2].[Resident] [ProducteurID_Resident]
,[Fournisseur2].[Email] [ProducteurID_Email]
,[Fournisseur2].[WWW] [ProducteurID_WWW]
,[Fournisseur2].[Commentaires] [ProducteurID_Commentaires]
,[Fournisseur2].[AfficherCommentaires] [ProducteurID_AfficherCommentaires]
,[Fournisseur2].[DepotDirect] [ProducteurID_DepotDirect]
,[Fournisseur2].[InstitutionBanquaireID] [ProducteurID_InstitutionBanquaireID]
,[Fournisseur2].[Banque_transit] [ProducteurID_Banque_transit]
,[Fournisseur2].[Banque_folio] [ProducteurID_Banque_folio]
,[Fournisseur2].[No_TPS] [ProducteurID_No_TPS]
,[Fournisseur2].[No_TVQ] [ProducteurID_No_TVQ]
,[Fournisseur2].[PayerA] [ProducteurID_PayerA]
,[Fournisseur2].[PayerAID] [ProducteurID_PayerAID]
,[Fournisseur2].[Statut] [ProducteurID_Statut]
,[Fournisseur2].[Rep_Nom] [ProducteurID_Rep_Nom]
,[Fournisseur2].[Rep_Telephone] [ProducteurID_Rep_Telephone]
,[Fournisseur2].[Rep_Telephone_Poste] [ProducteurID_Rep_Telephone_Poste]
,[Fournisseur2].[Rep_Email] [ProducteurID_Rep_Email]
,[Fournisseur2].[EnAnglais] [ProducteurID_EnAnglais]
,[Fournisseur2].[Actif] [ProducteurID_Actif]
,[Fournisseur2].[MRCProducteurID] [ProducteurID_MRCProducteurID]
,[Fournisseur2].[PaiementManuel] [ProducteurID_PaiementManuel]
,[Fournisseur2].[Journal] [ProducteurID_Journal]
,[Fournisseur2].[RecoitTPS] [ProducteurID_RecoitTPS]
,[Fournisseur2].[RecoitTVQ] [ProducteurID_RecoitTVQ]
,[Fournisseur2].[ModifierTrigger] [ProducteurID_ModifierTrigger]
,[Fournisseur2].[IsProducteur] [ProducteurID_IsProducteur]
,[Fournisseur2].[IsTransporteur] [ProducteurID_IsTransporteur]
,[Fournisseur2].[IsChargeur] [ProducteurID_IsChargeur]
,[Fournisseur2].[IsAutre] [ProducteurID_IsAutre]
,[Fournisseur2].[AfficherCommentairesSurPermit] [ProducteurID_AfficherCommentairesSurPermit]
,[Fournisseur2].[PasEmissionPermis] [ProducteurID_PasEmissionPermis]
,[Fournisseur2].[Generique] [ProducteurID_Generique]
,[Fournisseur2].[Membre_OGC] [ProducteurID_Membre_OGC]
,[Fournisseur2].[InscritTPS] [ProducteurID_InscritTPS]
,[Fournisseur2].[InscritTVQ] [ProducteurID_InscritTVQ]
,[Fournisseur2].[IsOGC] [ProducteurID_IsOGC]
,[Fournisseur3].[ID] [ProducteurEntentePaiementID_ID]
,[Fournisseur3].[CleTri] [ProducteurEntentePaiementID_CleTri]
,[Fournisseur3].[Nom] [ProducteurEntentePaiementID_Nom]
,[Fournisseur3].[AuSoinsDe] [ProducteurEntentePaiementID_AuSoinsDe]
,[Fournisseur3].[Rue] [ProducteurEntentePaiementID_Rue]
,[Fournisseur3].[Ville] [ProducteurEntentePaiementID_Ville]
,[Fournisseur3].[PaysID] [ProducteurEntentePaiementID_PaysID]
,[Fournisseur3].[Code_postal] [ProducteurEntentePaiementID_Code_postal]
,[Fournisseur3].[Telephone] [ProducteurEntentePaiementID_Telephone]
,[Fournisseur3].[Telephone_Poste] [ProducteurEntentePaiementID_Telephone_Poste]
,[Fournisseur3].[Telecopieur] [ProducteurEntentePaiementID_Telecopieur]
,[Fournisseur3].[Telephone2] [ProducteurEntentePaiementID_Telephone2]
,[Fournisseur3].[Telephone2_Desc] [ProducteurEntentePaiementID_Telephone2_Desc]
,[Fournisseur3].[Telephone2_Poste] [ProducteurEntentePaiementID_Telephone2_Poste]
,[Fournisseur3].[Telephone3] [ProducteurEntentePaiementID_Telephone3]
,[Fournisseur3].[Telephone3_Desc] [ProducteurEntentePaiementID_Telephone3_Desc]
,[Fournisseur3].[Telephone3_Poste] [ProducteurEntentePaiementID_Telephone3_Poste]
,[Fournisseur3].[No_membre] [ProducteurEntentePaiementID_No_membre]
,[Fournisseur3].[Resident] [ProducteurEntentePaiementID_Resident]
,[Fournisseur3].[Email] [ProducteurEntentePaiementID_Email]
,[Fournisseur3].[WWW] [ProducteurEntentePaiementID_WWW]
,[Fournisseur3].[Commentaires] [ProducteurEntentePaiementID_Commentaires]
,[Fournisseur3].[AfficherCommentaires] [ProducteurEntentePaiementID_AfficherCommentaires]
,[Fournisseur3].[DepotDirect] [ProducteurEntentePaiementID_DepotDirect]
,[Fournisseur3].[InstitutionBanquaireID] [ProducteurEntentePaiementID_InstitutionBanquaireID]
,[Fournisseur3].[Banque_transit] [ProducteurEntentePaiementID_Banque_transit]
,[Fournisseur3].[Banque_folio] [ProducteurEntentePaiementID_Banque_folio]
,[Fournisseur3].[No_TPS] [ProducteurEntentePaiementID_No_TPS]
,[Fournisseur3].[No_TVQ] [ProducteurEntentePaiementID_No_TVQ]
,[Fournisseur3].[PayerA] [ProducteurEntentePaiementID_PayerA]
,[Fournisseur3].[PayerAID] [ProducteurEntentePaiementID_PayerAID]
,[Fournisseur3].[Statut] [ProducteurEntentePaiementID_Statut]
,[Fournisseur3].[Rep_Nom] [ProducteurEntentePaiementID_Rep_Nom]
,[Fournisseur3].[Rep_Telephone] [ProducteurEntentePaiementID_Rep_Telephone]
,[Fournisseur3].[Rep_Telephone_Poste] [ProducteurEntentePaiementID_Rep_Telephone_Poste]
,[Fournisseur3].[Rep_Email] [ProducteurEntentePaiementID_Rep_Email]
,[Fournisseur3].[EnAnglais] [ProducteurEntentePaiementID_EnAnglais]
,[Fournisseur3].[Actif] [ProducteurEntentePaiementID_Actif]
,[Fournisseur3].[MRCProducteurID] [ProducteurEntentePaiementID_MRCProducteurID]
,[Fournisseur3].[PaiementManuel] [ProducteurEntentePaiementID_PaiementManuel]
,[Fournisseur3].[Journal] [ProducteurEntentePaiementID_Journal]
,[Fournisseur3].[RecoitTPS] [ProducteurEntentePaiementID_RecoitTPS]
,[Fournisseur3].[RecoitTVQ] [ProducteurEntentePaiementID_RecoitTVQ]
,[Fournisseur3].[ModifierTrigger] [ProducteurEntentePaiementID_ModifierTrigger]
,[Fournisseur3].[IsProducteur] [ProducteurEntentePaiementID_IsProducteur]
,[Fournisseur3].[IsTransporteur] [ProducteurEntentePaiementID_IsTransporteur]
,[Fournisseur3].[IsChargeur] [ProducteurEntentePaiementID_IsChargeur]
,[Fournisseur3].[IsAutre] [ProducteurEntentePaiementID_IsAutre]
,[Fournisseur3].[AfficherCommentairesSurPermit] [ProducteurEntentePaiementID_AfficherCommentairesSurPermit]
,[Fournisseur3].[PasEmissionPermis] [ProducteurEntentePaiementID_PasEmissionPermis]
,[Fournisseur3].[Generique] [ProducteurEntentePaiementID_Generique]
,[Fournisseur3].[Membre_OGC] [ProducteurEntentePaiementID_Membre_OGC]
,[Fournisseur3].[InscritTPS] [ProducteurEntentePaiementID_InscritTPS]
,[Fournisseur3].[InscritTVQ] [ProducteurEntentePaiementID_InscritTVQ]
,[Fournisseur3].[IsOGC] [ProducteurEntentePaiementID_IsOGC]
,[Municipalite_Zone4].[ID] [ZoneID_ID]
,[Municipalite_Zone4].[MunicipaliteID] [ZoneID_MunicipaliteID]
,[Municipalite_Zone4].[Description] [ZoneID_Description]
,[Municipalite_Zone4].[Actif] [ZoneID_Actif]
,[Municipalite_Zone5].[ID] [MunicipaliteID_ID]
,[Municipalite_Zone5].[MunicipaliteID] [MunicipaliteID_MunicipaliteID]
,[Municipalite_Zone5].[Description] [MunicipaliteID_Description]
,[Municipalite_Zone5].[Actif] [MunicipaliteID_Actif]
,[Lot6].[CantonID] [LotID_CantonID]
,[Lot6].[Rang] [LotID_Rang]
,[Lot6].[Lot] [LotID_Lot]
,[Lot6].[MunicipaliteID] [LotID_MunicipaliteID]
,[Lot6].[Superficie_total] [LotID_Superficie_total]
,[Lot6].[Superficie_boisee] [LotID_Superficie_boisee]
,[Lot6].[ProprietaireID] [LotID_ProprietaireID]
,[Lot6].[ContingentID] [LotID_ContingentID]
,[Lot6].[Contingent_Date] [LotID_Contingent_Date]
,[Lot6].[Droit_coupeID] [LotID_Droit_coupeID]
,[Lot6].[Droit_coupe_Date] [LotID_Droit_coupe_Date]
,[Lot6].[Entente_paiementID] [LotID_Entente_paiementID]
,[Lot6].[Entente_paiement_Date] [LotID_Entente_paiement_Date]
,[Lot6].[Actif] [LotID_Actif]
,[Lot6].[ID] [LotID_ID]
,[Lot6].[Sequence] [LotID_Sequence]
,[Lot6].[Partie] [LotID_Partie]
,[Lot6].[Matricule] [LotID_Matricule]
,[Lot6].[ZoneID] [LotID_ZoneID]
,[Lot6].[Secteur] [LotID_Secteur]
,[Lot6].[Cadastre] [LotID_Cadastre]
,[Lot6].[Reforme] [LotID_Reforme]
,[Lot6].[LotsComplementaires] [LotID_LotsComplementaires]
,[Lot6].[Certifie] [LotID_Certifie]
,[Lot6].[NumeroCertification] [LotID_NumeroCertification]
,[Lot6].[OGC] [LotID_OGC]
,[UniteMesure7].[ID] [UniteMesureID_ID]
,[UniteMesure7].[Description] [UniteMesureID_Description]
,[UniteMesure7].[Nb_decimale] [UniteMesureID_Nb_decimale]
,[UniteMesure7].[Actif] [UniteMesureID_Actif]
,[UniteMesure7].[UseMontant] [UniteMesureID_UseMontant]
,[UniteMesure7].[Montant_Preleve_plan_conjoint] [UniteMesureID_Montant_Preleve_plan_conjoint]
,[UniteMesure7].[Montant_Preleve_fond_roulement] [UniteMesureID_Montant_Preleve_fond_roulement]
,[UniteMesure7].[Montant_Preleve_fond_forestier] [UniteMesureID_Montant_Preleve_fond_forestier]
,[UniteMesure7].[Montant_Preleve_divers] [UniteMesureID_Montant_Preleve_divers]
,[UniteMesure7].[Pourc_Preleve_plan_conjoint] [UniteMesureID_Pourc_Preleve_plan_conjoint]
,[UniteMesure7].[Pourc_Preleve_fond_roulement] [UniteMesureID_Pourc_Preleve_fond_roulement]
,[UniteMesure7].[Pourc_Preleve_fond_forestier] [UniteMesureID_Pourc_Preleve_fond_forestier]
,[UniteMesure7].[Pourc_Preleve_divers] [UniteMesureID_Pourc_Preleve_divers]
,[Livraison8].[ID] [LivraisonID_ID]
,[Livraison8].[DateLivraison] [LivraisonID_DateLivraison]
,[Livraison8].[DatePaye] [LivraisonID_DatePaye]
,[Livraison8].[ContratID] [LivraisonID_ContratID]
,[Livraison8].[UniteMesureID] [LivraisonID_UniteMesureID]
,[Livraison8].[EssenceID] [LivraisonID_EssenceID]
,[Livraison8].[Sciage] [LivraisonID_Sciage]
,[Livraison8].[NumeroFactureUsine] [LivraisonID_NumeroFactureUsine]
,[Livraison8].[DroitCoupeID] [LivraisonID_DroitCoupeID]
,[Livraison8].[EntentePaiementID] [LivraisonID_EntentePaiementID]
,[Livraison8].[TransporteurID] [LivraisonID_TransporteurID]
,[Livraison8].[VR] [LivraisonID_VR]
,[Livraison8].[MasseLimite] [LivraisonID_MasseLimite]
,[Livraison8].[VolumeBrut] [LivraisonID_VolumeBrut]
,[Livraison8].[VolumeTare] [LivraisonID_VolumeTare]
,[Livraison8].[VolumeTransporte] [LivraisonID_VolumeTransporte]
,[Livraison8].[VolumeSurcharge] [LivraisonID_VolumeSurcharge]
,[Livraison8].[VolumeAPayer] [LivraisonID_VolumeAPayer]
,[Livraison8].[Annee] [LivraisonID_Annee]
,[Livraison8].[Periode] [LivraisonID_Periode]
,[Livraison8].[DateCalcul] [LivraisonID_DateCalcul]
,[Livraison8].[Taux_Transporteur] [LivraisonID_Taux_Transporteur]
,[Livraison8].[Montant_Transporteur] [LivraisonID_Montant_Transporteur]
,[Livraison8].[Montant_Usine] [LivraisonID_Montant_Usine]
,[Livraison8].[Montant_Producteur1] [LivraisonID_Montant_Producteur1]
,[Livraison8].[Montant_Producteur2] [LivraisonID_Montant_Producteur2]
,[Livraison8].[Montant_Preleve_Plan_Conjoint] [LivraisonID_Montant_Preleve_Plan_Conjoint]
,[Livraison8].[Montant_Preleve_Fond_Roulement] [LivraisonID_Montant_Preleve_Fond_Roulement]
,[Livraison8].[Montant_Preleve_Fond_Forestier] [LivraisonID_Montant_Preleve_Fond_Forestier]
,[Livraison8].[Montant_Preleve_Divers] [LivraisonID_Montant_Preleve_Divers]
,[Livraison8].[Montant_Surcharge] [LivraisonID_Montant_Surcharge]
,[Livraison8].[Montant_MiseEnCommun] [LivraisonID_Montant_MiseEnCommun]
,[Livraison8].[Facture] [LivraisonID_Facture]
,[Livraison8].[Producteur1_FactureID] [LivraisonID_Producteur1_FactureID]
,[Livraison8].[Producteur2_FactureID] [LivraisonID_Producteur2_FactureID]
,[Livraison8].[Transporteur_FactureID] [LivraisonID_Transporteur_FactureID]
,[Livraison8].[Usine_FactureID] [LivraisonID_Usine_FactureID]
,[Livraison8].[ErreurCalcul] [LivraisonID_ErreurCalcul]
,[Livraison8].[ErreurDescription] [LivraisonID_ErreurDescription]
,[Livraison8].[LotID] [LivraisonID_LotID]
,[Livraison8].[Taux_Transporteur_Override] [LivraisonID_Taux_Transporteur_Override]
,[Livraison8].[PaieTransporteur] [LivraisonID_PaieTransporteur]
,[Livraison8].[VolumeSurcharge_Override] [LivraisonID_VolumeSurcharge_Override]
,[Livraison8].[SurchargeManuel] [LivraisonID_SurchargeManuel]
,[Livraison8].[Code] [LivraisonID_Code]
,[Livraison8].[NombrePermis] [LivraisonID_NombrePermis]
,[Livraison8].[ZoneID] [LivraisonID_ZoneID]
,[Livraison8].[MunicipaliteID] [LivraisonID_MunicipaliteID]
,[Livraison8].[ChargeurID] [LivraisonID_ChargeurID]
,[Livraison8].[Montant_Chargeur] [LivraisonID_Montant_Chargeur]
,[Livraison8].[Frais_ChargeurAuProducteur] [LivraisonID_Frais_ChargeurAuProducteur]
,[Livraison8].[Frais_ChargeurAuTransporteur] [LivraisonID_Frais_ChargeurAuTransporteur]
,[Livraison8].[Frais_AutresAuProducteur] [LivraisonID_Frais_AutresAuProducteur]
,[Livraison8].[Frais_AutresAuProducteurDescription] [LivraisonID_Frais_AutresAuProducteurDescription]
,[Livraison8].[Frais_AutresAuTransporteur] [LivraisonID_Frais_AutresAuTransporteur]
,[Livraison8].[Frais_AutresAuTransporteurDescription] [LivraisonID_Frais_AutresAuTransporteurDescription]
,[Livraison8].[Frais_CompensationDeDeplacement] [LivraisonID_Frais_CompensationDeDeplacement]
,[Livraison8].[Chargeur_FactureID] [LivraisonID_Chargeur_FactureID]
,[Livraison8].[Commentaires_Producteur] [LivraisonID_Commentaires_Producteur]
,[Livraison8].[Commentaires_Transporteur] [LivraisonID_Commentaires_Transporteur]
,[Livraison8].[Commentaires_Chargeur] [LivraisonID_Commentaires_Chargeur]
,[Livraison8].[TauxChargeurAuProducteur] [LivraisonID_TauxChargeurAuProducteur]
,[Livraison8].[TauxChargeurAuTransporteur] [LivraisonID_TauxChargeurAuTransporteur]
,[Livraison8].[Frais_AutresRevenusTransporteur] [LivraisonID_Frais_AutresRevenusTransporteur]
,[Livraison8].[Frais_AutresRevenusTransporteurDescription] [LivraisonID_Frais_AutresRevenusTransporteurDescription]
,[Livraison8].[Frais_AutresRevenusProducteur] [LivraisonID_Frais_AutresRevenusProducteur]
,[Livraison8].[Frais_AutresRevenusProducteurDescription] [LivraisonID_Frais_AutresRevenusProducteurDescription]
,[Livraison8].[Montant_SurchargeProducteur] [LivraisonID_Montant_SurchargeProducteur]
,[Livraison8].[KgVert_Brut] [LivraisonID_KgVert_Brut]
,[Livraison8].[KgVert_Tare] [LivraisonID_KgVert_Tare]
,[Livraison8].[KgVert_Net] [LivraisonID_KgVert_Net]
,[Livraison8].[KgVert_Rejets] [LivraisonID_KgVert_Rejets]
,[Livraison8].[KgVert_Paye] [LivraisonID_KgVert_Paye]
,[Livraison8].[Pourcent_Sec_Producteur] [LivraisonID_Pourcent_Sec_Producteur]
,[Livraison8].[Pourcent_Sec_Producteur_Override] [LivraisonID_Pourcent_Sec_Producteur_Override]
,[Livraison8].[TMA_Producteur] [LivraisonID_TMA_Producteur]
,[Livraison8].[Pourcent_Sec_Transport] [LivraisonID_Pourcent_Sec_Transport]
,[Livraison8].[Pourcent_Sec_Transport_Override] [LivraisonID_Pourcent_Sec_Transport_Override]
,[Livraison8].[TMA_Transport] [LivraisonID_TMA_Transport]
,[Livraison8].[IsTMA] [LivraisonID_IsTMA]
,[Essence9].[ID] [EssenceID_ID]
,[Essence9].[Description] [EssenceID_Description]
,[Essence9].[RegroupementID] [EssenceID_RegroupementID]
,[Essence9].[ContingentID] [EssenceID_ContingentID]
,[Essence9].[RepartitionID] [EssenceID_RepartitionID]
,[Essence9].[Actif] [EssenceID_Actif]

From [dbo].[FactureUsine_Detail] [FactureUsine_Detail]
    Left Outer Join [dbo].[FactureUsine] [FactureUsine1] On [FactureUsine_Detail].[FactureUsineID] = [FactureUsine1].[ID]
        Left Outer Join [dbo].[Fournisseur] [Fournisseur2] On [FactureUsine_Detail].[ProducteurID] = [Fournisseur2].[ID]
            Left Outer Join [dbo].[Fournisseur] [Fournisseur3] On [FactureUsine_Detail].[ProducteurEntentePaiementID] = [Fournisseur3].[ID]
                Left Outer Join [dbo].[Municipalite_Zone] [Municipalite_Zone4] On [FactureUsine_Detail].[ZoneID] = [Municipalite_Zone4].[ID]
                    Left Outer Join [dbo].[Municipalite_Zone] [Municipalite_Zone5] On [FactureUsine_Detail].[MunicipaliteID] = [Municipalite_Zone5].[MunicipaliteID]
                        Left Outer Join [dbo].[Lot] [Lot6] On [FactureUsine_Detail].[LotID] = [Lot6].[ID]
                            Inner Join [dbo].[UniteMesure] [UniteMesure7] On [FactureUsine_Detail].[UniteMesureID] = [UniteMesure7].[ID]
                                Left Outer Join [dbo].[Livraison] [Livraison8] On [FactureUsine_Detail].[LivraisonID] = [Livraison8].[ID]
                                    Left Outer Join [dbo].[Essence] [Essence9] On [FactureUsine_Detail].[EssenceID] = [Essence9].[ID]

Where

    ((@ID Is Null) Or ([FactureUsine_Detail].[ID] = @ID))
And ((@FactureUsineID Is Null) Or ([FactureUsine_Detail].[FactureUsineID] = @FactureUsineID))
And ((@ProducteurID Is Null) Or ([FactureUsine_Detail].[ProducteurID] = @ProducteurID))
And ((@ProducteurEntentePaiementID Is Null) Or ([FactureUsine_Detail].[ProducteurEntentePaiementID] = @ProducteurEntentePaiementID))
And ((@ZoneID Is Null) Or ([FactureUsine_Detail].[ZoneID] = @ZoneID))
And ((@MunicipaliteID Is Null) Or ([FactureUsine_Detail].[MunicipaliteID] = @MunicipaliteID))
And ((@LotID Is Null) Or ([FactureUsine_Detail].[LotID] = @LotID))
And ((@UniteMesureID Is Null) Or ([FactureUsine_Detail].[UniteMesureID] = @UniteMesureID))
And ((@LivraisonID Is Null) Or ([FactureUsine_Detail].[LivraisonID] = @LivraisonID))
And ((@EssenceID Is Null) Or ([FactureUsine_Detail].[EssenceID] = @EssenceID))
)



