CREATE FUNCTION [dbo].[fnIndexationCalcule_Transporteur_Full]
(@ID INT=Null, @TypeIndexation CHAR (1)=Null, @IndexationID INT=Null, @IndexationDetailID INT=Null, @LivraisonID INT=Null, @TransporteurID VARCHAR (15)=Null, @FactureID INT=Null)
RETURNS TABLE 
AS
RETURN 
    (
Select TOP 100 PERCENT
 [IndexationCalcule_Transporteur].[ID]
,[IndexationCalcule_Transporteur].[DateCalcul]
,[IndexationCalcule_Transporteur].[TypeIndexation]
,[IndexationCalcule_Transporteur].[IndexationID]
,[IndexationCalcule_Transporteur].[IndexationDetailID]
,[IndexationCalcule_Transporteur].[LivraisonID]
,[IndexationCalcule_Transporteur].[TransporteurID]
,[IndexationCalcule_Transporteur].[MontantDejaPaye]
,[IndexationCalcule_Transporteur].[PourcentageDuMontant]
,[IndexationCalcule_Transporteur].[Montant]
,[IndexationCalcule_Transporteur].[Facture]
,[IndexationCalcule_Transporteur].[FactureID]
,[IndexationCalcule_Transporteur].[ErreurCalcul]
,[IndexationCalcule_Transporteur].[ErreurDescription]
,[TypeIndexation1].[ID] [TypeIndexation_ID]
,[TypeIndexation1].[Description] [TypeIndexation_Description]
,[Indexation2].[ID] [IndexationID_ID]
,[Indexation2].[DateIndexation] [IndexationID_DateIndexation]
,[Indexation2].[ContratID] [IndexationID_ContratID]
,[Indexation2].[Periode_Debut] [IndexationID_Periode_Debut]
,[Indexation2].[Periode_Fin] [IndexationID_Periode_Fin]
,[Indexation2].[TypeIndexation] [IndexationID_TypeIndexation]
,[Indexation2].[PourcentageDuMontant] [IndexationID_PourcentageDuMontant]
,[Indexation2].[Facture] [IndexationID_Facture]
,[Indexation2].[IndexationTransporteur] [IndexationID_IndexationTransporteur]
,[Indexation2].[Date_Debut] [IndexationID_Date_Debut]
,[Indexation2].[Date_Fin] [IndexationID_Date_Fin]
,[Indexation2].[IndexationManuelle] [IndexationID_IndexationManuelle]
,[Indexation_Municipalite3].[ID] [IndexationDetailID_ID]
,[Indexation_Municipalite3].[IndexationID] [IndexationDetailID_IndexationID]
,[Indexation_Municipalite3].[MunicipaliteID] [IndexationDetailID_MunicipaliteID]
,[Indexation_Municipalite3].[Montant] [IndexationDetailID_Montant]
,[Indexation_Municipalite3].[ZoneID] [IndexationDetailID_ZoneID]
,[Livraison4].[ID] [LivraisonID_ID]
,[Livraison4].[DateLivraison] [LivraisonID_DateLivraison]
,[Livraison4].[DatePaye] [LivraisonID_DatePaye]
,[Livraison4].[ContratID] [LivraisonID_ContratID]
,[Livraison4].[UniteMesureID] [LivraisonID_UniteMesureID]
,[Livraison4].[EssenceID] [LivraisonID_EssenceID]
,[Livraison4].[Sciage] [LivraisonID_Sciage]
,[Livraison4].[NumeroFactureUsine] [LivraisonID_NumeroFactureUsine]
,[Livraison4].[DroitCoupeID] [LivraisonID_DroitCoupeID]
,[Livraison4].[EntentePaiementID] [LivraisonID_EntentePaiementID]
,[Livraison4].[TransporteurID] [LivraisonID_TransporteurID]
,[Livraison4].[VR] [LivraisonID_VR]
,[Livraison4].[MasseLimite] [LivraisonID_MasseLimite]
,[Livraison4].[VolumeBrut] [LivraisonID_VolumeBrut]
,[Livraison4].[VolumeTare] [LivraisonID_VolumeTare]
,[Livraison4].[VolumeTransporte] [LivraisonID_VolumeTransporte]
,[Livraison4].[VolumeSurcharge] [LivraisonID_VolumeSurcharge]
,[Livraison4].[VolumeAPayer] [LivraisonID_VolumeAPayer]
,[Livraison4].[Annee] [LivraisonID_Annee]
,[Livraison4].[Periode] [LivraisonID_Periode]
,[Livraison4].[DateCalcul] [LivraisonID_DateCalcul]
,[Livraison4].[Taux_Transporteur] [LivraisonID_Taux_Transporteur]
,[Livraison4].[Montant_Transporteur] [LivraisonID_Montant_Transporteur]
,[Livraison4].[Montant_Usine] [LivraisonID_Montant_Usine]
,[Livraison4].[Montant_Producteur1] [LivraisonID_Montant_Producteur1]
,[Livraison4].[Montant_Producteur2] [LivraisonID_Montant_Producteur2]
,[Livraison4].[Montant_Preleve_Plan_Conjoint] [LivraisonID_Montant_Preleve_Plan_Conjoint]
,[Livraison4].[Montant_Preleve_Fond_Roulement] [LivraisonID_Montant_Preleve_Fond_Roulement]
,[Livraison4].[Montant_Preleve_Fond_Forestier] [LivraisonID_Montant_Preleve_Fond_Forestier]
,[Livraison4].[Montant_Preleve_Divers] [LivraisonID_Montant_Preleve_Divers]
,[Livraison4].[Montant_Surcharge] [LivraisonID_Montant_Surcharge]
,[Livraison4].[Montant_MiseEnCommun] [LivraisonID_Montant_MiseEnCommun]
,[Livraison4].[Facture] [LivraisonID_Facture]
,[Livraison4].[Producteur1_FactureID] [LivraisonID_Producteur1_FactureID]
,[Livraison4].[Producteur2_FactureID] [LivraisonID_Producteur2_FactureID]
,[Livraison4].[Transporteur_FactureID] [LivraisonID_Transporteur_FactureID]
,[Livraison4].[Usine_FactureID] [LivraisonID_Usine_FactureID]
,[Livraison4].[ErreurCalcul] [LivraisonID_ErreurCalcul]
,[Livraison4].[ErreurDescription] [LivraisonID_ErreurDescription]
,[Livraison4].[LotID] [LivraisonID_LotID]
,[Livraison4].[Taux_Transporteur_Override] [LivraisonID_Taux_Transporteur_Override]
,[Livraison4].[PaieTransporteur] [LivraisonID_PaieTransporteur]
,[Livraison4].[VolumeSurcharge_Override] [LivraisonID_VolumeSurcharge_Override]
,[Livraison4].[SurchargeManuel] [LivraisonID_SurchargeManuel]
,[Livraison4].[Code] [LivraisonID_Code]
,[Livraison4].[NombrePermis] [LivraisonID_NombrePermis]
,[Livraison4].[ZoneID] [LivraisonID_ZoneID]
,[Livraison4].[MunicipaliteID] [LivraisonID_MunicipaliteID]
,[Livraison4].[ChargeurID] [LivraisonID_ChargeurID]
,[Livraison4].[Montant_Chargeur] [LivraisonID_Montant_Chargeur]
,[Livraison4].[Frais_ChargeurAuProducteur] [LivraisonID_Frais_ChargeurAuProducteur]
,[Livraison4].[Frais_ChargeurAuTransporteur] [LivraisonID_Frais_ChargeurAuTransporteur]
,[Livraison4].[Frais_AutresAuProducteur] [LivraisonID_Frais_AutresAuProducteur]
,[Livraison4].[Frais_AutresAuProducteurDescription] [LivraisonID_Frais_AutresAuProducteurDescription]
,[Livraison4].[Frais_AutresAuTransporteur] [LivraisonID_Frais_AutresAuTransporteur]
,[Livraison4].[Frais_AutresAuTransporteurDescription] [LivraisonID_Frais_AutresAuTransporteurDescription]
,[Livraison4].[Frais_CompensationDeDeplacement] [LivraisonID_Frais_CompensationDeDeplacement]
,[Livraison4].[Chargeur_FactureID] [LivraisonID_Chargeur_FactureID]
,[Livraison4].[Commentaires_Producteur] [LivraisonID_Commentaires_Producteur]
,[Livraison4].[Commentaires_Transporteur] [LivraisonID_Commentaires_Transporteur]
,[Livraison4].[Commentaires_Chargeur] [LivraisonID_Commentaires_Chargeur]
,[Livraison4].[TauxChargeurAuProducteur] [LivraisonID_TauxChargeurAuProducteur]
,[Livraison4].[TauxChargeurAuTransporteur] [LivraisonID_TauxChargeurAuTransporteur]
,[Livraison4].[Frais_AutresRevenusTransporteur] [LivraisonID_Frais_AutresRevenusTransporteur]
,[Livraison4].[Frais_AutresRevenusTransporteurDescription] [LivraisonID_Frais_AutresRevenusTransporteurDescription]
,[Livraison4].[Frais_AutresRevenusProducteur] [LivraisonID_Frais_AutresRevenusProducteur]
,[Livraison4].[Frais_AutresRevenusProducteurDescription] [LivraisonID_Frais_AutresRevenusProducteurDescription]
,[Livraison4].[Montant_SurchargeProducteur] [LivraisonID_Montant_SurchargeProducteur]
,[Fournisseur5].[ID] [TransporteurID_ID]
,[Fournisseur5].[CleTri] [TransporteurID_CleTri]
,[Fournisseur5].[Nom] [TransporteurID_Nom]
,[Fournisseur5].[AuSoinsDe] [TransporteurID_AuSoinsDe]
,[Fournisseur5].[Rue] [TransporteurID_Rue]
,[Fournisseur5].[Ville] [TransporteurID_Ville]
,[Fournisseur5].[PaysID] [TransporteurID_PaysID]
,[Fournisseur5].[Code_postal] [TransporteurID_Code_postal]
,[Fournisseur5].[Telephone] [TransporteurID_Telephone]
,[Fournisseur5].[Telephone_Poste] [TransporteurID_Telephone_Poste]
,[Fournisseur5].[Telecopieur] [TransporteurID_Telecopieur]
,[Fournisseur5].[Telephone2] [TransporteurID_Telephone2]
,[Fournisseur5].[Telephone2_Desc] [TransporteurID_Telephone2_Desc]
,[Fournisseur5].[Telephone2_Poste] [TransporteurID_Telephone2_Poste]
,[Fournisseur5].[Telephone3] [TransporteurID_Telephone3]
,[Fournisseur5].[Telephone3_Desc] [TransporteurID_Telephone3_Desc]
,[Fournisseur5].[Telephone3_Poste] [TransporteurID_Telephone3_Poste]
,[Fournisseur5].[No_membre] [TransporteurID_No_membre]
,[Fournisseur5].[Resident] [TransporteurID_Resident]
,[Fournisseur5].[Email] [TransporteurID_Email]
,[Fournisseur5].[WWW] [TransporteurID_WWW]
,[Fournisseur5].[Commentaires] [TransporteurID_Commentaires]
,[Fournisseur5].[AfficherCommentaires] [TransporteurID_AfficherCommentaires]
,[Fournisseur5].[DepotDirect] [TransporteurID_DepotDirect]
,[Fournisseur5].[InstitutionBanquaireID] [TransporteurID_InstitutionBanquaireID]
,[Fournisseur5].[Banque_transit] [TransporteurID_Banque_transit]
,[Fournisseur5].[Banque_folio] [TransporteurID_Banque_folio]
,[Fournisseur5].[No_TPS] [TransporteurID_No_TPS]
,[Fournisseur5].[No_TVQ] [TransporteurID_No_TVQ]
,[Fournisseur5].[PayerA] [TransporteurID_PayerA]
,[Fournisseur5].[PayerAID] [TransporteurID_PayerAID]
,[Fournisseur5].[Statut] [TransporteurID_Statut]
,[Fournisseur5].[Rep_Nom] [TransporteurID_Rep_Nom]
,[Fournisseur5].[Rep_Telephone] [TransporteurID_Rep_Telephone]
,[Fournisseur5].[Rep_Telephone_Poste] [TransporteurID_Rep_Telephone_Poste]
,[Fournisseur5].[Rep_Email] [TransporteurID_Rep_Email]
,[Fournisseur5].[EnAnglais] [TransporteurID_EnAnglais]
,[Fournisseur5].[Actif] [TransporteurID_Actif]
,[Fournisseur5].[MRCProducteurID] [TransporteurID_MRCProducteurID]
,[Fournisseur5].[PaiementManuel] [TransporteurID_PaiementManuel]
,[Fournisseur5].[Journal] [TransporteurID_Journal]
,[Fournisseur5].[RecoitTPS] [TransporteurID_RecoitTPS]
,[Fournisseur5].[RecoitTVQ] [TransporteurID_RecoitTVQ]
,[Fournisseur5].[ModifierTrigger] [TransporteurID_ModifierTrigger]
,[Fournisseur5].[IsProducteur] [TransporteurID_IsProducteur]
,[Fournisseur5].[IsTransporteur] [TransporteurID_IsTransporteur]
,[Fournisseur5].[IsChargeur] [TransporteurID_IsChargeur]
,[Fournisseur5].[IsAutre] [TransporteurID_IsAutre]
,[Fournisseur5].[AfficherCommentairesSurPermit] [TransporteurID_AfficherCommentairesSurPermit]
,[Fournisseur5].[PasEmissionPermis] [TransporteurID_PasEmissionPermis]
,[Fournisseur5].[Generique] [TransporteurID_Generique]
,[FactureFournisseur6].[ID] [FactureID_ID]
,[FactureFournisseur6].[NoFacture] [FactureID_NoFacture]
,[FactureFournisseur6].[DateFacture] [FactureID_DateFacture]
,[FactureFournisseur6].[Annee] [FactureID_Annee]
,[FactureFournisseur6].[TypeFactureFournisseur] [FactureID_TypeFactureFournisseur]
,[FactureFournisseur6].[TypeFacture] [FactureID_TypeFacture]
,[FactureFournisseur6].[TypeInvoiceAcomba] [FactureID_TypeInvoiceAcomba]
,[FactureFournisseur6].[FournisseurID] [FactureID_FournisseurID]
,[FactureFournisseur6].[PayerAID] [FactureID_PayerAID]
,[FactureFournisseur6].[Montant_Total] [FactureID_Montant_Total]
,[FactureFournisseur6].[Montant_TPS] [FactureID_Montant_TPS]
,[FactureFournisseur6].[Montant_TVQ] [FactureID_Montant_TVQ]
,[FactureFournisseur6].[Description] [FactureID_Description]
,[FactureFournisseur6].[Status] [FactureID_Status]
,[FactureFournisseur6].[StatusDescription] [FactureID_StatusDescription]
,[FactureFournisseur6].[NumeroCheque] [FactureID_NumeroCheque]
,[FactureFournisseur6].[NumeroPaiement] [FactureID_NumeroPaiement]
,[FactureFournisseur6].[NumeroPaiementUnique] [FactureID_NumeroPaiementUnique]
,[FactureFournisseur6].[DateFactureAcomba] [FactureID_DateFactureAcomba]
,[FactureFournisseur6].[DatePaiementAcomba] [FactureID_DatePaiementAcomba]

From [dbo].[IndexationCalcule_Transporteur] [IndexationCalcule_Transporteur]
    Left Outer Join [dbo].[TypeIndexation] [TypeIndexation1] On [IndexationCalcule_Transporteur].[TypeIndexation] = [TypeIndexation1].[ID]
        Left Outer Join [dbo].[Indexation] [Indexation2] On [IndexationCalcule_Transporteur].[IndexationID] = [Indexation2].[ID]
            Left Outer Join [dbo].[Indexation_Municipalite] [Indexation_Municipalite3] On [IndexationCalcule_Transporteur].[IndexationDetailID] = [Indexation_Municipalite3].[ID]
                Left Outer Join [dbo].[Livraison] [Livraison4] On [IndexationCalcule_Transporteur].[LivraisonID] = [Livraison4].[ID]
                    Left Outer Join [dbo].[Fournisseur] [Fournisseur5] On [IndexationCalcule_Transporteur].[TransporteurID] = [Fournisseur5].[ID]
                        Left Outer Join [dbo].[FactureFournisseur] [FactureFournisseur6] On [IndexationCalcule_Transporteur].[FactureID] = [FactureFournisseur6].[ID]

Where

    ((@ID Is Null) Or ([IndexationCalcule_Transporteur].[ID] = @ID))
And ((@TypeIndexation Is Null) Or ([IndexationCalcule_Transporteur].[TypeIndexation] = @TypeIndexation))
And ((@IndexationID Is Null) Or ([IndexationCalcule_Transporteur].[IndexationID] = @IndexationID))
And ((@IndexationDetailID Is Null) Or ([IndexationCalcule_Transporteur].[IndexationDetailID] = @IndexationDetailID))
And ((@LivraisonID Is Null) Or ([IndexationCalcule_Transporteur].[LivraisonID] = @LivraisonID))
And ((@TransporteurID Is Null) Or ([IndexationCalcule_Transporteur].[TransporteurID] = @TransporteurID))
And ((@FactureID Is Null) Or ([IndexationCalcule_Transporteur].[FactureID] = @FactureID))
)



