CREATE FUNCTION [dbo].[fnIndexationCalcule_Producteur_Full]
(@ID INT=Null, @TypeIndexation CHAR (1)=Null, @IndexationID INT=Null, @IndexationDetailID INT=Null, @LivraisonID INT=Null, @LivraisonDetailID INT=Null, @ProducteurID VARCHAR (15)=Null, @ContratID VARCHAR (10)=Null, @EssenceID VARCHAR (6)=Null, @Code CHAR (4)=Null, @UniteID VARCHAR (6)=Null, @FactureID INT=Null)
RETURNS TABLE 
AS
RETURN 
    (
Select TOP 100 PERCENT
 [IndexationCalcule_Producteur].[ID]
,[IndexationCalcule_Producteur].[DateCalcul]
,[IndexationCalcule_Producteur].[TypeIndexation]
,[IndexationCalcule_Producteur].[IndexationID]
,[IndexationCalcule_Producteur].[IndexationDetailID]
,[IndexationCalcule_Producteur].[LivraisonID]
,[IndexationCalcule_Producteur].[LivraisonDetailID]
,[IndexationCalcule_Producteur].[ProducteurID]
,[IndexationCalcule_Producteur].[ContratID]
,[IndexationCalcule_Producteur].[EssenceID]
,[IndexationCalcule_Producteur].[Code]
,[IndexationCalcule_Producteur].[UniteID]
,[IndexationCalcule_Producteur].[Volume]
,[IndexationCalcule_Producteur].[MontantDejaPaye]
,[IndexationCalcule_Producteur].[PourcentageDuMontant]
,[IndexationCalcule_Producteur].[Taux]
,[IndexationCalcule_Producteur].[Montant]
,[IndexationCalcule_Producteur].[Facture]
,[IndexationCalcule_Producteur].[FactureID]
,[IndexationCalcule_Producteur].[ErreurCalcul]
,[IndexationCalcule_Producteur].[ErreurDescription]
,[TypeIndexation1].[ID] [TypeIndexation_ID]
,[TypeIndexation1].[Description] [TypeIndexation_Description]
,[Indexation2].[ID] [IndexationID_ID]
,[Indexation2].[DateIndexation] [IndexationID_DateIndexation]
,[Indexation2].[ContratID] [IndexationID_ContratID]
,[Indexation2].[Periode_Debut] [IndexationID_Periode_Debut]
,[Indexation2].[Periode_Fin] [IndexationID_Periode_Fin]
,[Indexation2].[TypeIndexation] [IndexationID_TypeIndexation]
,[Indexation2].[PourcentageDuMontant] [IndexationID_PourcentageDuMontant]
,[Indexation2].[Facture] [IndexationID_Facture]
,[Indexation2].[IndexationTransporteur] [IndexationID_IndexationTransporteur]
,[Indexation2].[Date_Debut] [IndexationID_Date_Debut]
,[Indexation2].[Date_Fin] [IndexationID_Date_Fin]
,[Indexation2].[IndexationManuelle] [IndexationID_IndexationManuelle]
,[Indexation_EssenceUnite3].[ID] [IndexationDetailID_ID]
,[Indexation_EssenceUnite3].[IndexationID] [IndexationDetailID_IndexationID]
,[Indexation_EssenceUnite3].[ContratID] [IndexationDetailID_ContratID]
,[Indexation_EssenceUnite3].[EssenceID] [IndexationDetailID_EssenceID]
,[Indexation_EssenceUnite3].[Code] [IndexationDetailID_Code]
,[Indexation_EssenceUnite3].[UniteID] [IndexationDetailID_UniteID]
,[Indexation_EssenceUnite3].[Taux] [IndexationDetailID_Taux]
,[Livraison4].[ID] [LivraisonID_ID]
,[Livraison4].[DateLivraison] [LivraisonID_DateLivraison]
,[Livraison4].[DatePaye] [LivraisonID_DatePaye]
,[Livraison4].[ContratID] [LivraisonID_ContratID]
,[Livraison4].[UniteMesureID] [LivraisonID_UniteMesureID]
,[Livraison4].[EssenceID] [LivraisonID_EssenceID]
,[Livraison4].[Sciage] [LivraisonID_Sciage]
,[Livraison4].[NumeroFactureUsine] [LivraisonID_NumeroFactureUsine]
,[Livraison4].[DroitCoupeID] [LivraisonID_DroitCoupeID]
,[Livraison4].[EntentePaiementID] [LivraisonID_EntentePaiementID]
,[Livraison4].[TransporteurID] [LivraisonID_TransporteurID]
,[Livraison4].[VR] [LivraisonID_VR]
,[Livraison4].[MasseLimite] [LivraisonID_MasseLimite]
,[Livraison4].[VolumeBrut] [LivraisonID_VolumeBrut]
,[Livraison4].[VolumeTare] [LivraisonID_VolumeTare]
,[Livraison4].[VolumeTransporte] [LivraisonID_VolumeTransporte]
,[Livraison4].[VolumeSurcharge] [LivraisonID_VolumeSurcharge]
,[Livraison4].[VolumeAPayer] [LivraisonID_VolumeAPayer]
,[Livraison4].[Annee] [LivraisonID_Annee]
,[Livraison4].[Periode] [LivraisonID_Periode]
,[Livraison4].[DateCalcul] [LivraisonID_DateCalcul]
,[Livraison4].[Taux_Transporteur] [LivraisonID_Taux_Transporteur]
,[Livraison4].[Montant_Transporteur] [LivraisonID_Montant_Transporteur]
,[Livraison4].[Montant_Usine] [LivraisonID_Montant_Usine]
,[Livraison4].[Montant_Producteur1] [LivraisonID_Montant_Producteur1]
,[Livraison4].[Montant_Producteur2] [LivraisonID_Montant_Producteur2]
,[Livraison4].[Montant_Preleve_Plan_Conjoint] [LivraisonID_Montant_Preleve_Plan_Conjoint]
,[Livraison4].[Montant_Preleve_Fond_Roulement] [LivraisonID_Montant_Preleve_Fond_Roulement]
,[Livraison4].[Montant_Preleve_Fond_Forestier] [LivraisonID_Montant_Preleve_Fond_Forestier]
,[Livraison4].[Montant_Preleve_Divers] [LivraisonID_Montant_Preleve_Divers]
,[Livraison4].[Montant_Surcharge] [LivraisonID_Montant_Surcharge]
,[Livraison4].[Montant_MiseEnCommun] [LivraisonID_Montant_MiseEnCommun]
,[Livraison4].[Facture] [LivraisonID_Facture]
,[Livraison4].[Producteur1_FactureID] [LivraisonID_Producteur1_FactureID]
,[Livraison4].[Producteur2_FactureID] [LivraisonID_Producteur2_FactureID]
,[Livraison4].[Transporteur_FactureID] [LivraisonID_Transporteur_FactureID]
,[Livraison4].[Usine_FactureID] [LivraisonID_Usine_FactureID]
,[Livraison4].[ErreurCalcul] [LivraisonID_ErreurCalcul]
,[Livraison4].[ErreurDescription] [LivraisonID_ErreurDescription]
,[Livraison4].[LotID] [LivraisonID_LotID]
,[Livraison4].[Taux_Transporteur_Override] [LivraisonID_Taux_Transporteur_Override]
,[Livraison4].[PaieTransporteur] [LivraisonID_PaieTransporteur]
,[Livraison4].[VolumeSurcharge_Override] [LivraisonID_VolumeSurcharge_Override]
,[Livraison4].[SurchargeManuel] [LivraisonID_SurchargeManuel]
,[Livraison4].[Code] [LivraisonID_Code]
,[Livraison4].[NombrePermis] [LivraisonID_NombrePermis]
,[Livraison4].[ZoneID] [LivraisonID_ZoneID]
,[Livraison4].[MunicipaliteID] [LivraisonID_MunicipaliteID]
,[Livraison4].[ChargeurID] [LivraisonID_ChargeurID]
,[Livraison4].[Montant_Chargeur] [LivraisonID_Montant_Chargeur]
,[Livraison4].[Frais_ChargeurAuProducteur] [LivraisonID_Frais_ChargeurAuProducteur]
,[Livraison4].[Frais_ChargeurAuTransporteur] [LivraisonID_Frais_ChargeurAuTransporteur]
,[Livraison4].[Frais_AutresAuProducteur] [LivraisonID_Frais_AutresAuProducteur]
,[Livraison4].[Frais_AutresAuProducteurDescription] [LivraisonID_Frais_AutresAuProducteurDescription]
,[Livraison4].[Frais_AutresAuTransporteur] [LivraisonID_Frais_AutresAuTransporteur]
,[Livraison4].[Frais_AutresAuTransporteurDescription] [LivraisonID_Frais_AutresAuTransporteurDescription]
,[Livraison4].[Frais_CompensationDeDeplacement] [LivraisonID_Frais_CompensationDeDeplacement]
,[Livraison4].[Chargeur_FactureID] [LivraisonID_Chargeur_FactureID]
,[Livraison4].[Commentaires_Producteur] [LivraisonID_Commentaires_Producteur]
,[Livraison4].[Commentaires_Transporteur] [LivraisonID_Commentaires_Transporteur]
,[Livraison4].[Commentaires_Chargeur] [LivraisonID_Commentaires_Chargeur]
,[Livraison4].[TauxChargeurAuProducteur] [LivraisonID_TauxChargeurAuProducteur]
,[Livraison4].[TauxChargeurAuTransporteur] [LivraisonID_TauxChargeurAuTransporteur]
,[Livraison4].[Frais_AutresRevenusTransporteur] [LivraisonID_Frais_AutresRevenusTransporteur]
,[Livraison4].[Frais_AutresRevenusTransporteurDescription] [LivraisonID_Frais_AutresRevenusTransporteurDescription]
,[Livraison4].[Frais_AutresRevenusProducteur] [LivraisonID_Frais_AutresRevenusProducteur]
,[Livraison4].[Frais_AutresRevenusProducteurDescription] [LivraisonID_Frais_AutresRevenusProducteurDescription]
,[Livraison4].[Montant_SurchargeProducteur] [LivraisonID_Montant_SurchargeProducteur]
,[Livraison_Detail5].[ID] [LivraisonDetailID_ID]
,[Livraison_Detail5].[LivraisonID] [LivraisonDetailID_LivraisonID]
,[Livraison_Detail5].[ContratID] [LivraisonDetailID_ContratID]
,[Livraison_Detail5].[EssenceID] [LivraisonDetailID_EssenceID]
,[Livraison_Detail5].[UniteMesureID] [LivraisonDetailID_UniteMesureID]
,[Livraison_Detail5].[ProducteurID] [LivraisonDetailID_ProducteurID]
,[Livraison_Detail5].[Droit_Coupe] [LivraisonDetailID_Droit_Coupe]
,[Livraison_Detail5].[VolumeBrut] [LivraisonDetailID_VolumeBrut]
,[Livraison_Detail5].[VolumeReduction] [LivraisonDetailID_VolumeReduction]
,[Livraison_Detail5].[VolumeNet] [LivraisonDetailID_VolumeNet]
,[Livraison_Detail5].[VolumeContingente] [LivraisonDetailID_VolumeContingente]
,[Livraison_Detail5].[ContingentementID] [LivraisonDetailID_ContingentementID]
,[Livraison_Detail5].[DateCalcul] [LivraisonDetailID_DateCalcul]
,[Livraison_Detail5].[Taux_Usine] [LivraisonDetailID_Taux_Usine]
,[Livraison_Detail5].[Montant_Usine] [LivraisonDetailID_Montant_Usine]
,[Livraison_Detail5].[Taux_Producteur] [LivraisonDetailID_Taux_Producteur]
,[Livraison_Detail5].[Montant_ProducteurBrut] [LivraisonDetailID_Montant_ProducteurBrut]
,[Livraison_Detail5].[Taux_TransporteurMoyen] [LivraisonDetailID_Taux_TransporteurMoyen]
,[Livraison_Detail5].[Taux_TransporteurMoyen_Override] [LivraisonDetailID_Taux_TransporteurMoyen_Override]
,[Livraison_Detail5].[Montant_TransporteurMoyen] [LivraisonDetailID_Montant_TransporteurMoyen]
,[Livraison_Detail5].[Taux_Preleve_Plan_Conjoint] [LivraisonDetailID_Taux_Preleve_Plan_Conjoint]
,[Livraison_Detail5].[Montant_Preleve_Plan_Conjoint] [LivraisonDetailID_Montant_Preleve_Plan_Conjoint]
,[Livraison_Detail5].[Taux_Preleve_Fond_Roulement] [LivraisonDetailID_Taux_Preleve_Fond_Roulement]
,[Livraison_Detail5].[Montant_Preleve_Fond_Roulement] [LivraisonDetailID_Montant_Preleve_Fond_Roulement]
,[Livraison_Detail5].[Taux_Preleve_Fond_Forestier] [LivraisonDetailID_Taux_Preleve_Fond_Forestier]
,[Livraison_Detail5].[Montant_Preleve_Fond_Forestier] [LivraisonDetailID_Montant_Preleve_Fond_Forestier]
,[Livraison_Detail5].[Taux_Preleve_Divers] [LivraisonDetailID_Taux_Preleve_Divers]
,[Livraison_Detail5].[Montant_Preleve_Divers] [LivraisonDetailID_Montant_Preleve_Divers]
,[Livraison_Detail5].[Montant_ProducteurNet] [LivraisonDetailID_Montant_ProducteurNet]
,[Livraison_Detail5].[Taux_Producteur_Override] [LivraisonDetailID_Taux_Producteur_Override]
,[Livraison_Detail5].[Taux_Usine_Override] [LivraisonDetailID_Taux_Usine_Override]
,[Livraison_Detail5].[Code] [LivraisonDetailID_Code]
,[Livraison_Detail5].[UsePreleveMontant] [LivraisonDetailID_UsePreleveMontant]
,[Fournisseur6].[ID] [ProducteurID_ID]
,[Fournisseur6].[CleTri] [ProducteurID_CleTri]
,[Fournisseur6].[Nom] [ProducteurID_Nom]
,[Fournisseur6].[AuSoinsDe] [ProducteurID_AuSoinsDe]
,[Fournisseur6].[Rue] [ProducteurID_Rue]
,[Fournisseur6].[Ville] [ProducteurID_Ville]
,[Fournisseur6].[PaysID] [ProducteurID_PaysID]
,[Fournisseur6].[Code_postal] [ProducteurID_Code_postal]
,[Fournisseur6].[Telephone] [ProducteurID_Telephone]
,[Fournisseur6].[Telephone_Poste] [ProducteurID_Telephone_Poste]
,[Fournisseur6].[Telecopieur] [ProducteurID_Telecopieur]
,[Fournisseur6].[Telephone2] [ProducteurID_Telephone2]
,[Fournisseur6].[Telephone2_Desc] [ProducteurID_Telephone2_Desc]
,[Fournisseur6].[Telephone2_Poste] [ProducteurID_Telephone2_Poste]
,[Fournisseur6].[Telephone3] [ProducteurID_Telephone3]
,[Fournisseur6].[Telephone3_Desc] [ProducteurID_Telephone3_Desc]
,[Fournisseur6].[Telephone3_Poste] [ProducteurID_Telephone3_Poste]
,[Fournisseur6].[No_membre] [ProducteurID_No_membre]
,[Fournisseur6].[Resident] [ProducteurID_Resident]
,[Fournisseur6].[Email] [ProducteurID_Email]
,[Fournisseur6].[WWW] [ProducteurID_WWW]
,[Fournisseur6].[Commentaires] [ProducteurID_Commentaires]
,[Fournisseur6].[AfficherCommentaires] [ProducteurID_AfficherCommentaires]
,[Fournisseur6].[DepotDirect] [ProducteurID_DepotDirect]
,[Fournisseur6].[InstitutionBanquaireID] [ProducteurID_InstitutionBanquaireID]
,[Fournisseur6].[Banque_transit] [ProducteurID_Banque_transit]
,[Fournisseur6].[Banque_folio] [ProducteurID_Banque_folio]
,[Fournisseur6].[No_TPS] [ProducteurID_No_TPS]
,[Fournisseur6].[No_TVQ] [ProducteurID_No_TVQ]
,[Fournisseur6].[PayerA] [ProducteurID_PayerA]
,[Fournisseur6].[PayerAID] [ProducteurID_PayerAID]
,[Fournisseur6].[Statut] [ProducteurID_Statut]
,[Fournisseur6].[Rep_Nom] [ProducteurID_Rep_Nom]
,[Fournisseur6].[Rep_Telephone] [ProducteurID_Rep_Telephone]
,[Fournisseur6].[Rep_Telephone_Poste] [ProducteurID_Rep_Telephone_Poste]
,[Fournisseur6].[Rep_Email] [ProducteurID_Rep_Email]
,[Fournisseur6].[EnAnglais] [ProducteurID_EnAnglais]
,[Fournisseur6].[Actif] [ProducteurID_Actif]
,[Fournisseur6].[MRCProducteurID] [ProducteurID_MRCProducteurID]
,[Fournisseur6].[PaiementManuel] [ProducteurID_PaiementManuel]
,[Fournisseur6].[Journal] [ProducteurID_Journal]
,[Fournisseur6].[RecoitTPS] [ProducteurID_RecoitTPS]
,[Fournisseur6].[RecoitTVQ] [ProducteurID_RecoitTVQ]
,[Fournisseur6].[ModifierTrigger] [ProducteurID_ModifierTrigger]
,[Fournisseur6].[IsProducteur] [ProducteurID_IsProducteur]
,[Fournisseur6].[IsTransporteur] [ProducteurID_IsTransporteur]
,[Fournisseur6].[IsChargeur] [ProducteurID_IsChargeur]
,[Fournisseur6].[IsAutre] [ProducteurID_IsAutre]
,[Fournisseur6].[AfficherCommentairesSurPermit] [ProducteurID_AfficherCommentairesSurPermit]
,[Fournisseur6].[PasEmissionPermis] [ProducteurID_PasEmissionPermis]
,[Fournisseur6].[Generique] [ProducteurID_Generique]
,[Contrat_EssenceUnite7].[ContratID] [ContratID_ContratID]
,[Contrat_EssenceUnite7].[EssenceID] [ContratID_EssenceID]
,[Contrat_EssenceUnite7].[UniteID] [ContratID_UniteID]
,[Contrat_EssenceUnite7].[Code] [ContratID_Code]
,[Contrat_EssenceUnite7].[Quantite_prevue] [ContratID_Quantite_prevue]
,[Contrat_EssenceUnite7].[Taux_usine] [ContratID_Taux_usine]
,[Contrat_EssenceUnite7].[Taux_producteur] [ContratID_Taux_producteur]
,[Contrat_EssenceUnite7].[Actif] [ContratID_Actif]
,[Contrat_EssenceUnite7].[Description] [ContratID_Description]
,[Contrat_EssenceUnite8].[ContratID] [EssenceID_ContratID]
,[Contrat_EssenceUnite8].[EssenceID] [EssenceID_EssenceID]
,[Contrat_EssenceUnite8].[UniteID] [EssenceID_UniteID]
,[Contrat_EssenceUnite8].[Code] [EssenceID_Code]
,[Contrat_EssenceUnite8].[Quantite_prevue] [EssenceID_Quantite_prevue]
,[Contrat_EssenceUnite8].[Taux_usine] [EssenceID_Taux_usine]
,[Contrat_EssenceUnite8].[Taux_producteur] [EssenceID_Taux_producteur]
,[Contrat_EssenceUnite8].[Actif] [EssenceID_Actif]
,[Contrat_EssenceUnite8].[Description] [EssenceID_Description]
,[Contrat_EssenceUnite9].[ContratID] [Code_ContratID]
,[Contrat_EssenceUnite9].[EssenceID] [Code_EssenceID]
,[Contrat_EssenceUnite9].[UniteID] [Code_UniteID]
,[Contrat_EssenceUnite9].[Code] [Code_Code]
,[Contrat_EssenceUnite9].[Quantite_prevue] [Code_Quantite_prevue]
,[Contrat_EssenceUnite9].[Taux_usine] [Code_Taux_usine]
,[Contrat_EssenceUnite9].[Taux_producteur] [Code_Taux_producteur]
,[Contrat_EssenceUnite9].[Actif] [Code_Actif]
,[Contrat_EssenceUnite9].[Description] [Code_Description]
,[Contrat_EssenceUnite10].[ContratID] [UniteID_ContratID]
,[Contrat_EssenceUnite10].[EssenceID] [UniteID_EssenceID]
,[Contrat_EssenceUnite10].[UniteID] [UniteID_UniteID]
,[Contrat_EssenceUnite10].[Code] [UniteID_Code]
,[Contrat_EssenceUnite10].[Quantite_prevue] [UniteID_Quantite_prevue]
,[Contrat_EssenceUnite10].[Taux_usine] [UniteID_Taux_usine]
,[Contrat_EssenceUnite10].[Taux_producteur] [UniteID_Taux_producteur]
,[Contrat_EssenceUnite10].[Actif] [UniteID_Actif]
,[Contrat_EssenceUnite10].[Description] [UniteID_Description]
,[FactureFournisseur11].[ID] [FactureID_ID]
,[FactureFournisseur11].[NoFacture] [FactureID_NoFacture]
,[FactureFournisseur11].[DateFacture] [FactureID_DateFacture]
,[FactureFournisseur11].[Annee] [FactureID_Annee]
,[FactureFournisseur11].[TypeFactureFournisseur] [FactureID_TypeFactureFournisseur]
,[FactureFournisseur11].[TypeFacture] [FactureID_TypeFacture]
,[FactureFournisseur11].[TypeInvoiceAcomba] [FactureID_TypeInvoiceAcomba]
,[FactureFournisseur11].[FournisseurID] [FactureID_FournisseurID]
,[FactureFournisseur11].[PayerAID] [FactureID_PayerAID]
,[FactureFournisseur11].[Montant_Total] [FactureID_Montant_Total]
,[FactureFournisseur11].[Montant_TPS] [FactureID_Montant_TPS]
,[FactureFournisseur11].[Montant_TVQ] [FactureID_Montant_TVQ]
,[FactureFournisseur11].[Description] [FactureID_Description]
,[FactureFournisseur11].[Status] [FactureID_Status]
,[FactureFournisseur11].[StatusDescription] [FactureID_StatusDescription]
,[FactureFournisseur11].[NumeroCheque] [FactureID_NumeroCheque]
,[FactureFournisseur11].[NumeroPaiement] [FactureID_NumeroPaiement]
,[FactureFournisseur11].[NumeroPaiementUnique] [FactureID_NumeroPaiementUnique]
,[FactureFournisseur11].[DateFactureAcomba] [FactureID_DateFactureAcomba]
,[FactureFournisseur11].[DatePaiementAcomba] [FactureID_DatePaiementAcomba]

From [dbo].[IndexationCalcule_Producteur] [IndexationCalcule_Producteur]
    Left Outer Join [dbo].[TypeIndexation] [TypeIndexation1] On [IndexationCalcule_Producteur].[TypeIndexation] = [TypeIndexation1].[ID]
        Left Outer Join [dbo].[Indexation] [Indexation2] On [IndexationCalcule_Producteur].[IndexationID] = [Indexation2].[ID]
            Left Outer Join [dbo].[Indexation_EssenceUnite] [Indexation_EssenceUnite3] On [IndexationCalcule_Producteur].[IndexationDetailID] = [Indexation_EssenceUnite3].[ID]
                Left Outer Join [dbo].[Livraison] [Livraison4] On [IndexationCalcule_Producteur].[LivraisonID] = [Livraison4].[ID]
                    Left Outer Join [dbo].[Livraison_Detail] [Livraison_Detail5] On [IndexationCalcule_Producteur].[LivraisonDetailID] = [Livraison_Detail5].[ID]
                        Left Outer Join [dbo].[Fournisseur] [Fournisseur6] On [IndexationCalcule_Producteur].[ProducteurID] = [Fournisseur6].[ID]
                            Left Outer Join [dbo].[Contrat_EssenceUnite] [Contrat_EssenceUnite7] On [IndexationCalcule_Producteur].[ContratID] = [Contrat_EssenceUnite7].[ContratID]
                                Left Outer Join [dbo].[Contrat_EssenceUnite] [Contrat_EssenceUnite8] On [IndexationCalcule_Producteur].[EssenceID] = [Contrat_EssenceUnite8].[EssenceID]
                                    Left Outer Join [dbo].[Contrat_EssenceUnite] [Contrat_EssenceUnite9] On [IndexationCalcule_Producteur].[Code] = [Contrat_EssenceUnite9].[Code]
                                        Left Outer Join [dbo].[Contrat_EssenceUnite] [Contrat_EssenceUnite10] On [IndexationCalcule_Producteur].[UniteID] = [Contrat_EssenceUnite10].[UniteID]
                                            Left Outer Join [dbo].[FactureFournisseur] [FactureFournisseur11] On [IndexationCalcule_Producteur].[FactureID] = [FactureFournisseur11].[ID]

Where

    ((@ID Is Null) Or ([IndexationCalcule_Producteur].[ID] = @ID))
And ((@TypeIndexation Is Null) Or ([IndexationCalcule_Producteur].[TypeIndexation] = @TypeIndexation))
And ((@IndexationID Is Null) Or ([IndexationCalcule_Producteur].[IndexationID] = @IndexationID))
And ((@IndexationDetailID Is Null) Or ([IndexationCalcule_Producteur].[IndexationDetailID] = @IndexationDetailID))
And ((@LivraisonID Is Null) Or ([IndexationCalcule_Producteur].[LivraisonID] = @LivraisonID))
And ((@LivraisonDetailID Is Null) Or ([IndexationCalcule_Producteur].[LivraisonDetailID] = @LivraisonDetailID))
And ((@ProducteurID Is Null) Or ([IndexationCalcule_Producteur].[ProducteurID] = @ProducteurID))
And ((@ContratID Is Null) Or ([IndexationCalcule_Producteur].[ContratID] = @ContratID))
And ((@EssenceID Is Null) Or ([IndexationCalcule_Producteur].[EssenceID] = @EssenceID))
And ((@Code Is Null) Or ([IndexationCalcule_Producteur].[Code] = @Code))
And ((@UniteID Is Null) Or ([IndexationCalcule_Producteur].[UniteID] = @UniteID))
And ((@FactureID Is Null) Or ([IndexationCalcule_Producteur].[FactureID] = @FactureID))
)



