

CREATE Function [fnjag_System_Full]

(
 @Fournisseur_PlanConjoint [varchar](15) = Null
,@Fournisseur_Surcharge [varchar](15) = Null
,@Compte_Paiements [int] = Null
,@Compte_ARecevoir [int] = Null
,@Compte_APayer [int] = Null
,@Compte_DuAuxProducteurs [int] = Null
,@Compte_TPSpercues [int] = Null
,@Compte_TPSpayees [int] = Null
,@Compte_TVQpercues [int] = Null
,@Compte_TVQpayees [int] = Null
,@Fournisseur_Fond_Roulement [varchar](15) = Null
,@Fournisseur_Fond_Forestier [varchar](15) = Null
,@Fournisseur_Preleve_Divers [varchar](15) = Null
)


--	IMPORTANT:
--	Changes to this SQL code may cause incorrect behavior
--	and will be lost if the code is regenerated. 


Returns Table

As

Return
(
Select TOP 100 PERCENT
 [jag_System].[Fournisseur_PlanConjoint]
,[jag_System].[Fournisseur_Surcharge]
,[jag_System].[Compte_Paiements]
,[jag_System].[Compte_ARecevoir]
,[jag_System].[Compte_APayer]
,[jag_System].[Compte_DuAuxProducteurs]
,[jag_System].[Compte_TPSpercues]
,[jag_System].[Compte_TPSpayees]
,[jag_System].[Compte_TVQpercues]
,[jag_System].[Compte_TVQpayees]
,[jag_System].[Taux_TPS]
,[jag_System].[Taux_TVQ]
,[jag_System].[Fournisseur_Fond_Roulement]
,[jag_System].[Fournisseur_Fond_Forestier]
,[jag_System].[Fournisseur_Preleve_Divers]
,[Fournisseur1].[ID] [Fournisseur_PlanConjoint_ID]
,[Fournisseur1].[CleTri] [Fournisseur_PlanConjoint_CleTri]
,[Fournisseur1].[Nom] [Fournisseur_PlanConjoint_Nom]
,[Fournisseur1].[AuSoinsDe] [Fournisseur_PlanConjoint_AuSoinsDe]
,[Fournisseur1].[Rue] [Fournisseur_PlanConjoint_Rue]
,[Fournisseur1].[Ville] [Fournisseur_PlanConjoint_Ville]
,[Fournisseur1].[PaysID] [Fournisseur_PlanConjoint_PaysID]
,[Fournisseur1].[Code_postal] [Fournisseur_PlanConjoint_Code_postal]
,[Fournisseur1].[Telephone] [Fournisseur_PlanConjoint_Telephone]
,[Fournisseur1].[Telephone_Poste] [Fournisseur_PlanConjoint_Telephone_Poste]
,[Fournisseur1].[Telecopieur] [Fournisseur_PlanConjoint_Telecopieur]
,[Fournisseur1].[Telephone2] [Fournisseur_PlanConjoint_Telephone2]
,[Fournisseur1].[Telephone2_Desc] [Fournisseur_PlanConjoint_Telephone2_Desc]
,[Fournisseur1].[Telephone2_Poste] [Fournisseur_PlanConjoint_Telephone2_Poste]
,[Fournisseur1].[Telephone3] [Fournisseur_PlanConjoint_Telephone3]
,[Fournisseur1].[Telephone3_Desc] [Fournisseur_PlanConjoint_Telephone3_Desc]
,[Fournisseur1].[Telephone3_Poste] [Fournisseur_PlanConjoint_Telephone3_Poste]
,[Fournisseur1].[No_membre] [Fournisseur_PlanConjoint_No_membre]
,[Fournisseur1].[Resident] [Fournisseur_PlanConjoint_Resident]
,[Fournisseur1].[Email] [Fournisseur_PlanConjoint_Email]
,[Fournisseur1].[WWW] [Fournisseur_PlanConjoint_WWW]
,[Fournisseur1].[Commentaires] [Fournisseur_PlanConjoint_Commentaires]
,[Fournisseur1].[AfficherCommentaires] [Fournisseur_PlanConjoint_AfficherCommentaires]
,[Fournisseur1].[DepotDirect] [Fournisseur_PlanConjoint_DepotDirect]
,[Fournisseur1].[InstitutionBanquaireID] [Fournisseur_PlanConjoint_InstitutionBanquaireID]
,[Fournisseur1].[Banque_transit] [Fournisseur_PlanConjoint_Banque_transit]
,[Fournisseur1].[Banque_folio] [Fournisseur_PlanConjoint_Banque_folio]
,[Fournisseur1].[No_TPS] [Fournisseur_PlanConjoint_No_TPS]
,[Fournisseur1].[No_TVQ] [Fournisseur_PlanConjoint_No_TVQ]
,[Fournisseur1].[PayerA] [Fournisseur_PlanConjoint_PayerA]
,[Fournisseur1].[PayerAID] [Fournisseur_PlanConjoint_PayerAID]
,[Fournisseur1].[Statut] [Fournisseur_PlanConjoint_Statut]
,[Fournisseur1].[Rep_Nom] [Fournisseur_PlanConjoint_Rep_Nom]
,[Fournisseur1].[Rep_Telephone] [Fournisseur_PlanConjoint_Rep_Telephone]
,[Fournisseur1].[Rep_Telephone_Poste] [Fournisseur_PlanConjoint_Rep_Telephone_Poste]
,[Fournisseur1].[Rep_Email] [Fournisseur_PlanConjoint_Rep_Email]
,[Fournisseur1].[EnAnglais] [Fournisseur_PlanConjoint_EnAnglais]
,[Fournisseur1].[Actif] [Fournisseur_PlanConjoint_Actif]
,[Fournisseur1].[MRCProducteurID] [Fournisseur_PlanConjoint_MRCProducteurID]
,[Fournisseur1].[PaiementManuel] [Fournisseur_PlanConjoint_PaiementManuel]
,[Fournisseur1].[Journal] [Fournisseur_PlanConjoint_Journal]
,[Fournisseur1].[RecoitTPS] [Fournisseur_PlanConjoint_RecoitTPS]
,[Fournisseur1].[RecoitTVQ] [Fournisseur_PlanConjoint_RecoitTVQ]
,[Fournisseur1].[ModifierTrigger] [Fournisseur_PlanConjoint_ModifierTrigger]
,[Fournisseur1].[IsProducteur] [Fournisseur_PlanConjoint_IsProducteur]
,[Fournisseur1].[IsTransporteur] [Fournisseur_PlanConjoint_IsTransporteur]
,[Fournisseur1].[IsChargeur] [Fournisseur_PlanConjoint_IsChargeur]
,[Fournisseur1].[IsAutre] [Fournisseur_PlanConjoint_IsAutre]
,[Fournisseur1].[AfficherCommentairesSurPermit] [Fournisseur_PlanConjoint_AfficherCommentairesSurPermit]
,[Fournisseur1].[PasEmissionPermis] [Fournisseur_PlanConjoint_PasEmissionPermis]
,[Fournisseur1].[Generique] [Fournisseur_PlanConjoint_Generique]
,[Fournisseur2].[ID] [Fournisseur_Surcharge_ID]
,[Fournisseur2].[CleTri] [Fournisseur_Surcharge_CleTri]
,[Fournisseur2].[Nom] [Fournisseur_Surcharge_Nom]
,[Fournisseur2].[AuSoinsDe] [Fournisseur_Surcharge_AuSoinsDe]
,[Fournisseur2].[Rue] [Fournisseur_Surcharge_Rue]
,[Fournisseur2].[Ville] [Fournisseur_Surcharge_Ville]
,[Fournisseur2].[PaysID] [Fournisseur_Surcharge_PaysID]
,[Fournisseur2].[Code_postal] [Fournisseur_Surcharge_Code_postal]
,[Fournisseur2].[Telephone] [Fournisseur_Surcharge_Telephone]
,[Fournisseur2].[Telephone_Poste] [Fournisseur_Surcharge_Telephone_Poste]
,[Fournisseur2].[Telecopieur] [Fournisseur_Surcharge_Telecopieur]
,[Fournisseur2].[Telephone2] [Fournisseur_Surcharge_Telephone2]
,[Fournisseur2].[Telephone2_Desc] [Fournisseur_Surcharge_Telephone2_Desc]
,[Fournisseur2].[Telephone2_Poste] [Fournisseur_Surcharge_Telephone2_Poste]
,[Fournisseur2].[Telephone3] [Fournisseur_Surcharge_Telephone3]
,[Fournisseur2].[Telephone3_Desc] [Fournisseur_Surcharge_Telephone3_Desc]
,[Fournisseur2].[Telephone3_Poste] [Fournisseur_Surcharge_Telephone3_Poste]
,[Fournisseur2].[No_membre] [Fournisseur_Surcharge_No_membre]
,[Fournisseur2].[Resident] [Fournisseur_Surcharge_Resident]
,[Fournisseur2].[Email] [Fournisseur_Surcharge_Email]
,[Fournisseur2].[WWW] [Fournisseur_Surcharge_WWW]
,[Fournisseur2].[Commentaires] [Fournisseur_Surcharge_Commentaires]
,[Fournisseur2].[AfficherCommentaires] [Fournisseur_Surcharge_AfficherCommentaires]
,[Fournisseur2].[DepotDirect] [Fournisseur_Surcharge_DepotDirect]
,[Fournisseur2].[InstitutionBanquaireID] [Fournisseur_Surcharge_InstitutionBanquaireID]
,[Fournisseur2].[Banque_transit] [Fournisseur_Surcharge_Banque_transit]
,[Fournisseur2].[Banque_folio] [Fournisseur_Surcharge_Banque_folio]
,[Fournisseur2].[No_TPS] [Fournisseur_Surcharge_No_TPS]
,[Fournisseur2].[No_TVQ] [Fournisseur_Surcharge_No_TVQ]
,[Fournisseur2].[PayerA] [Fournisseur_Surcharge_PayerA]
,[Fournisseur2].[PayerAID] [Fournisseur_Surcharge_PayerAID]
,[Fournisseur2].[Statut] [Fournisseur_Surcharge_Statut]
,[Fournisseur2].[Rep_Nom] [Fournisseur_Surcharge_Rep_Nom]
,[Fournisseur2].[Rep_Telephone] [Fournisseur_Surcharge_Rep_Telephone]
,[Fournisseur2].[Rep_Telephone_Poste] [Fournisseur_Surcharge_Rep_Telephone_Poste]
,[Fournisseur2].[Rep_Email] [Fournisseur_Surcharge_Rep_Email]
,[Fournisseur2].[EnAnglais] [Fournisseur_Surcharge_EnAnglais]
,[Fournisseur2].[Actif] [Fournisseur_Surcharge_Actif]
,[Fournisseur2].[MRCProducteurID] [Fournisseur_Surcharge_MRCProducteurID]
,[Fournisseur2].[PaiementManuel] [Fournisseur_Surcharge_PaiementManuel]
,[Fournisseur2].[Journal] [Fournisseur_Surcharge_Journal]
,[Fournisseur2].[RecoitTPS] [Fournisseur_Surcharge_RecoitTPS]
,[Fournisseur2].[RecoitTVQ] [Fournisseur_Surcharge_RecoitTVQ]
,[Fournisseur2].[ModifierTrigger] [Fournisseur_Surcharge_ModifierTrigger]
,[Fournisseur2].[IsProducteur] [Fournisseur_Surcharge_IsProducteur]
,[Fournisseur2].[IsTransporteur] [Fournisseur_Surcharge_IsTransporteur]
,[Fournisseur2].[IsChargeur] [Fournisseur_Surcharge_IsChargeur]
,[Fournisseur2].[IsAutre] [Fournisseur_Surcharge_IsAutre]
,[Fournisseur2].[AfficherCommentairesSurPermit] [Fournisseur_Surcharge_AfficherCommentairesSurPermit]
,[Fournisseur2].[PasEmissionPermis] [Fournisseur_Surcharge_PasEmissionPermis]
,[Fournisseur2].[Generique] [Fournisseur_Surcharge_Generique]
,[Compte3].[ID] [Compte_Paiements_ID]
,[Compte3].[Description] [Compte_Paiements_Description]
,[Compte3].[CategoryID] [Compte_Paiements_CategoryID]
,[Compte3].[isTaxe] [Compte_Paiements_isTaxe]
,[Compte3].[Actif] [Compte_Paiements_Actif]
,[Compte4].[ID] [Compte_ARecevoir_ID]
,[Compte4].[Description] [Compte_ARecevoir_Description]
,[Compte4].[CategoryID] [Compte_ARecevoir_CategoryID]
,[Compte4].[isTaxe] [Compte_ARecevoir_isTaxe]
,[Compte4].[Actif] [Compte_ARecevoir_Actif]
,[Compte5].[ID] [Compte_APayer_ID]
,[Compte5].[Description] [Compte_APayer_Description]
,[Compte5].[CategoryID] [Compte_APayer_CategoryID]
,[Compte5].[isTaxe] [Compte_APayer_isTaxe]
,[Compte5].[Actif] [Compte_APayer_Actif]
,[Compte6].[ID] [Compte_DuAuxProducteurs_ID]
,[Compte6].[Description] [Compte_DuAuxProducteurs_Description]
,[Compte6].[CategoryID] [Compte_DuAuxProducteurs_CategoryID]
,[Compte6].[isTaxe] [Compte_DuAuxProducteurs_isTaxe]
,[Compte6].[Actif] [Compte_DuAuxProducteurs_Actif]
,[Compte7].[ID] [Compte_TPSpercues_ID]
,[Compte7].[Description] [Compte_TPSpercues_Description]
,[Compte7].[CategoryID] [Compte_TPSpercues_CategoryID]
,[Compte7].[isTaxe] [Compte_TPSpercues_isTaxe]
,[Compte7].[Actif] [Compte_TPSpercues_Actif]
,[Compte8].[ID] [Compte_TPSpayees_ID]
,[Compte8].[Description] [Compte_TPSpayees_Description]
,[Compte8].[CategoryID] [Compte_TPSpayees_CategoryID]
,[Compte8].[isTaxe] [Compte_TPSpayees_isTaxe]
,[Compte8].[Actif] [Compte_TPSpayees_Actif]
,[Compte9].[ID] [Compte_TVQpercues_ID]
,[Compte9].[Description] [Compte_TVQpercues_Description]
,[Compte9].[CategoryID] [Compte_TVQpercues_CategoryID]
,[Compte9].[isTaxe] [Compte_TVQpercues_isTaxe]
,[Compte9].[Actif] [Compte_TVQpercues_Actif]
,[Compte10].[ID] [Compte_TVQpayees_ID]
,[Compte10].[Description] [Compte_TVQpayees_Description]
,[Compte10].[CategoryID] [Compte_TVQpayees_CategoryID]
,[Compte10].[isTaxe] [Compte_TVQpayees_isTaxe]
,[Compte10].[Actif] [Compte_TVQpayees_Actif]
,[Fournisseur11].[ID] [Fournisseur_Fond_Roulement_ID]
,[Fournisseur11].[CleTri] [Fournisseur_Fond_Roulement_CleTri]
,[Fournisseur11].[Nom] [Fournisseur_Fond_Roulement_Nom]
,[Fournisseur11].[AuSoinsDe] [Fournisseur_Fond_Roulement_AuSoinsDe]
,[Fournisseur11].[Rue] [Fournisseur_Fond_Roulement_Rue]
,[Fournisseur11].[Ville] [Fournisseur_Fond_Roulement_Ville]
,[Fournisseur11].[PaysID] [Fournisseur_Fond_Roulement_PaysID]
,[Fournisseur11].[Code_postal] [Fournisseur_Fond_Roulement_Code_postal]
,[Fournisseur11].[Telephone] [Fournisseur_Fond_Roulement_Telephone]
,[Fournisseur11].[Telephone_Poste] [Fournisseur_Fond_Roulement_Telephone_Poste]
,[Fournisseur11].[Telecopieur] [Fournisseur_Fond_Roulement_Telecopieur]
,[Fournisseur11].[Telephone2] [Fournisseur_Fond_Roulement_Telephone2]
,[Fournisseur11].[Telephone2_Desc] [Fournisseur_Fond_Roulement_Telephone2_Desc]
,[Fournisseur11].[Telephone2_Poste] [Fournisseur_Fond_Roulement_Telephone2_Poste]
,[Fournisseur11].[Telephone3] [Fournisseur_Fond_Roulement_Telephone3]
,[Fournisseur11].[Telephone3_Desc] [Fournisseur_Fond_Roulement_Telephone3_Desc]
,[Fournisseur11].[Telephone3_Poste] [Fournisseur_Fond_Roulement_Telephone3_Poste]
,[Fournisseur11].[No_membre] [Fournisseur_Fond_Roulement_No_membre]
,[Fournisseur11].[Resident] [Fournisseur_Fond_Roulement_Resident]
,[Fournisseur11].[Email] [Fournisseur_Fond_Roulement_Email]
,[Fournisseur11].[WWW] [Fournisseur_Fond_Roulement_WWW]
,[Fournisseur11].[Commentaires] [Fournisseur_Fond_Roulement_Commentaires]
,[Fournisseur11].[AfficherCommentaires] [Fournisseur_Fond_Roulement_AfficherCommentaires]
,[Fournisseur11].[DepotDirect] [Fournisseur_Fond_Roulement_DepotDirect]
,[Fournisseur11].[InstitutionBanquaireID] [Fournisseur_Fond_Roulement_InstitutionBanquaireID]
,[Fournisseur11].[Banque_transit] [Fournisseur_Fond_Roulement_Banque_transit]
,[Fournisseur11].[Banque_folio] [Fournisseur_Fond_Roulement_Banque_folio]
,[Fournisseur11].[No_TPS] [Fournisseur_Fond_Roulement_No_TPS]
,[Fournisseur11].[No_TVQ] [Fournisseur_Fond_Roulement_No_TVQ]
,[Fournisseur11].[PayerA] [Fournisseur_Fond_Roulement_PayerA]
,[Fournisseur11].[PayerAID] [Fournisseur_Fond_Roulement_PayerAID]
,[Fournisseur11].[Statut] [Fournisseur_Fond_Roulement_Statut]
,[Fournisseur11].[Rep_Nom] [Fournisseur_Fond_Roulement_Rep_Nom]
,[Fournisseur11].[Rep_Telephone] [Fournisseur_Fond_Roulement_Rep_Telephone]
,[Fournisseur11].[Rep_Telephone_Poste] [Fournisseur_Fond_Roulement_Rep_Telephone_Poste]
,[Fournisseur11].[Rep_Email] [Fournisseur_Fond_Roulement_Rep_Email]
,[Fournisseur11].[EnAnglais] [Fournisseur_Fond_Roulement_EnAnglais]
,[Fournisseur11].[Actif] [Fournisseur_Fond_Roulement_Actif]
,[Fournisseur11].[MRCProducteurID] [Fournisseur_Fond_Roulement_MRCProducteurID]
,[Fournisseur11].[PaiementManuel] [Fournisseur_Fond_Roulement_PaiementManuel]
,[Fournisseur11].[Journal] [Fournisseur_Fond_Roulement_Journal]
,[Fournisseur11].[RecoitTPS] [Fournisseur_Fond_Roulement_RecoitTPS]
,[Fournisseur11].[RecoitTVQ] [Fournisseur_Fond_Roulement_RecoitTVQ]
,[Fournisseur11].[ModifierTrigger] [Fournisseur_Fond_Roulement_ModifierTrigger]
,[Fournisseur11].[IsProducteur] [Fournisseur_Fond_Roulement_IsProducteur]
,[Fournisseur11].[IsTransporteur] [Fournisseur_Fond_Roulement_IsTransporteur]
,[Fournisseur11].[IsChargeur] [Fournisseur_Fond_Roulement_IsChargeur]
,[Fournisseur11].[IsAutre] [Fournisseur_Fond_Roulement_IsAutre]
,[Fournisseur11].[AfficherCommentairesSurPermit] [Fournisseur_Fond_Roulement_AfficherCommentairesSurPermit]
,[Fournisseur11].[PasEmissionPermis] [Fournisseur_Fond_Roulement_PasEmissionPermis]
,[Fournisseur12].[ID] [Fournisseur_Fond_Forestier_ID]
,[Fournisseur12].[CleTri] [Fournisseur_Fond_Forestier_CleTri]
,[Fournisseur12].[Nom] [Fournisseur_Fond_Forestier_Nom]
,[Fournisseur12].[AuSoinsDe] [Fournisseur_Fond_Forestier_AuSoinsDe]
,[Fournisseur12].[Rue] [Fournisseur_Fond_Forestier_Rue]
,[Fournisseur12].[Ville] [Fournisseur_Fond_Forestier_Ville]
,[Fournisseur12].[PaysID] [Fournisseur_Fond_Forestier_PaysID]
,[Fournisseur12].[Code_postal] [Fournisseur_Fond_Forestier_Code_postal]
,[Fournisseur12].[Telephone] [Fournisseur_Fond_Forestier_Telephone]
,[Fournisseur12].[Telephone_Poste] [Fournisseur_Fond_Forestier_Telephone_Poste]
,[Fournisseur12].[Telecopieur] [Fournisseur_Fond_Forestier_Telecopieur]
,[Fournisseur12].[Telephone2] [Fournisseur_Fond_Forestier_Telephone2]
,[Fournisseur12].[Telephone2_Desc] [Fournisseur_Fond_Forestier_Telephone2_Desc]
,[Fournisseur12].[Telephone2_Poste] [Fournisseur_Fond_Forestier_Telephone2_Poste]
,[Fournisseur12].[Telephone3] [Fournisseur_Fond_Forestier_Telephone3]
,[Fournisseur12].[Telephone3_Desc] [Fournisseur_Fond_Forestier_Telephone3_Desc]
,[Fournisseur12].[Telephone3_Poste] [Fournisseur_Fond_Forestier_Telephone3_Poste]
,[Fournisseur12].[No_membre] [Fournisseur_Fond_Forestier_No_membre]
,[Fournisseur12].[Resident] [Fournisseur_Fond_Forestier_Resident]
,[Fournisseur12].[Email] [Fournisseur_Fond_Forestier_Email]
,[Fournisseur12].[WWW] [Fournisseur_Fond_Forestier_WWW]
,[Fournisseur12].[Commentaires] [Fournisseur_Fond_Forestier_Commentaires]
,[Fournisseur12].[AfficherCommentaires] [Fournisseur_Fond_Forestier_AfficherCommentaires]
,[Fournisseur12].[DepotDirect] [Fournisseur_Fond_Forestier_DepotDirect]
,[Fournisseur12].[InstitutionBanquaireID] [Fournisseur_Fond_Forestier_InstitutionBanquaireID]
,[Fournisseur12].[Banque_transit] [Fournisseur_Fond_Forestier_Banque_transit]
,[Fournisseur12].[Banque_folio] [Fournisseur_Fond_Forestier_Banque_folio]
,[Fournisseur12].[No_TPS] [Fournisseur_Fond_Forestier_No_TPS]
,[Fournisseur12].[No_TVQ] [Fournisseur_Fond_Forestier_No_TVQ]
,[Fournisseur12].[PayerA] [Fournisseur_Fond_Forestier_PayerA]
,[Fournisseur12].[PayerAID] [Fournisseur_Fond_Forestier_PayerAID]
,[Fournisseur12].[Statut] [Fournisseur_Fond_Forestier_Statut]
,[Fournisseur12].[Rep_Nom] [Fournisseur_Fond_Forestier_Rep_Nom]
,[Fournisseur12].[Rep_Telephone] [Fournisseur_Fond_Forestier_Rep_Telephone]
,[Fournisseur12].[Rep_Telephone_Poste] [Fournisseur_Fond_Forestier_Rep_Telephone_Poste]
,[Fournisseur12].[Rep_Email] [Fournisseur_Fond_Forestier_Rep_Email]
,[Fournisseur12].[EnAnglais] [Fournisseur_Fond_Forestier_EnAnglais]
,[Fournisseur12].[Actif] [Fournisseur_Fond_Forestier_Actif]
,[Fournisseur12].[MRCProducteurID] [Fournisseur_Fond_Forestier_MRCProducteurID]
,[Fournisseur12].[PaiementManuel] [Fournisseur_Fond_Forestier_PaiementManuel]
,[Fournisseur12].[Journal] [Fournisseur_Fond_Forestier_Journal]
,[Fournisseur12].[RecoitTPS] [Fournisseur_Fond_Forestier_RecoitTPS]
,[Fournisseur12].[RecoitTVQ] [Fournisseur_Fond_Forestier_RecoitTVQ]
,[Fournisseur12].[ModifierTrigger] [Fournisseur_Fond_Forestier_ModifierTrigger]
,[Fournisseur12].[IsProducteur] [Fournisseur_Fond_Forestier_IsProducteur]
,[Fournisseur12].[IsTransporteur] [Fournisseur_Fond_Forestier_IsTransporteur]
,[Fournisseur12].[IsChargeur] [Fournisseur_Fond_Forestier_IsChargeur]
,[Fournisseur12].[IsAutre] [Fournisseur_Fond_Forestier_IsAutre]
,[Fournisseur12].[AfficherCommentairesSurPermit] [Fournisseur_Fond_Forestier_AfficherCommentairesSurPermit]
,[Fournisseur12].[PasEmissionPermis] [Fournisseur_Fond_Forestier_PasEmissionPermis]
,[Fournisseur13].[ID] [Fournisseur_Preleve_Divers_ID]
,[Fournisseur13].[CleTri] [Fournisseur_Preleve_Divers_CleTri]
,[Fournisseur13].[Nom] [Fournisseur_Preleve_Divers_Nom]
,[Fournisseur13].[AuSoinsDe] [Fournisseur_Preleve_Divers_AuSoinsDe]
,[Fournisseur13].[Rue] [Fournisseur_Preleve_Divers_Rue]
,[Fournisseur13].[Ville] [Fournisseur_Preleve_Divers_Ville]
,[Fournisseur13].[PaysID] [Fournisseur_Preleve_Divers_PaysID]
,[Fournisseur13].[Code_postal] [Fournisseur_Preleve_Divers_Code_postal]
,[Fournisseur13].[Telephone] [Fournisseur_Preleve_Divers_Telephone]
,[Fournisseur13].[Telephone_Poste] [Fournisseur_Preleve_Divers_Telephone_Poste]
,[Fournisseur13].[Telecopieur] [Fournisseur_Preleve_Divers_Telecopieur]
,[Fournisseur13].[Telephone2] [Fournisseur_Preleve_Divers_Telephone2]
,[Fournisseur13].[Telephone2_Desc] [Fournisseur_Preleve_Divers_Telephone2_Desc]
,[Fournisseur13].[Telephone2_Poste] [Fournisseur_Preleve_Divers_Telephone2_Poste]
,[Fournisseur13].[Telephone3] [Fournisseur_Preleve_Divers_Telephone3]
,[Fournisseur13].[Telephone3_Desc] [Fournisseur_Preleve_Divers_Telephone3_Desc]
,[Fournisseur13].[Telephone3_Poste] [Fournisseur_Preleve_Divers_Telephone3_Poste]
,[Fournisseur13].[No_membre] [Fournisseur_Preleve_Divers_No_membre]
,[Fournisseur13].[Resident] [Fournisseur_Preleve_Divers_Resident]
,[Fournisseur13].[Email] [Fournisseur_Preleve_Divers_Email]
,[Fournisseur13].[WWW] [Fournisseur_Preleve_Divers_WWW]
,[Fournisseur13].[Commentaires] [Fournisseur_Preleve_Divers_Commentaires]
,[Fournisseur13].[AfficherCommentaires] [Fournisseur_Preleve_Divers_AfficherCommentaires]
,[Fournisseur13].[DepotDirect] [Fournisseur_Preleve_Divers_DepotDirect]
,[Fournisseur13].[InstitutionBanquaireID] [Fournisseur_Preleve_Divers_InstitutionBanquaireID]
,[Fournisseur13].[Banque_transit] [Fournisseur_Preleve_Divers_Banque_transit]
,[Fournisseur13].[Banque_folio] [Fournisseur_Preleve_Divers_Banque_folio]
,[Fournisseur13].[No_TPS] [Fournisseur_Preleve_Divers_No_TPS]
,[Fournisseur13].[No_TVQ] [Fournisseur_Preleve_Divers_No_TVQ]
,[Fournisseur13].[PayerA] [Fournisseur_Preleve_Divers_PayerA]
,[Fournisseur13].[PayerAID] [Fournisseur_Preleve_Divers_PayerAID]
,[Fournisseur13].[Statut] [Fournisseur_Preleve_Divers_Statut]
,[Fournisseur13].[Rep_Nom] [Fournisseur_Preleve_Divers_Rep_Nom]
,[Fournisseur13].[Rep_Telephone] [Fournisseur_Preleve_Divers_Rep_Telephone]
,[Fournisseur13].[Rep_Telephone_Poste] [Fournisseur_Preleve_Divers_Rep_Telephone_Poste]
,[Fournisseur13].[Rep_Email] [Fournisseur_Preleve_Divers_Rep_Email]
,[Fournisseur13].[EnAnglais] [Fournisseur_Preleve_Divers_EnAnglais]
,[Fournisseur13].[Actif] [Fournisseur_Preleve_Divers_Actif]
,[Fournisseur13].[MRCProducteurID] [Fournisseur_Preleve_Divers_MRCProducteurID]
,[Fournisseur13].[PaiementManuel] [Fournisseur_Preleve_Divers_PaiementManuel]
,[Fournisseur13].[Journal] [Fournisseur_Preleve_Divers_Journal]
,[Fournisseur13].[RecoitTPS] [Fournisseur_Preleve_Divers_RecoitTPS]
,[Fournisseur13].[RecoitTVQ] [Fournisseur_Preleve_Divers_RecoitTVQ]
,[Fournisseur13].[ModifierTrigger] [Fournisseur_Preleve_Divers_ModifierTrigger]
,[Fournisseur13].[IsProducteur] [Fournisseur_Preleve_Divers_IsProducteur]
,[Fournisseur13].[IsTransporteur] [Fournisseur_Preleve_Divers_IsTransporteur]
,[Fournisseur13].[IsChargeur] [Fournisseur_Preleve_Divers_IsChargeur]
,[Fournisseur13].[IsAutre] [Fournisseur_Preleve_Divers_IsAutre]
,[Fournisseur13].[AfficherCommentairesSurPermit] [Fournisseur_Preleve_Divers_AfficherCommentairesSurPermit]
,[Fournisseur13].[PasEmissionPermis] [Fournisseur_Preleve_Divers_PasEmissionPermis]
From [dbo].[jag_System] [jag_System]
    Left Outer Join [dbo].[Fournisseur] [Fournisseur1] On [jag_System].[Fournisseur_PlanConjoint] = [Fournisseur1].[ID]
        Left Outer Join [dbo].[Fournisseur] [Fournisseur2] On [jag_System].[Fournisseur_Surcharge] = [Fournisseur2].[ID]
            Left Outer Join [dbo].[Compte] [Compte3] On [jag_System].[Compte_Paiements] = [Compte3].[ID]
                Left Outer Join [dbo].[Compte] [Compte4] On [jag_System].[Compte_ARecevoir] = [Compte4].[ID]
                    Left Outer Join [dbo].[Compte] [Compte5] On [jag_System].[Compte_APayer] = [Compte5].[ID]
                        Left Outer Join [dbo].[Compte] [Compte6] On [jag_System].[Compte_DuAuxProducteurs] = [Compte6].[ID]
                            Left Outer Join [dbo].[Compte] [Compte7] On [jag_System].[Compte_TPSpercues] = [Compte7].[ID]
                                Left Outer Join [dbo].[Compte] [Compte8] On [jag_System].[Compte_TPSpayees] = [Compte8].[ID]
                                    Left Outer Join [dbo].[Compte] [Compte9] On [jag_System].[Compte_TVQpercues] = [Compte9].[ID]
                                        Left Outer Join [dbo].[Compte] [Compte10] On [jag_System].[Compte_TVQpayees] = [Compte10].[ID]
        									Left Outer Join [dbo].[Fournisseur] [Fournisseur11] On [jag_System].[Fournisseur_Fond_Roulement] = [Fournisseur11].[ID]
       											Left Outer Join [dbo].[Fournisseur] [Fournisseur12] On [jag_System].[Fournisseur_Fond_Forestier] = [Fournisseur12].[ID]
        											Left Outer Join [dbo].[Fournisseur] [Fournisseur13] On [jag_System].[Fournisseur_Preleve_Divers] = [Fournisseur13].[ID]
Where

    ((@Fournisseur_PlanConjoint Is Null) Or ([jag_System].[Fournisseur_PlanConjoint] = @Fournisseur_PlanConjoint))
And ((@Fournisseur_Surcharge Is Null) Or ([jag_System].[Fournisseur_Surcharge] = @Fournisseur_Surcharge))
And ((@Compte_Paiements Is Null) Or ([jag_System].[Compte_Paiements] = @Compte_Paiements))
And ((@Compte_ARecevoir Is Null) Or ([jag_System].[Compte_ARecevoir] = @Compte_ARecevoir))
And ((@Compte_APayer Is Null) Or ([jag_System].[Compte_APayer] = @Compte_APayer))
And ((@Compte_DuAuxProducteurs Is Null) Or ([jag_System].[Compte_DuAuxProducteurs] = @Compte_DuAuxProducteurs))
And ((@Compte_TPSpercues Is Null) Or ([jag_System].[Compte_TPSpercues] = @Compte_TPSpercues))
And ((@Compte_TPSpayees Is Null) Or ([jag_System].[Compte_TPSpayees] = @Compte_TPSpayees))
And ((@Compte_TVQpercues Is Null) Or ([jag_System].[Compte_TVQpercues] = @Compte_TVQpercues))
And ((@Compte_TVQpayees Is Null) Or ([jag_System].[Compte_TVQpayees] = @Compte_TVQpayees))
And ((@Fournisseur_Fond_Roulement Is Null) Or ([jag_System].[Fournisseur_Fond_Roulement] = @Fournisseur_Fond_Roulement))
And ((@Fournisseur_Fond_Forestier Is Null) Or ([jag_System].[Fournisseur_Fond_Forestier] = @Fournisseur_Fond_Forestier))
And ((@Fournisseur_Preleve_Divers Is Null) Or ([jag_System].[Fournisseur_Preleve_Divers] = @Fournisseur_Preleve_Divers))

)



