CREATE FUNCTION [dbo].[fnLivraison_Full]
(@ID INT=Null, @ContratID VARCHAR (10)=Null, @UniteMesureID VARCHAR (6)=Null, @EssenceID VARCHAR (6)=Null, @DroitCoupeID VARCHAR (15)=Null, @EntentePaiementID VARCHAR (15)=Null, @TransporteurID VARCHAR (15)=Null, @Annee INT=Null, @Periode INT=Null, @Producteur1_FactureID INT=Null, @Producteur2_FactureID INT=Null, @Transporteur_FactureID INT=Null, @Usine_FactureID INT=Null, @LotID INT=Null, @ZoneID VARCHAR (2)=Null, @MunicipaliteID VARCHAR (6)=Null, @ChargeurID VARCHAR (15)=Null, @Chargeur_FactureID INT=Null)
RETURNS TABLE 
AS
RETURN 
    (
Select
 [Livraison].[ID]
,[Livraison].[DateLivraison]
,[Livraison].[DatePaye]
,[Livraison].[ContratID]
,[Livraison].[UniteMesureID]
,[Livraison].[EssenceID]
,[Livraison].[Sciage]
,[Livraison].[NumeroFactureUsine]
,[Livraison].[DroitCoupeID]
,[Livraison].[EntentePaiementID]
,[Livraison].[TransporteurID]
,[Livraison].[VR]
,[Livraison].[MasseLimite]
,[Livraison].[VolumeBrut]
,[Livraison].[VolumeTare]
,[Livraison].[VolumeTransporte]
,[Livraison].[VolumeSurcharge]
,[Livraison].[VolumeAPayer]
,[Livraison].[Annee]
,[Livraison].[Periode]
,[Livraison].[DateCalcul]
,[Livraison].[Taux_Transporteur]
,[Livraison].[Montant_Transporteur]
,[Livraison].[Montant_Usine]
,[Livraison].[Montant_Producteur1]
,[Livraison].[Montant_Producteur2]
,[Livraison].[Montant_Preleve_Plan_Conjoint]
,[Livraison].[Montant_Preleve_Fond_Roulement]
,[Livraison].[Montant_Preleve_Fond_Forestier]
,[Livraison].[Montant_Preleve_Divers]
,[Livraison].[Montant_Surcharge]
,[Livraison].[Montant_MiseEnCommun]
,[Livraison].[Facture]
,[Livraison].[Producteur1_FactureID]
,[Livraison].[Producteur2_FactureID]
,[Livraison].[Transporteur_FactureID]
,[Livraison].[Usine_FactureID]
,[Livraison].[ErreurCalcul]
,[Livraison].[ErreurDescription]
,[Livraison].[LotID]
,[Livraison].[Taux_Transporteur_Override]
,[Livraison].[PaieTransporteur]
,[Livraison].[VolumeSurcharge_Override]
,[Livraison].[SurchargeManuel]
,[Livraison].[Code]
,[Livraison].[NombrePermis]
,[Livraison].[ZoneID]
,[Livraison].[MunicipaliteID]
,[Livraison].[ChargeurID]
,[Livraison].[Montant_Chargeur]
,[Livraison].[Frais_ChargeurAuProducteur]
,[Livraison].[Frais_ChargeurAuTransporteur]
,[Livraison].[Frais_AutresAuProducteur]
,[Livraison].[Frais_AutresAuProducteurDescription]
,[Livraison].[Frais_AutresAuTransporteur]
,[Livraison].[Frais_AutresAuTransporteurDescription]
,[Livraison].[Frais_CompensationDeDeplacement]
,[Livraison].[Chargeur_FactureID]
,[Livraison].[Commentaires_Producteur]
,[Livraison].[Commentaires_Transporteur]
,[Livraison].[Commentaires_Chargeur]
,[Livraison].[TauxChargeurAuProducteur]
,[Livraison].[TauxChargeurAuTransporteur]
,[Livraison].[Frais_AutresRevenusTransporteur]
,[Livraison].[Frais_AutresRevenusTransporteurDescription]
,[Livraison].[Frais_AutresRevenusProducteur]
,[Livraison].[Frais_AutresRevenusProducteurDescription]
,[Livraison].[Montant_SurchargeProducteur]
,[Livraison].[KgVert_Brut]
,[Livraison].[KgVert_Tare]
,[Livraison].[KgVert_Net]
,[Livraison].[KgVert_Rejets]
,[Livraison].[KgVert_Paye]
,[Livraison].[Pourcent_Sec_Producteur]
,[Livraison].[Pourcent_Sec_Producteur_Override]
,[Livraison].[TMA_Producteur]
,[Livraison].[Pourcent_Sec_Transport]
,[Livraison].[Pourcent_Sec_Transport_Override]
,[Livraison].[TMA_Transport]
,[Livraison].[IsTMA]
,[Livraison].[SuspendrePaiement]
,[Livraison].[BonCommande]
,[Permit1].[ID] [ID_ID]
,[Permit1].[DatePermit] [ID_DatePermit]
,[Permit1].[DateDebut] [ID_DateDebut]
,[Permit1].[DateFin] [ID_DateFin]
,[Permit1].[Annee] [ID_Annee]
,[Permit1].[Periode] [ID_Periode]
,[Permit1].[ContratID] [ID_ContratID]
,[Permit1].[EssenceID] [ID_EssenceID]
,[Permit1].[PermitSciage] [ID_PermitSciage]
,[Permit1].[TransporteurID] [ID_TransporteurID]
,[Permit1].[VR] [ID_VR]
,[Permit1].[ProducteurDroitCoupeID] [ID_ProducteurDroitCoupeID]
,[Permit1].[ProducteurEntentePaiementID] [ID_ProducteurEntentePaiementID]
,[Permit1].[PermitLivre] [ID_PermitLivre]
,[Permit1].[PermitImprime] [ID_PermitImprime]
,[Permit1].[PermitAnnule] [ID_PermitAnnule]
,[Permit1].[LotID] [ID_LotID]
,[Permit1].[EssenceSciage] [ID_EssenceSciage]
,[Permit1].[Code] [ID_Code]
,[Permit1].[Remarques] [ID_Remarques]
,[Permit1].[ChargeurID] [ID_ChargeurID]
,[Permit1].[ZoneID] [ID_ZoneID]
,[Permit1].[MunicipaliteID] [ID_MunicipaliteID]
,[Contrat2].[ID] [ContratID_ID]
,[Contrat2].[Description] [ContratID_Description]
,[Contrat2].[UsineID] [ContratID_UsineID]
,[Contrat2].[Annee] [ContratID_Annee]
,[Contrat2].[Date_debut] [ContratID_Date_debut]
,[Contrat2].[Date_fin] [ContratID_Date_fin]
,[Contrat2].[Actif] [ContratID_Actif]
,[Contrat2].[PaieTransporteur] [ContratID_PaieTransporteur]
,[Contrat2].[Taux_Surcharge] [ContratID_Taux_Surcharge]
,[Contrat2].[SurchargeManuel] [ContratID_SurchargeManuel]
,[Contrat2].[TxTransSameProd] [ContratID_TxTransSameProd]
,[UniteMesure3].[ID] [UniteMesureID_ID]
,[UniteMesure3].[Description] [UniteMesureID_Description]
,[UniteMesure3].[Nb_decimale] [UniteMesureID_Nb_decimale]
,[UniteMesure3].[Actif] [UniteMesureID_Actif]
,[UniteMesure3].[UseMontant] [UniteMesureID_UseMontant]
,[UniteMesure3].[Montant_Preleve_plan_conjoint] [UniteMesureID_Montant_Preleve_plan_conjoint]
,[UniteMesure3].[Montant_Preleve_fond_roulement] [UniteMesureID_Montant_Preleve_fond_roulement]
,[UniteMesure3].[Montant_Preleve_fond_forestier] [UniteMesureID_Montant_Preleve_fond_forestier]
,[UniteMesure3].[Montant_Preleve_divers] [UniteMesureID_Montant_Preleve_divers]
,[UniteMesure3].[Pourc_Preleve_plan_conjoint] [UniteMesureID_Pourc_Preleve_plan_conjoint]
,[UniteMesure3].[Pourc_Preleve_fond_roulement] [UniteMesureID_Pourc_Preleve_fond_roulement]
,[UniteMesure3].[Pourc_Preleve_fond_forestier] [UniteMesureID_Pourc_Preleve_fond_forestier]
,[UniteMesure3].[Pourc_Preleve_divers] [UniteMesureID_Pourc_Preleve_divers]
,[Essence4].[ID] [EssenceID_ID]
,[Essence4].[Description] [EssenceID_Description]
,[Essence4].[RegroupementID] [EssenceID_RegroupementID]
,[Essence4].[ContingentID] [EssenceID_ContingentID]
,[Essence4].[RepartitionID] [EssenceID_RepartitionID]
,[Essence4].[Actif] [EssenceID_Actif]
,[Fournisseur5].[ID] [DroitCoupeID_ID]
,[Fournisseur5].[CleTri] [DroitCoupeID_CleTri]
,[Fournisseur5].[Nom] [DroitCoupeID_Nom]
,[Fournisseur5].[AuSoinsDe] [DroitCoupeID_AuSoinsDe]
,[Fournisseur5].[Rue] [DroitCoupeID_Rue]
,[Fournisseur5].[Ville] [DroitCoupeID_Ville]
,[Fournisseur5].[PaysID] [DroitCoupeID_PaysID]
,[Fournisseur5].[Code_postal] [DroitCoupeID_Code_postal]
,[Fournisseur5].[Telephone] [DroitCoupeID_Telephone]
,[Fournisseur5].[Telephone_Poste] [DroitCoupeID_Telephone_Poste]
,[Fournisseur5].[Telecopieur] [DroitCoupeID_Telecopieur]
,[Fournisseur5].[Telephone2] [DroitCoupeID_Telephone2]
,[Fournisseur5].[Telephone2_Desc] [DroitCoupeID_Telephone2_Desc]
,[Fournisseur5].[Telephone2_Poste] [DroitCoupeID_Telephone2_Poste]
,[Fournisseur5].[Telephone3] [DroitCoupeID_Telephone3]
,[Fournisseur5].[Telephone3_Desc] [DroitCoupeID_Telephone3_Desc]
,[Fournisseur5].[Telephone3_Poste] [DroitCoupeID_Telephone3_Poste]
,[Fournisseur5].[No_membre] [DroitCoupeID_No_membre]
,[Fournisseur5].[Resident] [DroitCoupeID_Resident]
,[Fournisseur5].[Email] [DroitCoupeID_Email]
,[Fournisseur5].[WWW] [DroitCoupeID_WWW]
,[Fournisseur5].[Commentaires] [DroitCoupeID_Commentaires]
,[Fournisseur5].[AfficherCommentaires] [DroitCoupeID_AfficherCommentaires]
,[Fournisseur5].[DepotDirect] [DroitCoupeID_DepotDirect]
,[Fournisseur5].[InstitutionBanquaireID] [DroitCoupeID_InstitutionBanquaireID]
,[Fournisseur5].[Banque_transit] [DroitCoupeID_Banque_transit]
,[Fournisseur5].[Banque_folio] [DroitCoupeID_Banque_folio]
,[Fournisseur5].[No_TPS] [DroitCoupeID_No_TPS]
,[Fournisseur5].[No_TVQ] [DroitCoupeID_No_TVQ]
,[Fournisseur5].[PayerA] [DroitCoupeID_PayerA]
,[Fournisseur5].[PayerAID] [DroitCoupeID_PayerAID]
,[Fournisseur5].[Statut] [DroitCoupeID_Statut]
,[Fournisseur5].[Rep_Nom] [DroitCoupeID_Rep_Nom]
,[Fournisseur5].[Rep_Telephone] [DroitCoupeID_Rep_Telephone]
,[Fournisseur5].[Rep_Telephone_Poste] [DroitCoupeID_Rep_Telephone_Poste]
,[Fournisseur5].[Rep_Email] [DroitCoupeID_Rep_Email]
,[Fournisseur5].[EnAnglais] [DroitCoupeID_EnAnglais]
,[Fournisseur5].[Actif] [DroitCoupeID_Actif]
,[Fournisseur5].[MRCProducteurID] [DroitCoupeID_MRCProducteurID]
,[Fournisseur5].[PaiementManuel] [DroitCoupeID_PaiementManuel]
,[Fournisseur5].[Journal] [DroitCoupeID_Journal]
,[Fournisseur5].[RecoitTPS] [DroitCoupeID_RecoitTPS]
,[Fournisseur5].[RecoitTVQ] [DroitCoupeID_RecoitTVQ]
,[Fournisseur5].[ModifierTrigger] [DroitCoupeID_ModifierTrigger]
,[Fournisseur5].[IsProducteur] [DroitCoupeID_IsProducteur]
,[Fournisseur5].[IsTransporteur] [DroitCoupeID_IsTransporteur]
,[Fournisseur5].[IsChargeur] [DroitCoupeID_IsChargeur]
,[Fournisseur5].[IsAutre] [DroitCoupeID_IsAutre]
,[Fournisseur5].[AfficherCommentairesSurPermit] [DroitCoupeID_AfficherCommentairesSurPermit]
,[Fournisseur5].[PasEmissionPermis] [DroitCoupeID_PasEmissionPermis]
,[Fournisseur5].[Generique] [DroitCoupeID_Generique]
,[Fournisseur5].[Membre_OGC] [DroitCoupeID_Membre_OGC]
,[Fournisseur5].[InscritTPS] [DroitCoupeID_InscritTPS]
,[Fournisseur5].[InscritTVQ] [DroitCoupeID_InscritTVQ]
,[Fournisseur5].[IsOGC] [DroitCoupeID_IsOGC]
,[Fournisseur6].[ID] [EntentePaiementID_ID]
,[Fournisseur6].[CleTri] [EntentePaiementID_CleTri]
,[Fournisseur6].[Nom] [EntentePaiementID_Nom]
,[Fournisseur6].[AuSoinsDe] [EntentePaiementID_AuSoinsDe]
,[Fournisseur6].[Rue] [EntentePaiementID_Rue]
,[Fournisseur6].[Ville] [EntentePaiementID_Ville]
,[Fournisseur6].[PaysID] [EntentePaiementID_PaysID]
,[Fournisseur6].[Code_postal] [EntentePaiementID_Code_postal]
,[Fournisseur6].[Telephone] [EntentePaiementID_Telephone]
,[Fournisseur6].[Telephone_Poste] [EntentePaiementID_Telephone_Poste]
,[Fournisseur6].[Telecopieur] [EntentePaiementID_Telecopieur]
,[Fournisseur6].[Telephone2] [EntentePaiementID_Telephone2]
,[Fournisseur6].[Telephone2_Desc] [EntentePaiementID_Telephone2_Desc]
,[Fournisseur6].[Telephone2_Poste] [EntentePaiementID_Telephone2_Poste]
,[Fournisseur6].[Telephone3] [EntentePaiementID_Telephone3]
,[Fournisseur6].[Telephone3_Desc] [EntentePaiementID_Telephone3_Desc]
,[Fournisseur6].[Telephone3_Poste] [EntentePaiementID_Telephone3_Poste]
,[Fournisseur6].[No_membre] [EntentePaiementID_No_membre]
,[Fournisseur6].[Resident] [EntentePaiementID_Resident]
,[Fournisseur6].[Email] [EntentePaiementID_Email]
,[Fournisseur6].[WWW] [EntentePaiementID_WWW]
,[Fournisseur6].[Commentaires] [EntentePaiementID_Commentaires]
,[Fournisseur6].[AfficherCommentaires] [EntentePaiementID_AfficherCommentaires]
,[Fournisseur6].[DepotDirect] [EntentePaiementID_DepotDirect]
,[Fournisseur6].[InstitutionBanquaireID] [EntentePaiementID_InstitutionBanquaireID]
,[Fournisseur6].[Banque_transit] [EntentePaiementID_Banque_transit]
,[Fournisseur6].[Banque_folio] [EntentePaiementID_Banque_folio]
,[Fournisseur6].[No_TPS] [EntentePaiementID_No_TPS]
,[Fournisseur6].[No_TVQ] [EntentePaiementID_No_TVQ]
,[Fournisseur6].[PayerA] [EntentePaiementID_PayerA]
,[Fournisseur6].[PayerAID] [EntentePaiementID_PayerAID]
,[Fournisseur6].[Statut] [EntentePaiementID_Statut]
,[Fournisseur6].[Rep_Nom] [EntentePaiementID_Rep_Nom]
,[Fournisseur6].[Rep_Telephone] [EntentePaiementID_Rep_Telephone]
,[Fournisseur6].[Rep_Telephone_Poste] [EntentePaiementID_Rep_Telephone_Poste]
,[Fournisseur6].[Rep_Email] [EntentePaiementID_Rep_Email]
,[Fournisseur6].[EnAnglais] [EntentePaiementID_EnAnglais]
,[Fournisseur6].[Actif] [EntentePaiementID_Actif]
,[Fournisseur6].[MRCProducteurID] [EntentePaiementID_MRCProducteurID]
,[Fournisseur6].[PaiementManuel] [EntentePaiementID_PaiementManuel]
,[Fournisseur6].[Journal] [EntentePaiementID_Journal]
,[Fournisseur6].[RecoitTPS] [EntentePaiementID_RecoitTPS]
,[Fournisseur6].[RecoitTVQ] [EntentePaiementID_RecoitTVQ]
,[Fournisseur6].[ModifierTrigger] [EntentePaiementID_ModifierTrigger]
,[Fournisseur6].[IsProducteur] [EntentePaiementID_IsProducteur]
,[Fournisseur6].[IsTransporteur] [EntentePaiementID_IsTransporteur]
,[Fournisseur6].[IsChargeur] [EntentePaiementID_IsChargeur]
,[Fournisseur6].[IsAutre] [EntentePaiementID_IsAutre]
,[Fournisseur6].[AfficherCommentairesSurPermit] [EntentePaiementID_AfficherCommentairesSurPermit]
,[Fournisseur6].[PasEmissionPermis] [EntentePaiementID_PasEmissionPermis]
,[Fournisseur6].[Generique] [EntentePaiementID_Generique]
,[Fournisseur6].[Membre_OGC] [EntentePaiementID_Membre_OGC]
,[Fournisseur6].[InscritTPS] [EntentePaiementID_InscritTPS]
,[Fournisseur6].[InscritTVQ] [EntentePaiementID_InscritTVQ]
,[Fournisseur6].[IsOGC] [EntentePaiementID_IsOGC]
,[Fournisseur7].[ID] [TransporteurID_ID]
,[Fournisseur7].[CleTri] [TransporteurID_CleTri]
,[Fournisseur7].[Nom] [TransporteurID_Nom]
,[Fournisseur7].[AuSoinsDe] [TransporteurID_AuSoinsDe]
,[Fournisseur7].[Rue] [TransporteurID_Rue]
,[Fournisseur7].[Ville] [TransporteurID_Ville]
,[Fournisseur7].[PaysID] [TransporteurID_PaysID]
,[Fournisseur7].[Code_postal] [TransporteurID_Code_postal]
,[Fournisseur7].[Telephone] [TransporteurID_Telephone]
,[Fournisseur7].[Telephone_Poste] [TransporteurID_Telephone_Poste]
,[Fournisseur7].[Telecopieur] [TransporteurID_Telecopieur]
,[Fournisseur7].[Telephone2] [TransporteurID_Telephone2]
,[Fournisseur7].[Telephone2_Desc] [TransporteurID_Telephone2_Desc]
,[Fournisseur7].[Telephone2_Poste] [TransporteurID_Telephone2_Poste]
,[Fournisseur7].[Telephone3] [TransporteurID_Telephone3]
,[Fournisseur7].[Telephone3_Desc] [TransporteurID_Telephone3_Desc]
,[Fournisseur7].[Telephone3_Poste] [TransporteurID_Telephone3_Poste]
,[Fournisseur7].[No_membre] [TransporteurID_No_membre]
,[Fournisseur7].[Resident] [TransporteurID_Resident]
,[Fournisseur7].[Email] [TransporteurID_Email]
,[Fournisseur7].[WWW] [TransporteurID_WWW]
,[Fournisseur7].[Commentaires] [TransporteurID_Commentaires]
,[Fournisseur7].[AfficherCommentaires] [TransporteurID_AfficherCommentaires]
,[Fournisseur7].[DepotDirect] [TransporteurID_DepotDirect]
,[Fournisseur7].[InstitutionBanquaireID] [TransporteurID_InstitutionBanquaireID]
,[Fournisseur7].[Banque_transit] [TransporteurID_Banque_transit]
,[Fournisseur7].[Banque_folio] [TransporteurID_Banque_folio]
,[Fournisseur7].[No_TPS] [TransporteurID_No_TPS]
,[Fournisseur7].[No_TVQ] [TransporteurID_No_TVQ]
,[Fournisseur7].[PayerA] [TransporteurID_PayerA]
,[Fournisseur7].[PayerAID] [TransporteurID_PayerAID]
,[Fournisseur7].[Statut] [TransporteurID_Statut]
,[Fournisseur7].[Rep_Nom] [TransporteurID_Rep_Nom]
,[Fournisseur7].[Rep_Telephone] [TransporteurID_Rep_Telephone]
,[Fournisseur7].[Rep_Telephone_Poste] [TransporteurID_Rep_Telephone_Poste]
,[Fournisseur7].[Rep_Email] [TransporteurID_Rep_Email]
,[Fournisseur7].[EnAnglais] [TransporteurID_EnAnglais]
,[Fournisseur7].[Actif] [TransporteurID_Actif]
,[Fournisseur7].[MRCProducteurID] [TransporteurID_MRCProducteurID]
,[Fournisseur7].[PaiementManuel] [TransporteurID_PaiementManuel]
,[Fournisseur7].[Journal] [TransporteurID_Journal]
,[Fournisseur7].[RecoitTPS] [TransporteurID_RecoitTPS]
,[Fournisseur7].[RecoitTVQ] [TransporteurID_RecoitTVQ]
,[Fournisseur7].[ModifierTrigger] [TransporteurID_ModifierTrigger]
,[Fournisseur7].[IsProducteur] [TransporteurID_IsProducteur]
,[Fournisseur7].[IsTransporteur] [TransporteurID_IsTransporteur]
,[Fournisseur7].[IsChargeur] [TransporteurID_IsChargeur]
,[Fournisseur7].[IsAutre] [TransporteurID_IsAutre]
,[Fournisseur7].[AfficherCommentairesSurPermit] [TransporteurID_AfficherCommentairesSurPermit]
,[Fournisseur7].[PasEmissionPermis] [TransporteurID_PasEmissionPermis]
,[Fournisseur7].[Generique] [TransporteurID_Generique]
,[Fournisseur7].[Membre_OGC] [TransporteurID_Membre_OGC]
,[Fournisseur7].[InscritTPS] [TransporteurID_InscritTPS]
,[Fournisseur7].[InscritTVQ] [TransporteurID_InscritTVQ]
,[Fournisseur7].[IsOGC] [TransporteurID_IsOGC]
,[Periode8].[Annee] [Annee_Annee]
,[Periode8].[SemaineNo] [Annee_SemaineNo]
,[Periode8].[DateDebut] [Annee_DateDebut]
,[Periode8].[DateFin] [Annee_DateFin]
,[Periode8].[PeriodeContingentement] [Annee_PeriodeContingentement]
,[Periode9].[Annee] [Periode_Annee]
,[Periode9].[SemaineNo] [Periode_SemaineNo]
,[Periode9].[DateDebut] [Periode_DateDebut]
,[Periode9].[DateFin] [Periode_DateFin]
,[Periode9].[PeriodeContingentement] [Periode_PeriodeContingentement]
,[FactureFournisseur10].[ID] [Producteur1_FactureID_ID]
,[FactureFournisseur10].[NoFacture] [Producteur1_FactureID_NoFacture]
,[FactureFournisseur10].[DateFacture] [Producteur1_FactureID_DateFacture]
,[FactureFournisseur10].[Annee] [Producteur1_FactureID_Annee]
,[FactureFournisseur10].[TypeFactureFournisseur] [Producteur1_FactureID_TypeFactureFournisseur]
,[FactureFournisseur10].[TypeFacture] [Producteur1_FactureID_TypeFacture]
,[FactureFournisseur10].[TypeInvoiceAcomba] [Producteur1_FactureID_TypeInvoiceAcomba]
,[FactureFournisseur10].[FournisseurID] [Producteur1_FactureID_FournisseurID]
,[FactureFournisseur10].[PayerAID] [Producteur1_FactureID_PayerAID]
,[FactureFournisseur10].[Montant_Total] [Producteur1_FactureID_Montant_Total]
,[FactureFournisseur10].[Montant_TPS] [Producteur1_FactureID_Montant_TPS]
,[FactureFournisseur10].[Montant_TVQ] [Producteur1_FactureID_Montant_TVQ]
,[FactureFournisseur10].[Description] [Producteur1_FactureID_Description]
,[FactureFournisseur10].[Status] [Producteur1_FactureID_Status]
,[FactureFournisseur10].[StatusDescription] [Producteur1_FactureID_StatusDescription]
,[FactureFournisseur10].[NumeroCheque] [Producteur1_FactureID_NumeroCheque]
,[FactureFournisseur10].[NumeroPaiement] [Producteur1_FactureID_NumeroPaiement]
,[FactureFournisseur10].[NumeroPaiementUnique] [Producteur1_FactureID_NumeroPaiementUnique]
,[FactureFournisseur10].[DateFactureAcomba] [Producteur1_FactureID_DateFactureAcomba]
,[FactureFournisseur10].[DatePaiementAcomba] [Producteur1_FactureID_DatePaiementAcomba]
,[FactureFournisseur11].[ID] [Producteur2_FactureID_ID]
,[FactureFournisseur11].[NoFacture] [Producteur2_FactureID_NoFacture]
,[FactureFournisseur11].[DateFacture] [Producteur2_FactureID_DateFacture]
,[FactureFournisseur11].[Annee] [Producteur2_FactureID_Annee]
,[FactureFournisseur11].[TypeFactureFournisseur] [Producteur2_FactureID_TypeFactureFournisseur]
,[FactureFournisseur11].[TypeFacture] [Producteur2_FactureID_TypeFacture]
,[FactureFournisseur11].[TypeInvoiceAcomba] [Producteur2_FactureID_TypeInvoiceAcomba]
,[FactureFournisseur11].[FournisseurID] [Producteur2_FactureID_FournisseurID]
,[FactureFournisseur11].[PayerAID] [Producteur2_FactureID_PayerAID]
,[FactureFournisseur11].[Montant_Total] [Producteur2_FactureID_Montant_Total]
,[FactureFournisseur11].[Montant_TPS] [Producteur2_FactureID_Montant_TPS]
,[FactureFournisseur11].[Montant_TVQ] [Producteur2_FactureID_Montant_TVQ]
,[FactureFournisseur11].[Description] [Producteur2_FactureID_Description]
,[FactureFournisseur11].[Status] [Producteur2_FactureID_Status]
,[FactureFournisseur11].[StatusDescription] [Producteur2_FactureID_StatusDescription]
,[FactureFournisseur11].[NumeroCheque] [Producteur2_FactureID_NumeroCheque]
,[FactureFournisseur11].[NumeroPaiement] [Producteur2_FactureID_NumeroPaiement]
,[FactureFournisseur11].[NumeroPaiementUnique] [Producteur2_FactureID_NumeroPaiementUnique]
,[FactureFournisseur11].[DateFactureAcomba] [Producteur2_FactureID_DateFactureAcomba]
,[FactureFournisseur11].[DatePaiementAcomba] [Producteur2_FactureID_DatePaiementAcomba]
,[FactureFournisseur12].[ID] [Transporteur_FactureID_ID]
,[FactureFournisseur12].[NoFacture] [Transporteur_FactureID_NoFacture]
,[FactureFournisseur12].[DateFacture] [Transporteur_FactureID_DateFacture]
,[FactureFournisseur12].[Annee] [Transporteur_FactureID_Annee]
,[FactureFournisseur12].[TypeFactureFournisseur] [Transporteur_FactureID_TypeFactureFournisseur]
,[FactureFournisseur12].[TypeFacture] [Transporteur_FactureID_TypeFacture]
,[FactureFournisseur12].[TypeInvoiceAcomba] [Transporteur_FactureID_TypeInvoiceAcomba]
,[FactureFournisseur12].[FournisseurID] [Transporteur_FactureID_FournisseurID]
,[FactureFournisseur12].[PayerAID] [Transporteur_FactureID_PayerAID]
,[FactureFournisseur12].[Montant_Total] [Transporteur_FactureID_Montant_Total]
,[FactureFournisseur12].[Montant_TPS] [Transporteur_FactureID_Montant_TPS]
,[FactureFournisseur12].[Montant_TVQ] [Transporteur_FactureID_Montant_TVQ]
,[FactureFournisseur12].[Description] [Transporteur_FactureID_Description]
,[FactureFournisseur12].[Status] [Transporteur_FactureID_Status]
,[FactureFournisseur12].[StatusDescription] [Transporteur_FactureID_StatusDescription]
,[FactureFournisseur12].[NumeroCheque] [Transporteur_FactureID_NumeroCheque]
,[FactureFournisseur12].[NumeroPaiement] [Transporteur_FactureID_NumeroPaiement]
,[FactureFournisseur12].[NumeroPaiementUnique] [Transporteur_FactureID_NumeroPaiementUnique]
,[FactureFournisseur12].[DateFactureAcomba] [Transporteur_FactureID_DateFactureAcomba]
,[FactureFournisseur12].[DatePaiementAcomba] [Transporteur_FactureID_DatePaiementAcomba]
,[FactureClient13].[ID] [Usine_FactureID_ID]
,[FactureClient13].[NoFacture] [Usine_FactureID_NoFacture]
,[FactureClient13].[DateFacture] [Usine_FactureID_DateFacture]
,[FactureClient13].[Annee] [Usine_FactureID_Annee]
,[FactureClient13].[TypeFacture] [Usine_FactureID_TypeFacture]
,[FactureClient13].[TypeInvoiceClientAcomba] [Usine_FactureID_TypeInvoiceClientAcomba]
,[FactureClient13].[ClientID] [Usine_FactureID_ClientID]
,[FactureClient13].[PayerAID] [Usine_FactureID_PayerAID]
,[FactureClient13].[Montant_Total] [Usine_FactureID_Montant_Total]
,[FactureClient13].[Montant_TPS] [Usine_FactureID_Montant_TPS]
,[FactureClient13].[Montant_TVQ] [Usine_FactureID_Montant_TVQ]
,[FactureClient13].[Description] [Usine_FactureID_Description]
,[FactureClient13].[Status] [Usine_FactureID_Status]
,[FactureClient13].[StatusDescription] [Usine_FactureID_StatusDescription]
,[FactureClient13].[DateFactureAcomba] [Usine_FactureID_DateFactureAcomba]
,[Lot14].[CantonID] [LotID_CantonID]
,[Lot14].[Rang] [LotID_Rang]
,[Lot14].[Lot] [LotID_Lot]
,[Lot14].[MunicipaliteID] [LotID_MunicipaliteID]
,[Lot14].[Superficie_total] [LotID_Superficie_total]
,[Lot14].[Superficie_boisee] [LotID_Superficie_boisee]
,[Lot14].[ProprietaireID] [LotID_ProprietaireID]
,[Lot14].[ContingentID] [LotID_ContingentID]
,[Lot14].[Contingent_Date] [LotID_Contingent_Date]
,[Lot14].[Droit_coupeID] [LotID_Droit_coupeID]
,[Lot14].[Droit_coupe_Date] [LotID_Droit_coupe_Date]
,[Lot14].[Entente_paiementID] [LotID_Entente_paiementID]
,[Lot14].[Entente_paiement_Date] [LotID_Entente_paiement_Date]
,[Lot14].[Actif] [LotID_Actif]
,[Lot14].[ID] [LotID_ID]
,[Lot14].[Sequence] [LotID_Sequence]
,[Lot14].[Partie] [LotID_Partie]
,[Lot14].[Matricule] [LotID_Matricule]
,[Lot14].[ZoneID] [LotID_ZoneID]
,[Lot14].[Secteur] [LotID_Secteur]
,[Lot14].[Cadastre] [LotID_Cadastre]
,[Lot14].[Reforme] [LotID_Reforme]
,[Lot14].[LotsComplementaires] [LotID_LotsComplementaires]
,[Lot14].[Certifie] [LotID_Certifie]
,[Lot14].[NumeroCertification] [LotID_NumeroCertification]
,[Lot14].[OGC] [LotID_OGC]
,[Municipalite_Zone15].[ID] [ZoneID_ID]
,[Municipalite_Zone15].[MunicipaliteID] [ZoneID_MunicipaliteID]
,[Municipalite_Zone15].[Description] [ZoneID_Description]
,[Municipalite_Zone15].[Actif] [ZoneID_Actif]
,[Municipalite_Zone16].[ID] [MunicipaliteID_ID]
,[Municipalite_Zone16].[MunicipaliteID] [MunicipaliteID_MunicipaliteID]
,[Municipalite_Zone16].[Description] [MunicipaliteID_Description]
,[Municipalite_Zone16].[Actif] [MunicipaliteID_Actif]
,[Fournisseur17].[ID] [ChargeurID_ID]
,[Fournisseur17].[CleTri] [ChargeurID_CleTri]
,[Fournisseur17].[Nom] [ChargeurID_Nom]
,[Fournisseur17].[AuSoinsDe] [ChargeurID_AuSoinsDe]
,[Fournisseur17].[Rue] [ChargeurID_Rue]
,[Fournisseur17].[Ville] [ChargeurID_Ville]
,[Fournisseur17].[PaysID] [ChargeurID_PaysID]
,[Fournisseur17].[Code_postal] [ChargeurID_Code_postal]
,[Fournisseur17].[Telephone] [ChargeurID_Telephone]
,[Fournisseur17].[Telephone_Poste] [ChargeurID_Telephone_Poste]
,[Fournisseur17].[Telecopieur] [ChargeurID_Telecopieur]
,[Fournisseur17].[Telephone2] [ChargeurID_Telephone2]
,[Fournisseur17].[Telephone2_Desc] [ChargeurID_Telephone2_Desc]
,[Fournisseur17].[Telephone2_Poste] [ChargeurID_Telephone2_Poste]
,[Fournisseur17].[Telephone3] [ChargeurID_Telephone3]
,[Fournisseur17].[Telephone3_Desc] [ChargeurID_Telephone3_Desc]
,[Fournisseur17].[Telephone3_Poste] [ChargeurID_Telephone3_Poste]
,[Fournisseur17].[No_membre] [ChargeurID_No_membre]
,[Fournisseur17].[Resident] [ChargeurID_Resident]
,[Fournisseur17].[Email] [ChargeurID_Email]
,[Fournisseur17].[WWW] [ChargeurID_WWW]
,[Fournisseur17].[Commentaires] [ChargeurID_Commentaires]
,[Fournisseur17].[AfficherCommentaires] [ChargeurID_AfficherCommentaires]
,[Fournisseur17].[DepotDirect] [ChargeurID_DepotDirect]
,[Fournisseur17].[InstitutionBanquaireID] [ChargeurID_InstitutionBanquaireID]
,[Fournisseur17].[Banque_transit] [ChargeurID_Banque_transit]
,[Fournisseur17].[Banque_folio] [ChargeurID_Banque_folio]
,[Fournisseur17].[No_TPS] [ChargeurID_No_TPS]
,[Fournisseur17].[No_TVQ] [ChargeurID_No_TVQ]
,[Fournisseur17].[PayerA] [ChargeurID_PayerA]
,[Fournisseur17].[PayerAID] [ChargeurID_PayerAID]
,[Fournisseur17].[Statut] [ChargeurID_Statut]
,[Fournisseur17].[Rep_Nom] [ChargeurID_Rep_Nom]
,[Fournisseur17].[Rep_Telephone] [ChargeurID_Rep_Telephone]
,[Fournisseur17].[Rep_Telephone_Poste] [ChargeurID_Rep_Telephone_Poste]
,[Fournisseur17].[Rep_Email] [ChargeurID_Rep_Email]
,[Fournisseur17].[EnAnglais] [ChargeurID_EnAnglais]
,[Fournisseur17].[Actif] [ChargeurID_Actif]
,[Fournisseur17].[MRCProducteurID] [ChargeurID_MRCProducteurID]
,[Fournisseur17].[PaiementManuel] [ChargeurID_PaiementManuel]
,[Fournisseur17].[Journal] [ChargeurID_Journal]
,[Fournisseur17].[RecoitTPS] [ChargeurID_RecoitTPS]
,[Fournisseur17].[RecoitTVQ] [ChargeurID_RecoitTVQ]
,[Fournisseur17].[ModifierTrigger] [ChargeurID_ModifierTrigger]
,[Fournisseur17].[IsProducteur] [ChargeurID_IsProducteur]
,[Fournisseur17].[IsTransporteur] [ChargeurID_IsTransporteur]
,[Fournisseur17].[IsChargeur] [ChargeurID_IsChargeur]
,[Fournisseur17].[IsAutre] [ChargeurID_IsAutre]
,[Fournisseur17].[AfficherCommentairesSurPermit] [ChargeurID_AfficherCommentairesSurPermit]
,[Fournisseur17].[PasEmissionPermis] [ChargeurID_PasEmissionPermis]
,[Fournisseur17].[Generique] [ChargeurID_Generique]
,[Fournisseur17].[Membre_OGC] [ChargeurID_Membre_OGC]
,[Fournisseur17].[InscritTPS] [ChargeurID_InscritTPS]
,[Fournisseur17].[InscritTVQ] [ChargeurID_InscritTVQ]
,[Fournisseur17].[IsOGC] [ChargeurID_IsOGC]
,[FactureFournisseur18].[ID] [Chargeur_FactureID_ID]
,[FactureFournisseur18].[NoFacture] [Chargeur_FactureID_NoFacture]
,[FactureFournisseur18].[DateFacture] [Chargeur_FactureID_DateFacture]
,[FactureFournisseur18].[Annee] [Chargeur_FactureID_Annee]
,[FactureFournisseur18].[TypeFactureFournisseur] [Chargeur_FactureID_TypeFactureFournisseur]
,[FactureFournisseur18].[TypeFacture] [Chargeur_FactureID_TypeFacture]
,[FactureFournisseur18].[TypeInvoiceAcomba] [Chargeur_FactureID_TypeInvoiceAcomba]
,[FactureFournisseur18].[FournisseurID] [Chargeur_FactureID_FournisseurID]
,[FactureFournisseur18].[PayerAID] [Chargeur_FactureID_PayerAID]
,[FactureFournisseur18].[Montant_Total] [Chargeur_FactureID_Montant_Total]
,[FactureFournisseur18].[Montant_TPS] [Chargeur_FactureID_Montant_TPS]
,[FactureFournisseur18].[Montant_TVQ] [Chargeur_FactureID_Montant_TVQ]
,[FactureFournisseur18].[Description] [Chargeur_FactureID_Description]
,[FactureFournisseur18].[Status] [Chargeur_FactureID_Status]
,[FactureFournisseur18].[StatusDescription] [Chargeur_FactureID_StatusDescription]
,[FactureFournisseur18].[NumeroCheque] [Chargeur_FactureID_NumeroCheque]
,[FactureFournisseur18].[NumeroPaiement] [Chargeur_FactureID_NumeroPaiement]
,[FactureFournisseur18].[NumeroPaiementUnique] [Chargeur_FactureID_NumeroPaiementUnique]
,[FactureFournisseur18].[DateFactureAcomba] [Chargeur_FactureID_DateFactureAcomba]
,[FactureFournisseur18].[DatePaiementAcomba] [Chargeur_FactureID_DatePaiementAcomba]

From [dbo].[Livraison] [Livraison]
    Inner Join [dbo].[Permit] [Permit1] On [Livraison].[ID] = [Permit1].[ID]
        Left Outer Join [dbo].[Contrat] [Contrat2] On [Livraison].[ContratID] = [Contrat2].[ID]
            Left Outer Join [dbo].[UniteMesure] [UniteMesure3] On [Livraison].[UniteMesureID] = [UniteMesure3].[ID]
                Left Outer Join [dbo].[Essence] [Essence4] On [Livraison].[EssenceID] = [Essence4].[ID]
                    Left Outer Join [dbo].[Fournisseur] [Fournisseur5] On [Livraison].[DroitCoupeID] = [Fournisseur5].[ID]
                        Left Outer Join [dbo].[Fournisseur] [Fournisseur6] On [Livraison].[EntentePaiementID] = [Fournisseur6].[ID]
                            Left Outer Join [dbo].[Fournisseur] [Fournisseur7] On [Livraison].[TransporteurID] = [Fournisseur7].[ID]
                                Left Outer Join [dbo].[Periode] [Periode8] On [Livraison].[Annee] = [Periode8].[Annee]
                                    Left Outer Join [dbo].[Periode] [Periode9] On [Livraison].[Periode] = [Periode9].[SemaineNo]
                                        Left Outer Join [dbo].[FactureFournisseur] [FactureFournisseur10] On [Livraison].[Producteur1_FactureID] = [FactureFournisseur10].[ID]
                                            Left Outer Join [dbo].[FactureFournisseur] [FactureFournisseur11] On [Livraison].[Producteur2_FactureID] = [FactureFournisseur11].[ID]
                                                Left Outer Join [dbo].[FactureFournisseur] [FactureFournisseur12] On [Livraison].[Transporteur_FactureID] = [FactureFournisseur12].[ID]
                                                    Left Outer Join [dbo].[FactureClient] [FactureClient13] On [Livraison].[Usine_FactureID] = [FactureClient13].[ID]
                                                        Left Outer Join [dbo].[Lot] [Lot14] On [Livraison].[LotID] = [Lot14].[ID]
                                                            Left Outer Join [dbo].[Municipalite_Zone] [Municipalite_Zone15] On [Livraison].[ZoneID] = [Municipalite_Zone15].[ID]
                                                                Left Outer Join [dbo].[Municipalite_Zone] [Municipalite_Zone16] On [Livraison].[MunicipaliteID] = [Municipalite_Zone16].[MunicipaliteID]
                                                                    Left Outer Join [dbo].[Fournisseur] [Fournisseur17] On [Livraison].[ChargeurID] = [Fournisseur17].[ID]
                                                                        Left Outer Join [dbo].[FactureFournisseur] [FactureFournisseur18] On [Livraison].[Chargeur_FactureID] = [FactureFournisseur18].[ID]

Where

    ((@ID Is Null) Or ([Livraison].[ID] = @ID))
And ((@ContratID Is Null) Or ([Livraison].[ContratID] = @ContratID))
And ((@UniteMesureID Is Null) Or ([Livraison].[UniteMesureID] = @UniteMesureID))
And ((@EssenceID Is Null) Or ([Livraison].[EssenceID] = @EssenceID))
And ((@DroitCoupeID Is Null) Or ([Livraison].[DroitCoupeID] = @DroitCoupeID))
And ((@EntentePaiementID Is Null) Or ([Livraison].[EntentePaiementID] = @EntentePaiementID))
And ((@TransporteurID Is Null) Or ([Livraison].[TransporteurID] = @TransporteurID))
And ((@Annee Is Null) Or ([Livraison].[Annee] = @Annee))
And ((@Periode Is Null) Or ([Livraison].[Periode] = @Periode))
And ((@Producteur1_FactureID Is Null) Or ([Livraison].[Producteur1_FactureID] = @Producteur1_FactureID))
And ((@Producteur2_FactureID Is Null) Or ([Livraison].[Producteur2_FactureID] = @Producteur2_FactureID))
And ((@Transporteur_FactureID Is Null) Or ([Livraison].[Transporteur_FactureID] = @Transporteur_FactureID))
And ((@Usine_FactureID Is Null) Or ([Livraison].[Usine_FactureID] = @Usine_FactureID))
And ((@LotID Is Null) Or ([Livraison].[LotID] = @LotID))
And ((@ZoneID Is Null) Or ([Livraison].[ZoneID] = @ZoneID))
And ((@MunicipaliteID Is Null) Or ([Livraison].[MunicipaliteID] = @MunicipaliteID))
And ((@ChargeurID Is Null) Or ([Livraison].[ChargeurID] = @ChargeurID))
And ((@Chargeur_FactureID Is Null) Or ([Livraison].[Chargeur_FactureID] = @Chargeur_FactureID))
)



