CREATE FUNCTION [dbo].[fnLivraison_Detail_Full]
(@ID INT=Null, @LivraisonID INT=Null, @ContratID VARCHAR (10)=Null, @EssenceID VARCHAR (6)=Null, @UniteMesureID VARCHAR (6)=Null, @ProducteurID VARCHAR (15)=Null, @ContingentementID INT=Null, @Code CHAR (4)=Null)
RETURNS TABLE 
AS
RETURN 
    (
Select TOP 100 PERCENT
 [Livraison_Detail].[ID]
,[Livraison_Detail].[LivraisonID]
,[Livraison_Detail].[ContratID]
,[Livraison_Detail].[EssenceID]
,[Livraison_Detail].[UniteMesureID]
,[Livraison_Detail].[ProducteurID]
,[Livraison_Detail].[Droit_Coupe]
,[Livraison_Detail].[VolumeBrut]
,[Livraison_Detail].[VolumeReduction]
,[Livraison_Detail].[VolumeNet]
,[Livraison_Detail].[VolumeContingente]
,[Livraison_Detail].[ContingentementID]
,[Livraison_Detail].[DateCalcul]
,[Livraison_Detail].[Taux_Usine]
,[Livraison_Detail].[Montant_Usine]
,[Livraison_Detail].[Taux_Producteur]
,[Livraison_Detail].[Montant_ProducteurBrut]
,[Livraison_Detail].[Taux_TransporteurMoyen]
,[Livraison_Detail].[Taux_TransporteurMoyen_Override]
,[Livraison_Detail].[Montant_TransporteurMoyen]
,[Livraison_Detail].[Taux_Preleve_Plan_Conjoint]
,[Livraison_Detail].[Montant_Preleve_Plan_Conjoint]
,[Livraison_Detail].[Taux_Preleve_Fond_Roulement]
,[Livraison_Detail].[Montant_Preleve_Fond_Roulement]
,[Livraison_Detail].[Taux_Preleve_Fond_Forestier]
,[Livraison_Detail].[Montant_Preleve_Fond_Forestier]
,[Livraison_Detail].[Taux_Preleve_Divers]
,[Livraison_Detail].[Montant_Preleve_Divers]
,[Livraison_Detail].[Montant_ProducteurNet]
,[Livraison_Detail].[Taux_Producteur_Override]
,[Livraison_Detail].[Taux_Usine_Override]
,[Livraison_Detail].[Code]
,[Livraison_Detail].[UsePreleveMontant]
,[Livraison1].[ID] [LivraisonID_ID]
,[Livraison1].[DateLivraison] [LivraisonID_DateLivraison]
,[Livraison1].[DatePaye] [LivraisonID_DatePaye]
,[Livraison1].[ContratID] [LivraisonID_ContratID]
,[Livraison1].[UniteMesureID] [LivraisonID_UniteMesureID]
,[Livraison1].[EssenceID] [LivraisonID_EssenceID]
,[Livraison1].[Sciage] [LivraisonID_Sciage]
,[Livraison1].[NumeroFactureUsine] [LivraisonID_NumeroFactureUsine]
,[Livraison1].[DroitCoupeID] [LivraisonID_DroitCoupeID]
,[Livraison1].[EntentePaiementID] [LivraisonID_EntentePaiementID]
,[Livraison1].[TransporteurID] [LivraisonID_TransporteurID]
,[Livraison1].[VR] [LivraisonID_VR]
,[Livraison1].[MasseLimite] [LivraisonID_MasseLimite]
,[Livraison1].[VolumeBrut] [LivraisonID_VolumeBrut]
,[Livraison1].[VolumeTare] [LivraisonID_VolumeTare]
,[Livraison1].[VolumeTransporte] [LivraisonID_VolumeTransporte]
,[Livraison1].[VolumeSurcharge] [LivraisonID_VolumeSurcharge]
,[Livraison1].[VolumeAPayer] [LivraisonID_VolumeAPayer]
,[Livraison1].[Annee] [LivraisonID_Annee]
,[Livraison1].[Periode] [LivraisonID_Periode]
,[Livraison1].[DateCalcul] [LivraisonID_DateCalcul]
,[Livraison1].[Taux_Transporteur] [LivraisonID_Taux_Transporteur]
,[Livraison1].[Montant_Transporteur] [LivraisonID_Montant_Transporteur]
,[Livraison1].[Montant_Usine] [LivraisonID_Montant_Usine]
,[Livraison1].[Montant_Producteur1] [LivraisonID_Montant_Producteur1]
,[Livraison1].[Montant_Producteur2] [LivraisonID_Montant_Producteur2]
,[Livraison1].[Montant_Preleve_Plan_Conjoint] [LivraisonID_Montant_Preleve_Plan_Conjoint]
,[Livraison1].[Montant_Preleve_Fond_Roulement] [LivraisonID_Montant_Preleve_Fond_Roulement]
,[Livraison1].[Montant_Preleve_Fond_Forestier] [LivraisonID_Montant_Preleve_Fond_Forestier]
,[Livraison1].[Montant_Preleve_Divers] [LivraisonID_Montant_Preleve_Divers]
,[Livraison1].[Montant_Surcharge] [LivraisonID_Montant_Surcharge]
,[Livraison1].[Montant_MiseEnCommun] [LivraisonID_Montant_MiseEnCommun]
,[Livraison1].[Facture] [LivraisonID_Facture]
,[Livraison1].[Producteur1_FactureID] [LivraisonID_Producteur1_FactureID]
,[Livraison1].[Producteur2_FactureID] [LivraisonID_Producteur2_FactureID]
,[Livraison1].[Transporteur_FactureID] [LivraisonID_Transporteur_FactureID]
,[Livraison1].[Usine_FactureID] [LivraisonID_Usine_FactureID]
,[Livraison1].[ErreurCalcul] [LivraisonID_ErreurCalcul]
,[Livraison1].[ErreurDescription] [LivraisonID_ErreurDescription]
,[Livraison1].[LotID] [LivraisonID_LotID]
,[Livraison1].[Taux_Transporteur_Override] [LivraisonID_Taux_Transporteur_Override]
,[Livraison1].[PaieTransporteur] [LivraisonID_PaieTransporteur]
,[Livraison1].[VolumeSurcharge_Override] [LivraisonID_VolumeSurcharge_Override]
,[Livraison1].[SurchargeManuel] [LivraisonID_SurchargeManuel]
,[Livraison1].[Code] [LivraisonID_Code]
,[Livraison1].[NombrePermis] [LivraisonID_NombrePermis]
,[Livraison1].[ZoneID] [LivraisonID_ZoneID]
,[Livraison1].[MunicipaliteID] [LivraisonID_MunicipaliteID]
,[Livraison1].[ChargeurID] [LivraisonID_ChargeurID]
,[Livraison1].[Montant_Chargeur] [LivraisonID_Montant_Chargeur]
,[Livraison1].[Frais_ChargeurAuProducteur] [LivraisonID_Frais_ChargeurAuProducteur]
,[Livraison1].[Frais_ChargeurAuTransporteur] [LivraisonID_Frais_ChargeurAuTransporteur]
,[Livraison1].[Frais_AutresAuProducteur] [LivraisonID_Frais_AutresAuProducteur]
,[Livraison1].[Frais_AutresAuProducteurDescription] [LivraisonID_Frais_AutresAuProducteurDescription]
,[Livraison1].[Frais_AutresAuTransporteur] [LivraisonID_Frais_AutresAuTransporteur]
,[Livraison1].[Frais_AutresAuTransporteurDescription] [LivraisonID_Frais_AutresAuTransporteurDescription]
,[Livraison1].[Frais_CompensationDeDeplacement] [LivraisonID_Frais_CompensationDeDeplacement]
,[Livraison1].[Chargeur_FactureID] [LivraisonID_Chargeur_FactureID]
,[Livraison1].[Commentaires_Producteur] [LivraisonID_Commentaires_Producteur]
,[Livraison1].[Commentaires_Transporteur] [LivraisonID_Commentaires_Transporteur]
,[Livraison1].[Commentaires_Chargeur] [LivraisonID_Commentaires_Chargeur]
,[Livraison1].[TauxChargeurAuProducteur] [LivraisonID_TauxChargeurAuProducteur]
,[Livraison1].[TauxChargeurAuTransporteur] [LivraisonID_TauxChargeurAuTransporteur]
,[Livraison1].[Frais_AutresRevenusTransporteur] [LivraisonID_Frais_AutresRevenusTransporteur]
,[Livraison1].[Frais_AutresRevenusTransporteurDescription] [LivraisonID_Frais_AutresRevenusTransporteurDescription]
,[Livraison1].[Frais_AutresRevenusProducteur] [LivraisonID_Frais_AutresRevenusProducteur]
,[Livraison1].[Frais_AutresRevenusProducteurDescription] [LivraisonID_Frais_AutresRevenusProducteurDescription]
,[Livraison1].[Montant_SurchargeProducteur] [LivraisonID_Montant_SurchargeProducteur]
,[Contrat_EssenceUnite2].[ContratID] [ContratID_ContratID]
,[Contrat_EssenceUnite2].[EssenceID] [ContratID_EssenceID]
,[Contrat_EssenceUnite2].[UniteID] [ContratID_UniteID]
,[Contrat_EssenceUnite2].[Code] [ContratID_Code]
,[Contrat_EssenceUnite2].[Quantite_prevue] [ContratID_Quantite_prevue]
,[Contrat_EssenceUnite2].[Taux_usine] [ContratID_Taux_usine]
,[Contrat_EssenceUnite2].[Taux_producteur] [ContratID_Taux_producteur]
,[Contrat_EssenceUnite2].[Actif] [ContratID_Actif]
,[Contrat_EssenceUnite2].[Description] [ContratID_Description]
,[Contrat_EssenceUnite3].[ContratID] [EssenceID_ContratID]
,[Contrat_EssenceUnite3].[EssenceID] [EssenceID_EssenceID]
,[Contrat_EssenceUnite3].[UniteID] [EssenceID_UniteID]
,[Contrat_EssenceUnite3].[Code] [EssenceID_Code]
,[Contrat_EssenceUnite3].[Quantite_prevue] [EssenceID_Quantite_prevue]
,[Contrat_EssenceUnite3].[Taux_usine] [EssenceID_Taux_usine]
,[Contrat_EssenceUnite3].[Taux_producteur] [EssenceID_Taux_producteur]
,[Contrat_EssenceUnite3].[Actif] [EssenceID_Actif]
,[Contrat_EssenceUnite3].[Description] [EssenceID_Description]
,[Contrat_EssenceUnite4].[ContratID] [UniteMesureID_ContratID]
,[Contrat_EssenceUnite4].[EssenceID] [UniteMesureID_EssenceID]
,[Contrat_EssenceUnite4].[UniteID] [UniteMesureID_UniteID]
,[Contrat_EssenceUnite4].[Code] [UniteMesureID_Code]
,[Contrat_EssenceUnite4].[Quantite_prevue] [UniteMesureID_Quantite_prevue]
,[Contrat_EssenceUnite4].[Taux_usine] [UniteMesureID_Taux_usine]
,[Contrat_EssenceUnite4].[Taux_producteur] [UniteMesureID_Taux_producteur]
,[Contrat_EssenceUnite4].[Actif] [UniteMesureID_Actif]
,[Contrat_EssenceUnite4].[Description] [UniteMesureID_Description]
,[Fournisseur5].[ID] [ProducteurID_ID]
,[Fournisseur5].[CleTri] [ProducteurID_CleTri]
,[Fournisseur5].[Nom] [ProducteurID_Nom]
,[Fournisseur5].[AuSoinsDe] [ProducteurID_AuSoinsDe]
,[Fournisseur5].[Rue] [ProducteurID_Rue]
,[Fournisseur5].[Ville] [ProducteurID_Ville]
,[Fournisseur5].[PaysID] [ProducteurID_PaysID]
,[Fournisseur5].[Code_postal] [ProducteurID_Code_postal]
,[Fournisseur5].[Telephone] [ProducteurID_Telephone]
,[Fournisseur5].[Telephone_Poste] [ProducteurID_Telephone_Poste]
,[Fournisseur5].[Telecopieur] [ProducteurID_Telecopieur]
,[Fournisseur5].[Telephone2] [ProducteurID_Telephone2]
,[Fournisseur5].[Telephone2_Desc] [ProducteurID_Telephone2_Desc]
,[Fournisseur5].[Telephone2_Poste] [ProducteurID_Telephone2_Poste]
,[Fournisseur5].[Telephone3] [ProducteurID_Telephone3]
,[Fournisseur5].[Telephone3_Desc] [ProducteurID_Telephone3_Desc]
,[Fournisseur5].[Telephone3_Poste] [ProducteurID_Telephone3_Poste]
,[Fournisseur5].[No_membre] [ProducteurID_No_membre]
,[Fournisseur5].[Resident] [ProducteurID_Resident]
,[Fournisseur5].[Email] [ProducteurID_Email]
,[Fournisseur5].[WWW] [ProducteurID_WWW]
,[Fournisseur5].[Commentaires] [ProducteurID_Commentaires]
,[Fournisseur5].[AfficherCommentaires] [ProducteurID_AfficherCommentaires]
,[Fournisseur5].[DepotDirect] [ProducteurID_DepotDirect]
,[Fournisseur5].[InstitutionBanquaireID] [ProducteurID_InstitutionBanquaireID]
,[Fournisseur5].[Banque_transit] [ProducteurID_Banque_transit]
,[Fournisseur5].[Banque_folio] [ProducteurID_Banque_folio]
,[Fournisseur5].[No_TPS] [ProducteurID_No_TPS]
,[Fournisseur5].[No_TVQ] [ProducteurID_No_TVQ]
,[Fournisseur5].[PayerA] [ProducteurID_PayerA]
,[Fournisseur5].[PayerAID] [ProducteurID_PayerAID]
,[Fournisseur5].[Statut] [ProducteurID_Statut]
,[Fournisseur5].[Rep_Nom] [ProducteurID_Rep_Nom]
,[Fournisseur5].[Rep_Telephone] [ProducteurID_Rep_Telephone]
,[Fournisseur5].[Rep_Telephone_Poste] [ProducteurID_Rep_Telephone_Poste]
,[Fournisseur5].[Rep_Email] [ProducteurID_Rep_Email]
,[Fournisseur5].[EnAnglais] [ProducteurID_EnAnglais]
,[Fournisseur5].[Actif] [ProducteurID_Actif]
,[Fournisseur5].[MRCProducteurID] [ProducteurID_MRCProducteurID]
,[Fournisseur5].[PaiementManuel] [ProducteurID_PaiementManuel]
,[Fournisseur5].[Journal] [ProducteurID_Journal]
,[Fournisseur5].[RecoitTPS] [ProducteurID_RecoitTPS]
,[Fournisseur5].[RecoitTVQ] [ProducteurID_RecoitTVQ]
,[Fournisseur5].[ModifierTrigger] [ProducteurID_ModifierTrigger]
,[Fournisseur5].[IsProducteur] [ProducteurID_IsProducteur]
,[Fournisseur5].[IsTransporteur] [ProducteurID_IsTransporteur]
,[Fournisseur5].[IsChargeur] [ProducteurID_IsChargeur]
,[Fournisseur5].[IsAutre] [ProducteurID_IsAutre]
,[Fournisseur5].[AfficherCommentairesSurPermit] [ProducteurID_AfficherCommentairesSurPermit]
,[Fournisseur5].[PasEmissionPermis] [ProducteurID_PasEmissionPermis]
,[Fournisseur5].[Generique] [ProducteurID_Generique]
,[Contingentement6].[ID] [ContingentementID_ID]
,[Contingentement6].[ContingentUsine] [ContingentementID_ContingentUsine]
,[Contingentement6].[UsineID] [ContingentementID_UsineID]
,[Contingentement6].[RegroupementID] [ContingentementID_RegroupementID]
,[Contingentement6].[Annee] [ContingentementID_Annee]
,[Contingentement6].[PeriodeContingentement] [ContingentementID_PeriodeContingentement]
,[Contingentement6].[PeriodeDebut] [ContingentementID_PeriodeDebut]
,[Contingentement6].[PeriodeFin] [ContingentementID_PeriodeFin]
,[Contingentement6].[EssenceID] [ContingentementID_EssenceID]
,[Contingentement6].[UniteMesureID] [ContingentementID_UniteMesureID]
,[Contingentement6].[Volume_Usine] [ContingentementID_Volume_Usine]
,[Contingentement6].[Facteur] [ContingentementID_Facteur]
,[Contingentement6].[Volume_Fixe] [ContingentementID_Volume_Fixe]
,[Contingentement6].[Date_Calcul] [ContingentementID_Date_Calcul]
,[Contingentement6].[CalculAccepte] [ContingentementID_CalculAccepte]
,[Contingentement6].[Code] [ContingentementID_Code]
,[Contrat_EssenceUnite7].[ContratID] [Code_ContratID]
,[Contrat_EssenceUnite7].[EssenceID] [Code_EssenceID]
,[Contrat_EssenceUnite7].[UniteID] [Code_UniteID]
,[Contrat_EssenceUnite7].[Code] [Code_Code]
,[Contrat_EssenceUnite7].[Quantite_prevue] [Code_Quantite_prevue]
,[Contrat_EssenceUnite7].[Taux_usine] [Code_Taux_usine]
,[Contrat_EssenceUnite7].[Taux_producteur] [Code_Taux_producteur]
,[Contrat_EssenceUnite7].[Actif] [Code_Actif]
,[Contrat_EssenceUnite7].[Description] [Code_Description]

From [dbo].[Livraison_Detail] [Livraison_Detail]
    Inner Join [dbo].[Livraison] [Livraison1] On [Livraison_Detail].[LivraisonID] = [Livraison1].[ID]
        Inner Join [dbo].[Contrat_EssenceUnite] [Contrat_EssenceUnite2] On [Livraison_Detail].[ContratID] = [Contrat_EssenceUnite2].[ContratID]
            Inner Join [dbo].[Contrat_EssenceUnite] [Contrat_EssenceUnite3] On [Livraison_Detail].[EssenceID] = [Contrat_EssenceUnite3].[EssenceID]
                Inner Join [dbo].[Contrat_EssenceUnite] [Contrat_EssenceUnite4] On [Livraison_Detail].[UniteMesureID] = [Contrat_EssenceUnite4].[UniteID]
                    Inner Join [dbo].[Fournisseur] [Fournisseur5] On [Livraison_Detail].[ProducteurID] = [Fournisseur5].[ID]
                        Left Outer Join [dbo].[Contingentement] [Contingentement6] On [Livraison_Detail].[ContingentementID] = [Contingentement6].[ID]
                            Left Outer Join [dbo].[Contrat_EssenceUnite] [Contrat_EssenceUnite7] On [Livraison_Detail].[Code] = [Contrat_EssenceUnite7].[Code]

Where

    ((@ID Is Null) Or ([Livraison_Detail].[ID] = @ID))
And ((@LivraisonID Is Null) Or ([Livraison_Detail].[LivraisonID] = @LivraisonID))
And ((@ContratID Is Null) Or ([Livraison_Detail].[ContratID] = @ContratID))
And ((@EssenceID Is Null) Or ([Livraison_Detail].[EssenceID] = @EssenceID))
And ((@UniteMesureID Is Null) Or ([Livraison_Detail].[UniteMesureID] = @UniteMesureID))
And ((@ProducteurID Is Null) Or ([Livraison_Detail].[ProducteurID] = @ProducteurID))
And ((@ContingentementID Is Null) Or ([Livraison_Detail].[ContingentementID] = @ContingentementID))
And ((@Code Is Null) Or ([Livraison_Detail].[Code] = @Code))
)



