

Create Function [fnPermit_Full]

(
 @ID [int] = Null
,@ContratID [varchar](10) = Null
,@EssenceID [varchar](6) = Null
,@TransporteurID [varchar](15) = Null
,@ProducteurDroitCoupeID [varchar](15) = Null
,@ProducteurEntentePaiementID [varchar](15) = Null
,@LotID [int] = Null
,@ChargeurID [varchar](15) = Null
,@ZoneID [varchar](2) = Null
,@MunicipaliteID [varchar](6) = Null
)


--	IMPORTANT:
--	Changes to this SQL code may cause incorrect behavior
--	and will be lost if the code is regenerated. 


Returns Table

As

Return
(
Select TOP 100 PERCENT
 [Permit].[ID]
,[Permit].[DatePermit]
,[Permit].[DateDebut]
,[Permit].[DateFin]
,[Permit].[Annee]
,[Permit].[Periode]
,[Permit].[ContratID]
,[Permit].[EssenceID]
,[Permit].[PermitSciage]
,[Permit].[TransporteurID]
,[Permit].[VR]
,[Permit].[ProducteurDroitCoupeID]
,[Permit].[ProducteurEntentePaiementID]
,[Permit].[PermitLivre]
,[Permit].[PermitImprime]
,[Permit].[PermitAnnule]
,[Permit].[LotID]
,[Permit].[EssenceSciage]
,[Permit].[Code]
,[Permit].[Remarques]
,[Permit].[ChargeurID]
,[Permit].[ZoneID]
,[Permit].[MunicipaliteID]
,[Contrat1].[ID] [ContratID_ID]
,[Contrat1].[Description] [ContratID_Description]
,[Contrat1].[UsineID] [ContratID_UsineID]
,[Contrat1].[Annee] [ContratID_Annee]
,[Contrat1].[Date_debut] [ContratID_Date_debut]
,[Contrat1].[Date_fin] [ContratID_Date_fin]
,[Contrat1].[Actif] [ContratID_Actif]
,[Contrat1].[PaieTransporteur] [ContratID_PaieTransporteur]
,[Contrat1].[Taux_Surcharge] [ContratID_Taux_Surcharge]
,[Contrat1].[SurchargeManuel] [ContratID_SurchargeManuel]
,[Contrat1].[TxTransSameProd] [ContratID_TxTransSameProd]
,[Essence2].[ID] [EssenceID_ID]
,[Essence2].[Description] [EssenceID_Description]
,[Essence2].[RegroupementID] [EssenceID_RegroupementID]
,[Essence2].[ContingentID] [EssenceID_ContingentID]
,[Essence2].[RepartitionID] [EssenceID_RepartitionID]
,[Essence2].[Actif] [EssenceID_Actif]
,[Fournisseur3].[ID] [TransporteurID_ID]
,[Fournisseur3].[CleTri] [TransporteurID_CleTri]
,[Fournisseur3].[Nom] [TransporteurID_Nom]
,[Fournisseur3].[AuSoinsDe] [TransporteurID_AuSoinsDe]
,[Fournisseur3].[Rue] [TransporteurID_Rue]
,[Fournisseur3].[Ville] [TransporteurID_Ville]
,[Fournisseur3].[PaysID] [TransporteurID_PaysID]
,[Fournisseur3].[Code_postal] [TransporteurID_Code_postal]
,[Fournisseur3].[Telephone] [TransporteurID_Telephone]
,[Fournisseur3].[Telephone_Poste] [TransporteurID_Telephone_Poste]
,[Fournisseur3].[Telecopieur] [TransporteurID_Telecopieur]
,[Fournisseur3].[Telephone2] [TransporteurID_Telephone2]
,[Fournisseur3].[Telephone2_Desc] [TransporteurID_Telephone2_Desc]
,[Fournisseur3].[Telephone2_Poste] [TransporteurID_Telephone2_Poste]
,[Fournisseur3].[Telephone3] [TransporteurID_Telephone3]
,[Fournisseur3].[Telephone3_Desc] [TransporteurID_Telephone3_Desc]
,[Fournisseur3].[Telephone3_Poste] [TransporteurID_Telephone3_Poste]
,[Fournisseur3].[No_membre] [TransporteurID_No_membre]
,[Fournisseur3].[Resident] [TransporteurID_Resident]
,[Fournisseur3].[Email] [TransporteurID_Email]
,[Fournisseur3].[WWW] [TransporteurID_WWW]
,[Fournisseur3].[Commentaires] [TransporteurID_Commentaires]
,[Fournisseur3].[AfficherCommentaires] [TransporteurID_AfficherCommentaires]
,[Fournisseur3].[DepotDirect] [TransporteurID_DepotDirect]
,[Fournisseur3].[InstitutionBanquaireID] [TransporteurID_InstitutionBanquaireID]
,[Fournisseur3].[Banque_transit] [TransporteurID_Banque_transit]
,[Fournisseur3].[Banque_folio] [TransporteurID_Banque_folio]
,[Fournisseur3].[No_TPS] [TransporteurID_No_TPS]
,[Fournisseur3].[No_TVQ] [TransporteurID_No_TVQ]
,[Fournisseur3].[PayerA] [TransporteurID_PayerA]
,[Fournisseur3].[PayerAID] [TransporteurID_PayerAID]
,[Fournisseur3].[Statut] [TransporteurID_Statut]
,[Fournisseur3].[Rep_Nom] [TransporteurID_Rep_Nom]
,[Fournisseur3].[Rep_Telephone] [TransporteurID_Rep_Telephone]
,[Fournisseur3].[Rep_Telephone_Poste] [TransporteurID_Rep_Telephone_Poste]
,[Fournisseur3].[Rep_Email] [TransporteurID_Rep_Email]
,[Fournisseur3].[EnAnglais] [TransporteurID_EnAnglais]
,[Fournisseur3].[Actif] [TransporteurID_Actif]
,[Fournisseur3].[MRCProducteurID] [TransporteurID_MRCProducteurID]
,[Fournisseur3].[PaiementManuel] [TransporteurID_PaiementManuel]
,[Fournisseur3].[Journal] [TransporteurID_Journal]
,[Fournisseur3].[RecoitTPS] [TransporteurID_RecoitTPS]
,[Fournisseur3].[RecoitTVQ] [TransporteurID_RecoitTVQ]
,[Fournisseur3].[ModifierTrigger] [TransporteurID_ModifierTrigger]
,[Fournisseur3].[IsProducteur] [TransporteurID_IsProducteur]
,[Fournisseur3].[IsTransporteur] [TransporteurID_IsTransporteur]
,[Fournisseur3].[IsChargeur] [TransporteurID_IsChargeur]
,[Fournisseur3].[IsAutre] [TransporteurID_IsAutre]
,[Fournisseur3].[AfficherCommentairesSurPermit] [TransporteurID_AfficherCommentairesSurPermit]
,[Fournisseur3].[PasEmissionPermis] [TransporteurID_PasEmissionPermis]
,[Fournisseur3].[Generique] [TransporteurID_Generique]
,[Fournisseur4].[ID] [ProducteurDroitCoupeID_ID]
,[Fournisseur4].[CleTri] [ProducteurDroitCoupeID_CleTri]
,[Fournisseur4].[Nom] [ProducteurDroitCoupeID_Nom]
,[Fournisseur4].[AuSoinsDe] [ProducteurDroitCoupeID_AuSoinsDe]
,[Fournisseur4].[Rue] [ProducteurDroitCoupeID_Rue]
,[Fournisseur4].[Ville] [ProducteurDroitCoupeID_Ville]
,[Fournisseur4].[PaysID] [ProducteurDroitCoupeID_PaysID]
,[Fournisseur4].[Code_postal] [ProducteurDroitCoupeID_Code_postal]
,[Fournisseur4].[Telephone] [ProducteurDroitCoupeID_Telephone]
,[Fournisseur4].[Telephone_Poste] [ProducteurDroitCoupeID_Telephone_Poste]
,[Fournisseur4].[Telecopieur] [ProducteurDroitCoupeID_Telecopieur]
,[Fournisseur4].[Telephone2] [ProducteurDroitCoupeID_Telephone2]
,[Fournisseur4].[Telephone2_Desc] [ProducteurDroitCoupeID_Telephone2_Desc]
,[Fournisseur4].[Telephone2_Poste] [ProducteurDroitCoupeID_Telephone2_Poste]
,[Fournisseur4].[Telephone3] [ProducteurDroitCoupeID_Telephone3]
,[Fournisseur4].[Telephone3_Desc] [ProducteurDroitCoupeID_Telephone3_Desc]
,[Fournisseur4].[Telephone3_Poste] [ProducteurDroitCoupeID_Telephone3_Poste]
,[Fournisseur4].[No_membre] [ProducteurDroitCoupeID_No_membre]
,[Fournisseur4].[Resident] [ProducteurDroitCoupeID_Resident]
,[Fournisseur4].[Email] [ProducteurDroitCoupeID_Email]
,[Fournisseur4].[WWW] [ProducteurDroitCoupeID_WWW]
,[Fournisseur4].[Commentaires] [ProducteurDroitCoupeID_Commentaires]
,[Fournisseur4].[AfficherCommentaires] [ProducteurDroitCoupeID_AfficherCommentaires]
,[Fournisseur4].[DepotDirect] [ProducteurDroitCoupeID_DepotDirect]
,[Fournisseur4].[InstitutionBanquaireID] [ProducteurDroitCoupeID_InstitutionBanquaireID]
,[Fournisseur4].[Banque_transit] [ProducteurDroitCoupeID_Banque_transit]
,[Fournisseur4].[Banque_folio] [ProducteurDroitCoupeID_Banque_folio]
,[Fournisseur4].[No_TPS] [ProducteurDroitCoupeID_No_TPS]
,[Fournisseur4].[No_TVQ] [ProducteurDroitCoupeID_No_TVQ]
,[Fournisseur4].[PayerA] [ProducteurDroitCoupeID_PayerA]
,[Fournisseur4].[PayerAID] [ProducteurDroitCoupeID_PayerAID]
,[Fournisseur4].[Statut] [ProducteurDroitCoupeID_Statut]
,[Fournisseur4].[Rep_Nom] [ProducteurDroitCoupeID_Rep_Nom]
,[Fournisseur4].[Rep_Telephone] [ProducteurDroitCoupeID_Rep_Telephone]
,[Fournisseur4].[Rep_Telephone_Poste] [ProducteurDroitCoupeID_Rep_Telephone_Poste]
,[Fournisseur4].[Rep_Email] [ProducteurDroitCoupeID_Rep_Email]
,[Fournisseur4].[EnAnglais] [ProducteurDroitCoupeID_EnAnglais]
,[Fournisseur4].[Actif] [ProducteurDroitCoupeID_Actif]
,[Fournisseur4].[MRCProducteurID] [ProducteurDroitCoupeID_MRCProducteurID]
,[Fournisseur4].[PaiementManuel] [ProducteurDroitCoupeID_PaiementManuel]
,[Fournisseur4].[Journal] [ProducteurDroitCoupeID_Journal]
,[Fournisseur4].[RecoitTPS] [ProducteurDroitCoupeID_RecoitTPS]
,[Fournisseur4].[RecoitTVQ] [ProducteurDroitCoupeID_RecoitTVQ]
,[Fournisseur4].[ModifierTrigger] [ProducteurDroitCoupeID_ModifierTrigger]
,[Fournisseur4].[IsProducteur] [ProducteurDroitCoupeID_IsProducteur]
,[Fournisseur4].[IsTransporteur] [ProducteurDroitCoupeID_IsTransporteur]
,[Fournisseur4].[IsChargeur] [ProducteurDroitCoupeID_IsChargeur]
,[Fournisseur4].[IsAutre] [ProducteurDroitCoupeID_IsAutre]
,[Fournisseur4].[AfficherCommentairesSurPermit] [ProducteurDroitCoupeID_AfficherCommentairesSurPermit]
,[Fournisseur4].[PasEmissionPermis] [ProducteurDroitCoupeID_PasEmissionPermis]
,[Fournisseur4].[Generique] [ProducteurDroitCoupeID_Generique]
,[Fournisseur5].[ID] [ProducteurEntentePaiementID_ID]
,[Fournisseur5].[CleTri] [ProducteurEntentePaiementID_CleTri]
,[Fournisseur5].[Nom] [ProducteurEntentePaiementID_Nom]
,[Fournisseur5].[AuSoinsDe] [ProducteurEntentePaiementID_AuSoinsDe]
,[Fournisseur5].[Rue] [ProducteurEntentePaiementID_Rue]
,[Fournisseur5].[Ville] [ProducteurEntentePaiementID_Ville]
,[Fournisseur5].[PaysID] [ProducteurEntentePaiementID_PaysID]
,[Fournisseur5].[Code_postal] [ProducteurEntentePaiementID_Code_postal]
,[Fournisseur5].[Telephone] [ProducteurEntentePaiementID_Telephone]
,[Fournisseur5].[Telephone_Poste] [ProducteurEntentePaiementID_Telephone_Poste]
,[Fournisseur5].[Telecopieur] [ProducteurEntentePaiementID_Telecopieur]
,[Fournisseur5].[Telephone2] [ProducteurEntentePaiementID_Telephone2]
,[Fournisseur5].[Telephone2_Desc] [ProducteurEntentePaiementID_Telephone2_Desc]
,[Fournisseur5].[Telephone2_Poste] [ProducteurEntentePaiementID_Telephone2_Poste]
,[Fournisseur5].[Telephone3] [ProducteurEntentePaiementID_Telephone3]
,[Fournisseur5].[Telephone3_Desc] [ProducteurEntentePaiementID_Telephone3_Desc]
,[Fournisseur5].[Telephone3_Poste] [ProducteurEntentePaiementID_Telephone3_Poste]
,[Fournisseur5].[No_membre] [ProducteurEntentePaiementID_No_membre]
,[Fournisseur5].[Resident] [ProducteurEntentePaiementID_Resident]
,[Fournisseur5].[Email] [ProducteurEntentePaiementID_Email]
,[Fournisseur5].[WWW] [ProducteurEntentePaiementID_WWW]
,[Fournisseur5].[Commentaires] [ProducteurEntentePaiementID_Commentaires]
,[Fournisseur5].[AfficherCommentaires] [ProducteurEntentePaiementID_AfficherCommentaires]
,[Fournisseur5].[DepotDirect] [ProducteurEntentePaiementID_DepotDirect]
,[Fournisseur5].[InstitutionBanquaireID] [ProducteurEntentePaiementID_InstitutionBanquaireID]
,[Fournisseur5].[Banque_transit] [ProducteurEntentePaiementID_Banque_transit]
,[Fournisseur5].[Banque_folio] [ProducteurEntentePaiementID_Banque_folio]
,[Fournisseur5].[No_TPS] [ProducteurEntentePaiementID_No_TPS]
,[Fournisseur5].[No_TVQ] [ProducteurEntentePaiementID_No_TVQ]
,[Fournisseur5].[PayerA] [ProducteurEntentePaiementID_PayerA]
,[Fournisseur5].[PayerAID] [ProducteurEntentePaiementID_PayerAID]
,[Fournisseur5].[Statut] [ProducteurEntentePaiementID_Statut]
,[Fournisseur5].[Rep_Nom] [ProducteurEntentePaiementID_Rep_Nom]
,[Fournisseur5].[Rep_Telephone] [ProducteurEntentePaiementID_Rep_Telephone]
,[Fournisseur5].[Rep_Telephone_Poste] [ProducteurEntentePaiementID_Rep_Telephone_Poste]
,[Fournisseur5].[Rep_Email] [ProducteurEntentePaiementID_Rep_Email]
,[Fournisseur5].[EnAnglais] [ProducteurEntentePaiementID_EnAnglais]
,[Fournisseur5].[Actif] [ProducteurEntentePaiementID_Actif]
,[Fournisseur5].[MRCProducteurID] [ProducteurEntentePaiementID_MRCProducteurID]
,[Fournisseur5].[PaiementManuel] [ProducteurEntentePaiementID_PaiementManuel]
,[Fournisseur5].[Journal] [ProducteurEntentePaiementID_Journal]
,[Fournisseur5].[RecoitTPS] [ProducteurEntentePaiementID_RecoitTPS]
,[Fournisseur5].[RecoitTVQ] [ProducteurEntentePaiementID_RecoitTVQ]
,[Fournisseur5].[ModifierTrigger] [ProducteurEntentePaiementID_ModifierTrigger]
,[Fournisseur5].[IsProducteur] [ProducteurEntentePaiementID_IsProducteur]
,[Fournisseur5].[IsTransporteur] [ProducteurEntentePaiementID_IsTransporteur]
,[Fournisseur5].[IsChargeur] [ProducteurEntentePaiementID_IsChargeur]
,[Fournisseur5].[IsAutre] [ProducteurEntentePaiementID_IsAutre]
,[Fournisseur5].[AfficherCommentairesSurPermit] [ProducteurEntentePaiementID_AfficherCommentairesSurPermit]
,[Fournisseur5].[PasEmissionPermis] [ProducteurEntentePaiementID_PasEmissionPermis]
,[Fournisseur5].[Generique] [ProducteurEntentePaiementID_Generique]
,[Lot6].[CantonID] [LotID_CantonID]
,[Lot6].[Rang] [LotID_Rang]
,[Lot6].[Lot] [LotID_Lot]
,[Lot6].[MunicipaliteID] [LotID_MunicipaliteID]
,[Lot6].[Superficie_total] [LotID_Superficie_total]
,[Lot6].[Superficie_boisee] [LotID_Superficie_boisee]
,[Lot6].[ProprietaireID] [LotID_ProprietaireID]
,[Lot6].[ContingentID] [LotID_ContingentID]
,[Lot6].[Contingent_Date] [LotID_Contingent_Date]
,[Lot6].[Droit_coupeID] [LotID_Droit_coupeID]
,[Lot6].[Droit_coupe_Date] [LotID_Droit_coupe_Date]
,[Lot6].[Entente_paiementID] [LotID_Entente_paiementID]
,[Lot6].[Entente_paiement_Date] [LotID_Entente_paiement_Date]
,[Lot6].[Actif] [LotID_Actif]
,[Lot6].[ID] [LotID_ID]
,[Lot6].[Sequence] [LotID_Sequence]
,[Lot6].[Partie] [LotID_Partie]
,[Lot6].[Matricule] [LotID_Matricule]
,[Lot6].[ZoneID] [LotID_ZoneID]
,[Lot6].[Secteur] [LotID_Secteur]
,[Lot6].[Cadastre] [LotID_Cadastre]
,[Fournisseur7].[ID] [ChargeurID_ID]
,[Fournisseur7].[CleTri] [ChargeurID_CleTri]
,[Fournisseur7].[Nom] [ChargeurID_Nom]
,[Fournisseur7].[AuSoinsDe] [ChargeurID_AuSoinsDe]
,[Fournisseur7].[Rue] [ChargeurID_Rue]
,[Fournisseur7].[Ville] [ChargeurID_Ville]
,[Fournisseur7].[PaysID] [ChargeurID_PaysID]
,[Fournisseur7].[Code_postal] [ChargeurID_Code_postal]
,[Fournisseur7].[Telephone] [ChargeurID_Telephone]
,[Fournisseur7].[Telephone_Poste] [ChargeurID_Telephone_Poste]
,[Fournisseur7].[Telecopieur] [ChargeurID_Telecopieur]
,[Fournisseur7].[Telephone2] [ChargeurID_Telephone2]
,[Fournisseur7].[Telephone2_Desc] [ChargeurID_Telephone2_Desc]
,[Fournisseur7].[Telephone2_Poste] [ChargeurID_Telephone2_Poste]
,[Fournisseur7].[Telephone3] [ChargeurID_Telephone3]
,[Fournisseur7].[Telephone3_Desc] [ChargeurID_Telephone3_Desc]
,[Fournisseur7].[Telephone3_Poste] [ChargeurID_Telephone3_Poste]
,[Fournisseur7].[No_membre] [ChargeurID_No_membre]
,[Fournisseur7].[Resident] [ChargeurID_Resident]
,[Fournisseur7].[Email] [ChargeurID_Email]
,[Fournisseur7].[WWW] [ChargeurID_WWW]
,[Fournisseur7].[Commentaires] [ChargeurID_Commentaires]
,[Fournisseur7].[AfficherCommentaires] [ChargeurID_AfficherCommentaires]
,[Fournisseur7].[DepotDirect] [ChargeurID_DepotDirect]
,[Fournisseur7].[InstitutionBanquaireID] [ChargeurID_InstitutionBanquaireID]
,[Fournisseur7].[Banque_transit] [ChargeurID_Banque_transit]
,[Fournisseur7].[Banque_folio] [ChargeurID_Banque_folio]
,[Fournisseur7].[No_TPS] [ChargeurID_No_TPS]
,[Fournisseur7].[No_TVQ] [ChargeurID_No_TVQ]
,[Fournisseur7].[PayerA] [ChargeurID_PayerA]
,[Fournisseur7].[PayerAID] [ChargeurID_PayerAID]
,[Fournisseur7].[Statut] [ChargeurID_Statut]
,[Fournisseur7].[Rep_Nom] [ChargeurID_Rep_Nom]
,[Fournisseur7].[Rep_Telephone] [ChargeurID_Rep_Telephone]
,[Fournisseur7].[Rep_Telephone_Poste] [ChargeurID_Rep_Telephone_Poste]
,[Fournisseur7].[Rep_Email] [ChargeurID_Rep_Email]
,[Fournisseur7].[EnAnglais] [ChargeurID_EnAnglais]
,[Fournisseur7].[Actif] [ChargeurID_Actif]
,[Fournisseur7].[MRCProducteurID] [ChargeurID_MRCProducteurID]
,[Fournisseur7].[PaiementManuel] [ChargeurID_PaiementManuel]
,[Fournisseur7].[Journal] [ChargeurID_Journal]
,[Fournisseur7].[RecoitTPS] [ChargeurID_RecoitTPS]
,[Fournisseur7].[RecoitTVQ] [ChargeurID_RecoitTVQ]
,[Fournisseur7].[ModifierTrigger] [ChargeurID_ModifierTrigger]
,[Fournisseur7].[IsProducteur] [ChargeurID_IsProducteur]
,[Fournisseur7].[IsTransporteur] [ChargeurID_IsTransporteur]
,[Fournisseur7].[IsChargeur] [ChargeurID_IsChargeur]
,[Fournisseur7].[IsAutre] [ChargeurID_IsAutre]
,[Fournisseur7].[AfficherCommentairesSurPermit] [ChargeurID_AfficherCommentairesSurPermit]
,[Fournisseur7].[PasEmissionPermis] [ChargeurID_PasEmissionPermis]
,[Fournisseur7].[Generique] [ChargeurID_Generique]
,[Municipalite_Zone8].[ID] [ZoneID_ID]
,[Municipalite_Zone8].[MunicipaliteID] [ZoneID_MunicipaliteID]
,[Municipalite_Zone8].[Description] [ZoneID_Description]
,[Municipalite_Zone8].[Actif] [ZoneID_Actif]
,[Municipalite_Zone9].[ID] [MunicipaliteID_ID]
,[Municipalite_Zone9].[MunicipaliteID] [MunicipaliteID_MunicipaliteID]
,[Municipalite_Zone9].[Description] [MunicipaliteID_Description]
,[Municipalite_Zone9].[Actif] [MunicipaliteID_Actif]

From [dbo].[Permit] [Permit]
    Left Outer Join [dbo].[Contrat] [Contrat1] On [Permit].[ContratID] = [Contrat1].[ID]
        Left Outer Join [dbo].[Essence] [Essence2] On [Permit].[EssenceID] = [Essence2].[ID]
            Left Outer Join [dbo].[Fournisseur] [Fournisseur3] On [Permit].[TransporteurID] = [Fournisseur3].[ID]
                Left Outer Join [dbo].[Fournisseur] [Fournisseur4] On [Permit].[ProducteurDroitCoupeID] = [Fournisseur4].[ID]
                    Left Outer Join [dbo].[Fournisseur] [Fournisseur5] On [Permit].[ProducteurEntentePaiementID] = [Fournisseur5].[ID]
                        Left Outer Join [dbo].[Lot] [Lot6] On [Permit].[LotID] = [Lot6].[ID]
                            Left Outer Join [dbo].[Fournisseur] [Fournisseur7] On [Permit].[ChargeurID] = [Fournisseur7].[ID]
                                Left Outer Join [dbo].[Municipalite_Zone] [Municipalite_Zone8] On [Permit].[ZoneID] = [Municipalite_Zone8].[ID]
                                    Left Outer Join [dbo].[Municipalite_Zone] [Municipalite_Zone9] On [Permit].[MunicipaliteID] = [Municipalite_Zone9].[MunicipaliteID]

Where

    ((@ID Is Null) Or ([Permit].[ID] = @ID))
And ((@ContratID Is Null) Or ([Permit].[ContratID] = @ContratID))
And ((@EssenceID Is Null) Or ([Permit].[EssenceID] = @EssenceID))
And ((@TransporteurID Is Null) Or ([Permit].[TransporteurID] = @TransporteurID))
And ((@ProducteurDroitCoupeID Is Null) Or ([Permit].[ProducteurDroitCoupeID] = @ProducteurDroitCoupeID))
And ((@ProducteurEntentePaiementID Is Null) Or ([Permit].[ProducteurEntentePaiementID] = @ProducteurEntentePaiementID))
And ((@LotID Is Null) Or ([Permit].[LotID] = @LotID))
And ((@ChargeurID Is Null) Or ([Permit].[ChargeurID] = @ChargeurID))
And ((@ZoneID Is Null) Or ([Permit].[ZoneID] = @ZoneID))
And ((@MunicipaliteID Is Null) Or ([Permit].[MunicipaliteID] = @MunicipaliteID))
)



