CREATE FUNCTION [dbo].[fun_Company_Select]
(
    @CIE int
)
RETURNS TABLE
AS
RETURN
(
    SELECT
        pt.CIE,
        pt.Name,
        pt.Features,
        pt.Archive,
        pt.Created,
        pt.Updated,
        pt.UpdatedBy,
        pt.AcombaPassword,
        pt.AcombaPath,
        pt.AcombaSocietePath,
        pt.AcombaSyncroPath,
        pt.AcombaUserName,
        pt.AcrobatPath,
        pt.AdminPassword,
        pt.AfficherPermit1,
        pt.AfficherPermit2,
        pt.AfficherPermit3,
        pt.AfficherPermit4,
        pt.AnneeCourante,
        pt.AutresRaportsPrinterMarginBottom,
        pt.AutresRaportsPrinterMarginLeft,
        pt.AutresRaportsPrinterMarginRight,
        pt.AutresRaportsPrinterMarginTop,
        pt.CanEditUndeliveredPermits,
        pt.CCEmail,
        pt.CleTriClientNom,
        pt.CopiePermit1,
        pt.CopiePermit2,
        pt.CopiePermit3,
        pt.CopiePermit4,
        pt.DeleteFichePassword,
        pt.EmailPermit1,
        pt.EmailPermit2,
        pt.EmailPermit3,
        pt.EmailPermit4,
        pt.ExcelLanguage,
        pt.FacturesAfficherFraisAutreChargePourTransporteur,
        pt.FacturesAfficherFraisAutresProducteur,
        pt.FacturesAfficherFraisAutresRevenusProducteur,
        pt.FacturesAfficherFraisAutresRevenusTransporteur,
        pt.FacturesAfficherFraisAutresTransporteur,
        pt.FacturesAfficherFraisChargeurProducteur,
        pt.FacturesAfficherFraisChargeurTransporteur,
        pt.FacturesAfficherFraisCompensationDeDeplacement,
        pt.FacturesAfficherSurchargeProducteur,
        pt.FormIcon,
        pt.FormText,
        pt.FournisseurPointerID,
        pt.FromEmail,
        pt.GPVersion,
        pt.HelpFilePath,
        pt.ImprimanteAutresRapports,
        pt.ImprimanteDePermis,
        pt.LivraisonLierTaux,
        pt.LogFile,
        pt.LogoPath,
        pt.MasseContingentVoyageDefaut,
        pt.MasseLimiteDefaut,
        pt.Message_AutorisationDesLivraisons,
        pt.Message_DemandeContingentement,
        pt.MessageImpressionsDeFactures,
        pt.MessageLivraisonNonConforme,
        pt.MessageSpecPermitAnglais,
        pt.MessageSpecPermitFrancais,
        pt.NomDB,
        pt.PermisPrinterMarginBottom,
        pt.PermisPrinterMarginLeft,
        pt.PermisPrinterMarginRight,
        pt.PermisPrinterMarginTop,
        pt.PermisPrintPreview,
        pt.Preleves_NoTPS,
        pt.Preleves_NoTVQ,
        pt.ServeurEmail,
        pt.ShowYearsInPermisListview,
        pt.SuperficieContingenteePourcentageDeduction,
        pt.SuperficieContingenteeSansDeduction,
        pt.Syndicat_CodePostal,
        pt.Syndicat_Fax,
        pt.Syndicat_Nom,
        pt.Syndicat_NomAnglais,
        pt.Syndicat_NomFrancais,
        pt.Syndicat_NoTPS,
        pt.Syndicat_NoTVQ,
        pt.Syndicat_Rue,
        pt.Syndicat_Telephone,
        pt.Syndicat_Ville,
        pt.SyndicatOuOffice,
        pt.TakeAcombaBackup,
        pt.TakeSQLBackup,
        pt.TempsEntreLesBackupsAutomatiques,
        pt.TimeoutSQL,
        pt.TypePermis,
        pt.TypePermis1,
        pt.TypePermis1Anglais,
        pt.TypePermis1Francais,
        pt.TypePermis2,
        pt.TypePermis2Anglais,
        pt.TypePermis2Francais,
        pt.TypePermis3,
        pt.TypePermis3Anglais,
        pt.TypePermis3Francais,
        pt.TypePermis4,
        pt.TypePermis4Anglais,
        pt.TypePermis4Francais,
        pt.UpdateOtherDataBase,
        pt.UtiliseLeSychronisateurDirect,
        pt.UtiliserLesNomsDeMachineDansLeNomDePrinter,
        pt.UtiliserLotsContingentes,
        pt.XLSTemplatesPath,
        pt.Fournisseur_PlanConjoint,
        lut1.Nom [Fournisseur_PlanConjoint_Text],
        pt.Fournisseur_Surcharge,
        lut2.Nom [Fournisseur_Surcharge_Text],
        pt.Compte_Paiements,
        lut3.Description [Compte_Paiements_Text],
        pt.Compte_ARecevoir,
        lut4.Description [Compte_ARecevoir_Text],
        pt.Compte_APayer,
        lut5.Description [Compte_APayer_Text],
        pt.Compte_DuAuxProducteurs,
        lut6.Description [Compte_DuAuxProducteurs_Text],
        pt.Compte_TPSpercues,
        lut7.Description [Compte_TPSpercues_Text],
        pt.Compte_TPSpayees,
        lut8.Description [Compte_TPSpayees_Text],
        pt.Compte_TVQpercues,
        lut9.Description [Compte_TVQpercues_Text],
        pt.Compte_TVQpayees,
        lut10.Description [Compte_TVQpayees_Text],
        pt.Taux_TPS,
        pt.Taux_TVQ,
        pt.Fournisseur_Fond_Roulement,
        lut11.Nom [Fournisseur_Fond_Roulement_Text],
        pt.Fournisseur_Fond_Forestier,
        lut12.Nom [Fournisseur_Fond_Forestier_Text],
        pt.Fournisseur_Preleve_Divers,
        lut13.Nom [Fournisseur_Preleve_Divers_Text]
    FROM [dbo].[Company] pt
    LEFT OUTER JOIN Fournisseur lut1 ON lut1.ID = pt.Fournisseur_PlanConjoint
    LEFT OUTER JOIN Fournisseur lut2 ON lut2.ID = pt.Fournisseur_Surcharge
    LEFT OUTER JOIN Compte lut3 ON lut3.ID = pt.Compte_Paiements
    LEFT OUTER JOIN Compte lut4 ON lut4.ID = pt.Compte_ARecevoir
    LEFT OUTER JOIN Compte lut5 ON lut5.ID = pt.Compte_APayer
    LEFT OUTER JOIN Compte lut6 ON lut6.ID = pt.Compte_DuAuxProducteurs
    LEFT OUTER JOIN Compte lut7 ON lut7.ID = pt.Compte_TPSpercues
    LEFT OUTER JOIN Compte lut8 ON lut8.ID = pt.Compte_TPSpayees
    LEFT OUTER JOIN Compte lut9 ON lut9.ID = pt.Compte_TVQpercues
    LEFT OUTER JOIN Compte lut10 ON lut10.ID = pt.Compte_TVQpayees
    LEFT OUTER JOIN Fournisseur lut11 ON lut11.ID = pt.Fournisseur_Fond_Roulement
    LEFT OUTER JOIN Fournisseur lut12 ON lut12.ID = pt.Fournisseur_Fond_Forestier
    LEFT OUTER JOIN Fournisseur lut13 ON lut13.ID = pt.Fournisseur_Preleve_Divers
    WHERE pt.CIE = @CIE
)