CREATE PROCEDURE [dbo].[Fournisseur_New]
(
    @_uid int
)
AS
BEGIN
SET NOCOUNT ON
;
DECLARE @returnTable TABLE
(
    [CleTri] varchar(15) NULL,
    [Nom] varchar(40) NULL,
    [AuSoinsDe] varchar(30) NULL,
    [Rue] varchar(30) NULL,
    [Ville] varchar(30) NULL,
    [PaysID] varchar(2) NULL,
    [PaysID_Text] nvarchar(50) NULL,
    [Code_postal] varchar(7) NULL,
    [Telephone] varchar(12) NULL,
    [Telephone_Poste] varchar(4) NULL,
    [Telecopieur] varchar(12) NULL,
    [Telephone2] varchar(12) NULL,
    [Telephone2_Desc] varchar(20) NULL,
    [Telephone2_Poste] varchar(4) NULL,
    [Telephone3] varchar(12) NULL,
    [Telephone3_Desc] varchar(20) NULL,
    [Telephone3_Poste] varchar(4) NULL,
    [No_membre] varchar(10) NULL,
    [Resident] char(1) NULL,
    [Email] varchar(80) NULL,
    [WWW] varchar(80) NULL,
    [Commentaires] varchar(255) NULL,
    [AfficherCommentaires] bit NULL,
    [DepotDirect] bit NULL,
    [InstitutionBanquaireID] varchar(3) NULL,
    [InstitutionBanquaireID_Text] nvarchar(50) NULL,
    [Banque_transit] varchar(5) NULL,
    [Banque_folio] varchar(12) NULL,
    [No_TPS] varchar(25) NULL,
    [No_TVQ] varchar(25) NULL,
    [PayerA] bit NULL,
    [PayerAID] varchar(15) NULL,
    [Statut] varchar(50) NULL,
    [Rep_Nom] varchar(30) NULL,
    [Rep_Telephone] varchar(12) NULL,
    [Rep_Telephone_Poste] varchar(4) NULL,
    [Rep_Email] varchar(80) NULL,
    [EnAnglais] bit NULL,
    [Actif] bit NULL,
    [MRCProducteurID] int NULL,
    [PaiementManuel] bit NULL,
    [Journal] bit NULL,
    [RecoitTPS] bit NULL,
    [RecoitTVQ] bit NULL,
    [ModifierTrigger] bit NULL,
    [IsProducteur] bit NULL,
    [IsTransporteur] bit NULL,
    [IsChargeur] bit NULL,
    [IsAutre] bit NULL,
    [AfficherCommentairesSurPermit] bit NOT NULL,
    [PasEmissionPermis] bit NULL,
    [Generique] bit NULL,
    [Membre_OGC] bit NULL,
    [InscritTPS] bit NULL,
    [InscritTVQ] bit NULL,
    [IsOGC] bit NOT NULL,
    [Rep2_Nom] varchar(80) NULL,
    [Rep2_Telephone] varchar(12) NULL,
    [Rep2_Telephone_Poste] varchar(4) NULL,
    [Rep2_Email] varchar(80) NULL,
    [Rep2_Commentaires] varchar(255) NULL
)
;
INSERT @returnTable
SELECT
    NULL [CleTri],
    NULL [Nom],
    NULL [AuSoinsDe],
    NULL [Rue],
    NULL [Ville],
    NULL [PaysID],
    '' [PaysID_Text],
    NULL [Code_postal],
    NULL [Telephone],
    NULL [Telephone_Poste],
    NULL [Telecopieur],
    NULL [Telephone2],
    NULL [Telephone2_Desc],
    NULL [Telephone2_Poste],
    NULL [Telephone3],
    NULL [Telephone3_Desc],
    NULL [Telephone3_Poste],
    NULL [No_membre],
    NULL [Resident],
    NULL [Email],
    NULL [WWW],
    NULL [Commentaires],
    NULL [AfficherCommentaires],
    NULL [DepotDirect],
    NULL [InstitutionBanquaireID],
    '' [InstitutionBanquaireID_Text],
    NULL [Banque_transit],
    NULL [Banque_folio],
    NULL [No_TPS],
    NULL [No_TVQ],
    NULL [PayerA],
    NULL [PayerAID],
    NULL [Statut],
    NULL [Rep_Nom],
    NULL [Rep_Telephone],
    NULL [Rep_Telephone_Poste],
    NULL [Rep_Email],
    NULL [EnAnglais],
    NULL [Actif],
    NULL [MRCProducteurID],
    NULL [PaiementManuel],
    NULL [Journal],
    NULL [RecoitTPS],
    NULL [RecoitTVQ],
    NULL [ModifierTrigger],
    NULL [IsProducteur],
    NULL [IsTransporteur],
    NULL [IsChargeur],
    NULL [IsAutre],
    0 [AfficherCommentairesSurPermit],
    NULL [PasEmissionPermis],
    NULL [Generique],
    NULL [Membre_OGC],
    NULL [InscritTPS],
    NULL [InscritTVQ],
    0 [IsOGC],
    NULL [Rep2_Nom],
    NULL [Rep2_Telephone],
    NULL [Rep2_Telephone_Poste],
    NULL [Rep2_Email],
    NULL [Rep2_Commentaires] 
;
SELECT * FROM @returnTable;
;
END
