

Create Procedure [spS_FactureFournisseur_Full]

/*
Retrieve specific records from the [FactureFournisseur] table, as well as all its foreign tables, depending on the input parameters you supply:
	[TypeFactureFournisseur] (via [TypeFactureFournisseur])
	[TypeFacture] (via [TypeFacture])
	[TypeInvoiceAcomba] (via [TypeInvoiceAcomba])
	[Fournisseur] (via [FournisseurID])
	[Fournisseur] (via [PayerAID])
*/

(
 @ID [int] = Null -- for [FactureFournisseur].[ID] column
,@TypeFactureFournisseur [char](1) = Null -- for [FactureFournisseur].[TypeFactureFournisseur] column
,@TypeFacture [char](1) = Null -- for [FactureFournisseur].[TypeFacture] column
,@TypeInvoiceAcomba [int] = Null -- for [FactureFournisseur].[TypeInvoiceAcomba] column
,@FournisseurID [varchar](15) = Null -- for [FactureFournisseur].[FournisseurID] column
,@PayerAID [varchar](15) = Null -- for [FactureFournisseur].[PayerAID] column
,@ReturnXML [bit] = 0 -- Indicates if we want to get back XML content instead of normal resultset (@ReturnXML = 1 to get XML back)
)

-- Returns the number of records found

As


--	IMPORTANT:
--	Changes to this SQL code may cause incorrect behavior
--	and will be lost if the code is regenerated. 


If @ReturnXML Is Null
	Set @ReturnXML = 0

If @ReturnXML = 0
	Begin
		Select

		 [FactureFournisseur_Records].[ID]
		,[FactureFournisseur_Records].[NoFacture]
		,[FactureFournisseur_Records].[DateFacture]
		,[FactureFournisseur_Records].[Annee]
		,[FactureFournisseur_Records].[TypeFactureFournisseur]
		,[FactureFournisseur_Records].[TypeFacture]
		,[FactureFournisseur_Records].[TypeInvoiceAcomba]
		,[FactureFournisseur_Records].[FournisseurID]
		,[FactureFournisseur_Records].[PayerAID]
		,[FactureFournisseur_Records].[Montant_Total]
		,[FactureFournisseur_Records].[Montant_TPS]
		,[FactureFournisseur_Records].[Montant_TVQ]
		,[FactureFournisseur_Records].[Description]
		,[FactureFournisseur_Records].[Status]
		,[FactureFournisseur_Records].[StatusDescription]
		,[FactureFournisseur_Records].[NumeroCheque]
		,[FactureFournisseur_Records].[NumeroPaiement]
		,[FactureFournisseur_Records].[NumeroPaiementUnique]
		,[FactureFournisseur_Records].[DateFactureAcomba]
		,[FactureFournisseur_Records].[DatePaiementAcomba]
		,[FactureFournisseur_Records].[TypeFactureFournisseur_ID]
		,[FactureFournisseur_Records].[TypeFactureFournisseur_Description]
		,[FactureFournisseur_Records].[TypeFacture_ID]
		,[FactureFournisseur_Records].[TypeFacture_Description]
		,[FactureFournisseur_Records].[TypeFacture_FactureDescriptionMask]
		,[FactureFournisseur_Records].[TypeInvoiceAcomba_ID]
		,[FactureFournisseur_Records].[TypeInvoiceAcomba_Description]
		,[FactureFournisseur_Records].[FournisseurID_ID]
		,[FactureFournisseur_Records].[FournisseurID_CleTri]
		,[FactureFournisseur_Records].[FournisseurID_Nom]
		,[FactureFournisseur_Records].[FournisseurID_AuSoinsDe]
		,[FactureFournisseur_Records].[FournisseurID_Rue]
		,[FactureFournisseur_Records].[FournisseurID_Ville]
		,[FactureFournisseur_Records].[FournisseurID_PaysID]
		,[FactureFournisseur_Records].[FournisseurID_Code_postal]
		,[FactureFournisseur_Records].[FournisseurID_Telephone]
		,[FactureFournisseur_Records].[FournisseurID_Telephone_Poste]
		,[FactureFournisseur_Records].[FournisseurID_Telecopieur]
		,[FactureFournisseur_Records].[FournisseurID_Telephone2]
		,[FactureFournisseur_Records].[FournisseurID_Telephone2_Desc]
		,[FactureFournisseur_Records].[FournisseurID_Telephone2_Poste]
		,[FactureFournisseur_Records].[FournisseurID_Telephone3]
		,[FactureFournisseur_Records].[FournisseurID_Telephone3_Desc]
		,[FactureFournisseur_Records].[FournisseurID_Telephone3_Poste]
		,[FactureFournisseur_Records].[FournisseurID_No_membre]
		,[FactureFournisseur_Records].[FournisseurID_Resident]
		,[FactureFournisseur_Records].[FournisseurID_Email]
		,[FactureFournisseur_Records].[FournisseurID_WWW]
		,[FactureFournisseur_Records].[FournisseurID_Commentaires]
		,[FactureFournisseur_Records].[FournisseurID_AfficherCommentaires]
		,[FactureFournisseur_Records].[FournisseurID_DepotDirect]
		,[FactureFournisseur_Records].[FournisseurID_InstitutionBanquaireID]
		,[FactureFournisseur_Records].[FournisseurID_Banque_transit]
		,[FactureFournisseur_Records].[FournisseurID_Banque_folio]
		,[FactureFournisseur_Records].[FournisseurID_No_TPS]
		,[FactureFournisseur_Records].[FournisseurID_No_TVQ]
		,[FactureFournisseur_Records].[FournisseurID_PayerA]
		,[FactureFournisseur_Records].[FournisseurID_PayerAID]
		,[FactureFournisseur_Records].[FournisseurID_Statut]
		,[FactureFournisseur_Records].[FournisseurID_Rep_Nom]
		,[FactureFournisseur_Records].[FournisseurID_Rep_Telephone]
		,[FactureFournisseur_Records].[FournisseurID_Rep_Telephone_Poste]
		,[FactureFournisseur_Records].[FournisseurID_Rep_Email]
		,[FactureFournisseur_Records].[FournisseurID_EnAnglais]
		,[FactureFournisseur_Records].[FournisseurID_Actif]
		,[FactureFournisseur_Records].[FournisseurID_MRCProducteurID]
		,[FactureFournisseur_Records].[FournisseurID_PaiementManuel]
		,[FactureFournisseur_Records].[FournisseurID_Journal]
		,[FactureFournisseur_Records].[FournisseurID_RecoitTPS]
		,[FactureFournisseur_Records].[FournisseurID_RecoitTVQ]
		,[FactureFournisseur_Records].[FournisseurID_ModifierTrigger]
		,[FactureFournisseur_Records].[FournisseurID_IsProducteur]
		,[FactureFournisseur_Records].[FournisseurID_IsTransporteur]
		,[FactureFournisseur_Records].[FournisseurID_IsChargeur]
		,[FactureFournisseur_Records].[FournisseurID_IsAutre]
		,[FactureFournisseur_Records].[FournisseurID_AfficherCommentairesSurPermit]
		,[FactureFournisseur_Records].[FournisseurID_PasEmissionPermis]
		,[FactureFournisseur_Records].[FournisseurID_Generique]
		,[FactureFournisseur_Records].[PayerAID_ID]
		,[FactureFournisseur_Records].[PayerAID_CleTri]
		,[FactureFournisseur_Records].[PayerAID_Nom]
		,[FactureFournisseur_Records].[PayerAID_AuSoinsDe]
		,[FactureFournisseur_Records].[PayerAID_Rue]
		,[FactureFournisseur_Records].[PayerAID_Ville]
		,[FactureFournisseur_Records].[PayerAID_PaysID]
		,[FactureFournisseur_Records].[PayerAID_Code_postal]
		,[FactureFournisseur_Records].[PayerAID_Telephone]
		,[FactureFournisseur_Records].[PayerAID_Telephone_Poste]
		,[FactureFournisseur_Records].[PayerAID_Telecopieur]
		,[FactureFournisseur_Records].[PayerAID_Telephone2]
		,[FactureFournisseur_Records].[PayerAID_Telephone2_Desc]
		,[FactureFournisseur_Records].[PayerAID_Telephone2_Poste]
		,[FactureFournisseur_Records].[PayerAID_Telephone3]
		,[FactureFournisseur_Records].[PayerAID_Telephone3_Desc]
		,[FactureFournisseur_Records].[PayerAID_Telephone3_Poste]
		,[FactureFournisseur_Records].[PayerAID_No_membre]
		,[FactureFournisseur_Records].[PayerAID_Resident]
		,[FactureFournisseur_Records].[PayerAID_Email]
		,[FactureFournisseur_Records].[PayerAID_WWW]
		,[FactureFournisseur_Records].[PayerAID_Commentaires]
		,[FactureFournisseur_Records].[PayerAID_AfficherCommentaires]
		,[FactureFournisseur_Records].[PayerAID_DepotDirect]
		,[FactureFournisseur_Records].[PayerAID_InstitutionBanquaireID]
		,[FactureFournisseur_Records].[PayerAID_Banque_transit]
		,[FactureFournisseur_Records].[PayerAID_Banque_folio]
		,[FactureFournisseur_Records].[PayerAID_No_TPS]
		,[FactureFournisseur_Records].[PayerAID_No_TVQ]
		,[FactureFournisseur_Records].[PayerAID_PayerA]
		,[FactureFournisseur_Records].[PayerAID_PayerAID]
		,[FactureFournisseur_Records].[PayerAID_Statut]
		,[FactureFournisseur_Records].[PayerAID_Rep_Nom]
		,[FactureFournisseur_Records].[PayerAID_Rep_Telephone]
		,[FactureFournisseur_Records].[PayerAID_Rep_Telephone_Poste]
		,[FactureFournisseur_Records].[PayerAID_Rep_Email]
		,[FactureFournisseur_Records].[PayerAID_EnAnglais]
		,[FactureFournisseur_Records].[PayerAID_Actif]
		,[FactureFournisseur_Records].[PayerAID_MRCProducteurID]
		,[FactureFournisseur_Records].[PayerAID_PaiementManuel]
		,[FactureFournisseur_Records].[PayerAID_Journal]
		,[FactureFournisseur_Records].[PayerAID_RecoitTPS]
		,[FactureFournisseur_Records].[PayerAID_RecoitTVQ]
		,[FactureFournisseur_Records].[PayerAID_ModifierTrigger]
		,[FactureFournisseur_Records].[PayerAID_IsProducteur]
		,[FactureFournisseur_Records].[PayerAID_IsTransporteur]
		,[FactureFournisseur_Records].[PayerAID_IsChargeur]
		,[FactureFournisseur_Records].[PayerAID_IsAutre]
		,[FactureFournisseur_Records].[PayerAID_AfficherCommentairesSurPermit]
		,[FactureFournisseur_Records].[PayerAID_PasEmissionPermis]
		,[FactureFournisseur_Records].[PayerAID_Generique]

		From [fnFactureFournisseur_Full](@ID, @TypeFactureFournisseur, @TypeFacture, @TypeInvoiceAcomba, @FournisseurID, @PayerAID) As [FactureFournisseur_Records]
	End

Else

	Begin
		Select

		 [FactureFournisseur_Records].[ID]
		,[FactureFournisseur_Records].[NoFacture]
		,[FactureFournisseur_Records].[DateFacture]
		,[FactureFournisseur_Records].[Annee]
		,[FactureFournisseur_Records].[TypeFactureFournisseur]
		,[FactureFournisseur_Records].[TypeFacture]
		,[FactureFournisseur_Records].[TypeInvoiceAcomba]
		,[FactureFournisseur_Records].[FournisseurID]
		,[FactureFournisseur_Records].[PayerAID]
		,[FactureFournisseur_Records].[Montant_Total]
		,[FactureFournisseur_Records].[Montant_TPS]
		,[FactureFournisseur_Records].[Montant_TVQ]
		,[FactureFournisseur_Records].[Description]
		,[FactureFournisseur_Records].[Status]
		,[FactureFournisseur_Records].[StatusDescription]
		,[FactureFournisseur_Records].[NumeroCheque]
		,[FactureFournisseur_Records].[NumeroPaiement]
		,[FactureFournisseur_Records].[NumeroPaiementUnique]
		,[FactureFournisseur_Records].[DateFactureAcomba]
		,[FactureFournisseur_Records].[DatePaiementAcomba]
		,[FactureFournisseur_Records].[TypeFactureFournisseur_ID]
		,[FactureFournisseur_Records].[TypeFactureFournisseur_Description]
		,[FactureFournisseur_Records].[TypeFacture_ID]
		,[FactureFournisseur_Records].[TypeFacture_Description]
		,[FactureFournisseur_Records].[TypeFacture_FactureDescriptionMask]
		,[FactureFournisseur_Records].[TypeInvoiceAcomba_ID]
		,[FactureFournisseur_Records].[TypeInvoiceAcomba_Description]
		,[FactureFournisseur_Records].[FournisseurID_ID]
		,[FactureFournisseur_Records].[FournisseurID_CleTri]
		,[FactureFournisseur_Records].[FournisseurID_Nom]
		,[FactureFournisseur_Records].[FournisseurID_AuSoinsDe]
		,[FactureFournisseur_Records].[FournisseurID_Rue]
		,[FactureFournisseur_Records].[FournisseurID_Ville]
		,[FactureFournisseur_Records].[FournisseurID_PaysID]
		,[FactureFournisseur_Records].[FournisseurID_Code_postal]
		,[FactureFournisseur_Records].[FournisseurID_Telephone]
		,[FactureFournisseur_Records].[FournisseurID_Telephone_Poste]
		,[FactureFournisseur_Records].[FournisseurID_Telecopieur]
		,[FactureFournisseur_Records].[FournisseurID_Telephone2]
		,[FactureFournisseur_Records].[FournisseurID_Telephone2_Desc]
		,[FactureFournisseur_Records].[FournisseurID_Telephone2_Poste]
		,[FactureFournisseur_Records].[FournisseurID_Telephone3]
		,[FactureFournisseur_Records].[FournisseurID_Telephone3_Desc]
		,[FactureFournisseur_Records].[FournisseurID_Telephone3_Poste]
		,[FactureFournisseur_Records].[FournisseurID_No_membre]
		,[FactureFournisseur_Records].[FournisseurID_Resident]
		,[FactureFournisseur_Records].[FournisseurID_Email]
		,[FactureFournisseur_Records].[FournisseurID_WWW]
		,[FactureFournisseur_Records].[FournisseurID_Commentaires]
		,[FactureFournisseur_Records].[FournisseurID_AfficherCommentaires]
		,[FactureFournisseur_Records].[FournisseurID_DepotDirect]
		,[FactureFournisseur_Records].[FournisseurID_InstitutionBanquaireID]
		,[FactureFournisseur_Records].[FournisseurID_Banque_transit]
		,[FactureFournisseur_Records].[FournisseurID_Banque_folio]
		,[FactureFournisseur_Records].[FournisseurID_No_TPS]
		,[FactureFournisseur_Records].[FournisseurID_No_TVQ]
		,[FactureFournisseur_Records].[FournisseurID_PayerA]
		,[FactureFournisseur_Records].[FournisseurID_PayerAID]
		,[FactureFournisseur_Records].[FournisseurID_Statut]
		,[FactureFournisseur_Records].[FournisseurID_Rep_Nom]
		,[FactureFournisseur_Records].[FournisseurID_Rep_Telephone]
		,[FactureFournisseur_Records].[FournisseurID_Rep_Telephone_Poste]
		,[FactureFournisseur_Records].[FournisseurID_Rep_Email]
		,[FactureFournisseur_Records].[FournisseurID_EnAnglais]
		,[FactureFournisseur_Records].[FournisseurID_Actif]
		,[FactureFournisseur_Records].[FournisseurID_MRCProducteurID]
		,[FactureFournisseur_Records].[FournisseurID_PaiementManuel]
		,[FactureFournisseur_Records].[FournisseurID_Journal]
		,[FactureFournisseur_Records].[FournisseurID_RecoitTPS]
		,[FactureFournisseur_Records].[FournisseurID_RecoitTVQ]
		,[FactureFournisseur_Records].[FournisseurID_ModifierTrigger]
		,[FactureFournisseur_Records].[FournisseurID_IsProducteur]
		,[FactureFournisseur_Records].[FournisseurID_IsTransporteur]
		,[FactureFournisseur_Records].[FournisseurID_IsChargeur]
		,[FactureFournisseur_Records].[FournisseurID_IsAutre]
		,[FactureFournisseur_Records].[FournisseurID_AfficherCommentairesSurPermit]
		,[FactureFournisseur_Records].[FournisseurID_PasEmissionPermis]
		,[FactureFournisseur_Records].[FournisseurID_Generique]
		,[FactureFournisseur_Records].[PayerAID_ID]
		,[FactureFournisseur_Records].[PayerAID_CleTri]
		,[FactureFournisseur_Records].[PayerAID_Nom]
		,[FactureFournisseur_Records].[PayerAID_AuSoinsDe]
		,[FactureFournisseur_Records].[PayerAID_Rue]
		,[FactureFournisseur_Records].[PayerAID_Ville]
		,[FactureFournisseur_Records].[PayerAID_PaysID]
		,[FactureFournisseur_Records].[PayerAID_Code_postal]
		,[FactureFournisseur_Records].[PayerAID_Telephone]
		,[FactureFournisseur_Records].[PayerAID_Telephone_Poste]
		,[FactureFournisseur_Records].[PayerAID_Telecopieur]
		,[FactureFournisseur_Records].[PayerAID_Telephone2]
		,[FactureFournisseur_Records].[PayerAID_Telephone2_Desc]
		,[FactureFournisseur_Records].[PayerAID_Telephone2_Poste]
		,[FactureFournisseur_Records].[PayerAID_Telephone3]
		,[FactureFournisseur_Records].[PayerAID_Telephone3_Desc]
		,[FactureFournisseur_Records].[PayerAID_Telephone3_Poste]
		,[FactureFournisseur_Records].[PayerAID_No_membre]
		,[FactureFournisseur_Records].[PayerAID_Resident]
		,[FactureFournisseur_Records].[PayerAID_Email]
		,[FactureFournisseur_Records].[PayerAID_WWW]
		,[FactureFournisseur_Records].[PayerAID_Commentaires]
		,[FactureFournisseur_Records].[PayerAID_AfficherCommentaires]
		,[FactureFournisseur_Records].[PayerAID_DepotDirect]
		,[FactureFournisseur_Records].[PayerAID_InstitutionBanquaireID]
		,[FactureFournisseur_Records].[PayerAID_Banque_transit]
		,[FactureFournisseur_Records].[PayerAID_Banque_folio]
		,[FactureFournisseur_Records].[PayerAID_No_TPS]
		,[FactureFournisseur_Records].[PayerAID_No_TVQ]
		,[FactureFournisseur_Records].[PayerAID_PayerA]
		,[FactureFournisseur_Records].[PayerAID_PayerAID]
		,[FactureFournisseur_Records].[PayerAID_Statut]
		,[FactureFournisseur_Records].[PayerAID_Rep_Nom]
		,[FactureFournisseur_Records].[PayerAID_Rep_Telephone]
		,[FactureFournisseur_Records].[PayerAID_Rep_Telephone_Poste]
		,[FactureFournisseur_Records].[PayerAID_Rep_Email]
		,[FactureFournisseur_Records].[PayerAID_EnAnglais]
		,[FactureFournisseur_Records].[PayerAID_Actif]
		,[FactureFournisseur_Records].[PayerAID_MRCProducteurID]
		,[FactureFournisseur_Records].[PayerAID_PaiementManuel]
		,[FactureFournisseur_Records].[PayerAID_Journal]
		,[FactureFournisseur_Records].[PayerAID_RecoitTPS]
		,[FactureFournisseur_Records].[PayerAID_RecoitTVQ]
		,[FactureFournisseur_Records].[PayerAID_ModifierTrigger]
		,[FactureFournisseur_Records].[PayerAID_IsProducteur]
		,[FactureFournisseur_Records].[PayerAID_IsTransporteur]
		,[FactureFournisseur_Records].[PayerAID_IsChargeur]
		,[FactureFournisseur_Records].[PayerAID_IsAutre]
		,[FactureFournisseur_Records].[PayerAID_AfficherCommentairesSurPermit]
		,[FactureFournisseur_Records].[PayerAID_PasEmissionPermis]
		,[FactureFournisseur_Records].[PayerAID_Generique]

		From [fnFactureFournisseur_Full](@ID, @TypeFactureFournisseur, @TypeFacture, @TypeInvoiceAcomba, @FournisseurID, @PayerAID) As [FactureFournisseur_Records]

		For XML Auto, Elements, XMLData, BINARY BASE64
	End

Return(@@RowCount)


