

Create Procedure [spS_AjustementCalcule_Transporteur_Full]

/*
Retrieve specific records from the [AjustementCalcule_Transporteur] table, as well as all its foreign tables, depending on the input parameters you supply:
	[Ajustement_Transporteur] (via [AjustementID])
	[Ajustement_Transporteur] (via [UniteID])
	[Ajustement_Transporteur] (via [MunicipaliteID])
	[Livraison] (via [LivraisonID])
	[Fournisseur] (via [TransporteurID])
	[FactureFournisseur] (via [FactureID])
	[Ajustement_Transporteur] (via [ZoneID])
*/

(
 @ID [int] = Null -- for [AjustementCalcule_Transporteur].[ID] column
,@AjustementID [int] = Null -- for [AjustementCalcule_Transporteur].[AjustementID] column
,@UniteID [varchar](6) = Null -- for [AjustementCalcule_Transporteur].[UniteID] column
,@MunicipaliteID [varchar](6) = Null -- for [AjustementCalcule_Transporteur].[MunicipaliteID] column
,@LivraisonID [int] = Null -- for [AjustementCalcule_Transporteur].[LivraisonID] column
,@TransporteurID [varchar](15) = Null -- for [AjustementCalcule_Transporteur].[TransporteurID] column
,@FactureID [int] = Null -- for [AjustementCalcule_Transporteur].[FactureID] column
,@ZoneID [varchar](2) = Null -- for [AjustementCalcule_Transporteur].[ZoneID] column
,@ReturnXML [bit] = 0 -- Indicates if we want to get back XML content instead of normal resultset (@ReturnXML = 1 to get XML back)
)

-- Returns the number of records found

As


--	IMPORTANT:
--	Changes to this SQL code may cause incorrect behavior
--	and will be lost if the code is regenerated. 


If @ReturnXML Is Null
	Set @ReturnXML = 0

If @ReturnXML = 0
	Begin
		Select

		 [AjustementCalcule_Transporteur_Records].[ID]
		,[AjustementCalcule_Transporteur_Records].[DateCalcul]
		,[AjustementCalcule_Transporteur_Records].[AjustementID]
		,[AjustementCalcule_Transporteur_Records].[UniteID]
		,[AjustementCalcule_Transporteur_Records].[MunicipaliteID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID]
		,[AjustementCalcule_Transporteur_Records].[Volume]
		,[AjustementCalcule_Transporteur_Records].[Taux]
		,[AjustementCalcule_Transporteur_Records].[Montant]
		,[AjustementCalcule_Transporteur_Records].[Facture]
		,[AjustementCalcule_Transporteur_Records].[FactureID]
		,[AjustementCalcule_Transporteur_Records].[ErreurCalcul]
		,[AjustementCalcule_Transporteur_Records].[ErreurDescription]
		,[AjustementCalcule_Transporteur_Records].[ZoneID]
		,[AjustementCalcule_Transporteur_Records].[AjustementID_AjustementID]
		,[AjustementCalcule_Transporteur_Records].[AjustementID_UniteID]
		,[AjustementCalcule_Transporteur_Records].[AjustementID_MunicipaliteID]
		,[AjustementCalcule_Transporteur_Records].[AjustementID_ContratID]
		,[AjustementCalcule_Transporteur_Records].[AjustementID_Taux_transporteur]
		,[AjustementCalcule_Transporteur_Records].[AjustementID_Date_Modification]
		,[AjustementCalcule_Transporteur_Records].[AjustementID_ZoneID]
		,[AjustementCalcule_Transporteur_Records].[UniteID_AjustementID]
		,[AjustementCalcule_Transporteur_Records].[UniteID_UniteID]
		,[AjustementCalcule_Transporteur_Records].[UniteID_MunicipaliteID]
		,[AjustementCalcule_Transporteur_Records].[UniteID_ContratID]
		,[AjustementCalcule_Transporteur_Records].[UniteID_Taux_transporteur]
		,[AjustementCalcule_Transporteur_Records].[UniteID_Date_Modification]
		,[AjustementCalcule_Transporteur_Records].[UniteID_ZoneID]
		,[AjustementCalcule_Transporteur_Records].[MunicipaliteID_AjustementID]
		,[AjustementCalcule_Transporteur_Records].[MunicipaliteID_UniteID]
		,[AjustementCalcule_Transporteur_Records].[MunicipaliteID_MunicipaliteID]
		,[AjustementCalcule_Transporteur_Records].[MunicipaliteID_ContratID]
		,[AjustementCalcule_Transporteur_Records].[MunicipaliteID_Taux_transporteur]
		,[AjustementCalcule_Transporteur_Records].[MunicipaliteID_Date_Modification]
		,[AjustementCalcule_Transporteur_Records].[MunicipaliteID_ZoneID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_ID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_DateLivraison]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_DatePaye]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_ContratID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_UniteMesureID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_EssenceID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Sciage]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_NumeroFactureUsine]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_DroitCoupeID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_EntentePaiementID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_TransporteurID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_VR]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_MasseLimite]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_VolumeBrut]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_VolumeTare]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_VolumeTransporte]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_VolumeSurcharge]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_VolumeAPayer]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Annee]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Periode]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_DateCalcul]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Taux_Transporteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_Transporteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_Usine]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_Producteur1]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_Producteur2]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_Preleve_Plan_Conjoint]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_Preleve_Fond_Roulement]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_Preleve_Fond_Forestier]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_Preleve_Divers]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_Surcharge]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_MiseEnCommun]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Facture]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Producteur1_FactureID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Producteur2_FactureID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Transporteur_FactureID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Usine_FactureID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_ErreurCalcul]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_ErreurDescription]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_LotID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Taux_Transporteur_Override]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_PaieTransporteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_VolumeSurcharge_Override]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_SurchargeManuel]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Code]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_NombrePermis]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_ZoneID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_MunicipaliteID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_ChargeurID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_Chargeur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_ChargeurAuProducteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_ChargeurAuTransporteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_AutresAuProducteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_AutresAuProducteurDescription]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_AutresAuTransporteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_AutresAuTransporteurDescription]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_CompensationDeDeplacement]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Chargeur_FactureID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Commentaires_Producteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Commentaires_Transporteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Commentaires_Chargeur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_TauxChargeurAuProducteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_TauxChargeurAuTransporteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_AutresRevenusTransporteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_AutresRevenusTransporteurDescription]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_AutresRevenusProducteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_AutresRevenusProducteurDescription]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_SurchargeProducteur]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_ID]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_CleTri]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Nom]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_AuSoinsDe]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Rue]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Ville]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_PaysID]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Code_postal]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Telephone]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Telephone_Poste]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Telecopieur]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Telephone2]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Telephone2_Desc]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Telephone2_Poste]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Telephone3]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Telephone3_Desc]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Telephone3_Poste]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_No_membre]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Resident]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Email]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_WWW]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Commentaires]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_AfficherCommentaires]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_DepotDirect]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_InstitutionBanquaireID]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Banque_transit]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Banque_folio]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_No_TPS]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_No_TVQ]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_PayerA]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_PayerAID]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Statut]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Rep_Nom]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Rep_Telephone]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Rep_Telephone_Poste]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Rep_Email]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_EnAnglais]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Actif]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_MRCProducteurID]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_PaiementManuel]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Journal]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_RecoitTPS]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_RecoitTVQ]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_ModifierTrigger]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_IsProducteur]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_IsTransporteur]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_IsChargeur]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_IsAutre]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_AfficherCommentairesSurPermit]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_PasEmissionPermis]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Generique]
		,[AjustementCalcule_Transporteur_Records].[FactureID_ID]
		,[AjustementCalcule_Transporteur_Records].[FactureID_NoFacture]
		,[AjustementCalcule_Transporteur_Records].[FactureID_DateFacture]
		,[AjustementCalcule_Transporteur_Records].[FactureID_Annee]
		,[AjustementCalcule_Transporteur_Records].[FactureID_TypeFactureFournisseur]
		,[AjustementCalcule_Transporteur_Records].[FactureID_TypeFacture]
		,[AjustementCalcule_Transporteur_Records].[FactureID_TypeInvoiceAcomba]
		,[AjustementCalcule_Transporteur_Records].[FactureID_FournisseurID]
		,[AjustementCalcule_Transporteur_Records].[FactureID_PayerAID]
		,[AjustementCalcule_Transporteur_Records].[FactureID_Montant_Total]
		,[AjustementCalcule_Transporteur_Records].[FactureID_Montant_TPS]
		,[AjustementCalcule_Transporteur_Records].[FactureID_Montant_TVQ]
		,[AjustementCalcule_Transporteur_Records].[FactureID_Description]
		,[AjustementCalcule_Transporteur_Records].[FactureID_Status]
		,[AjustementCalcule_Transporteur_Records].[FactureID_StatusDescription]
		,[AjustementCalcule_Transporteur_Records].[FactureID_NumeroCheque]
		,[AjustementCalcule_Transporteur_Records].[FactureID_NumeroPaiement]
		,[AjustementCalcule_Transporteur_Records].[FactureID_NumeroPaiementUnique]
		,[AjustementCalcule_Transporteur_Records].[FactureID_DateFactureAcomba]
		,[AjustementCalcule_Transporteur_Records].[FactureID_DatePaiementAcomba]
		,[AjustementCalcule_Transporteur_Records].[ZoneID_AjustementID]
		,[AjustementCalcule_Transporteur_Records].[ZoneID_UniteID]
		,[AjustementCalcule_Transporteur_Records].[ZoneID_MunicipaliteID]
		,[AjustementCalcule_Transporteur_Records].[ZoneID_ContratID]
		,[AjustementCalcule_Transporteur_Records].[ZoneID_Taux_transporteur]
		,[AjustementCalcule_Transporteur_Records].[ZoneID_Date_Modification]
		,[AjustementCalcule_Transporteur_Records].[ZoneID_ZoneID]

		From [fnAjustementCalcule_Transporteur_Full](@ID, @AjustementID, @UniteID, @MunicipaliteID, @LivraisonID, @TransporteurID, @FactureID, @ZoneID) As [AjustementCalcule_Transporteur_Records]
	End

Else

	Begin
		Select

		 [AjustementCalcule_Transporteur_Records].[ID]
		,[AjustementCalcule_Transporteur_Records].[DateCalcul]
		,[AjustementCalcule_Transporteur_Records].[AjustementID]
		,[AjustementCalcule_Transporteur_Records].[UniteID]
		,[AjustementCalcule_Transporteur_Records].[MunicipaliteID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID]
		,[AjustementCalcule_Transporteur_Records].[Volume]
		,[AjustementCalcule_Transporteur_Records].[Taux]
		,[AjustementCalcule_Transporteur_Records].[Montant]
		,[AjustementCalcule_Transporteur_Records].[Facture]
		,[AjustementCalcule_Transporteur_Records].[FactureID]
		,[AjustementCalcule_Transporteur_Records].[ErreurCalcul]
		,[AjustementCalcule_Transporteur_Records].[ErreurDescription]
		,[AjustementCalcule_Transporteur_Records].[ZoneID]
		,[AjustementCalcule_Transporteur_Records].[AjustementID_AjustementID]
		,[AjustementCalcule_Transporteur_Records].[AjustementID_UniteID]
		,[AjustementCalcule_Transporteur_Records].[AjustementID_MunicipaliteID]
		,[AjustementCalcule_Transporteur_Records].[AjustementID_ContratID]
		,[AjustementCalcule_Transporteur_Records].[AjustementID_Taux_transporteur]
		,[AjustementCalcule_Transporteur_Records].[AjustementID_Date_Modification]
		,[AjustementCalcule_Transporteur_Records].[AjustementID_ZoneID]
		,[AjustementCalcule_Transporteur_Records].[UniteID_AjustementID]
		,[AjustementCalcule_Transporteur_Records].[UniteID_UniteID]
		,[AjustementCalcule_Transporteur_Records].[UniteID_MunicipaliteID]
		,[AjustementCalcule_Transporteur_Records].[UniteID_ContratID]
		,[AjustementCalcule_Transporteur_Records].[UniteID_Taux_transporteur]
		,[AjustementCalcule_Transporteur_Records].[UniteID_Date_Modification]
		,[AjustementCalcule_Transporteur_Records].[UniteID_ZoneID]
		,[AjustementCalcule_Transporteur_Records].[MunicipaliteID_AjustementID]
		,[AjustementCalcule_Transporteur_Records].[MunicipaliteID_UniteID]
		,[AjustementCalcule_Transporteur_Records].[MunicipaliteID_MunicipaliteID]
		,[AjustementCalcule_Transporteur_Records].[MunicipaliteID_ContratID]
		,[AjustementCalcule_Transporteur_Records].[MunicipaliteID_Taux_transporteur]
		,[AjustementCalcule_Transporteur_Records].[MunicipaliteID_Date_Modification]
		,[AjustementCalcule_Transporteur_Records].[MunicipaliteID_ZoneID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_ID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_DateLivraison]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_DatePaye]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_ContratID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_UniteMesureID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_EssenceID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Sciage]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_NumeroFactureUsine]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_DroitCoupeID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_EntentePaiementID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_TransporteurID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_VR]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_MasseLimite]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_VolumeBrut]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_VolumeTare]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_VolumeTransporte]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_VolumeSurcharge]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_VolumeAPayer]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Annee]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Periode]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_DateCalcul]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Taux_Transporteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_Transporteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_Usine]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_Producteur1]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_Producteur2]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_Preleve_Plan_Conjoint]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_Preleve_Fond_Roulement]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_Preleve_Fond_Forestier]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_Preleve_Divers]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_Surcharge]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_MiseEnCommun]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Facture]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Producteur1_FactureID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Producteur2_FactureID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Transporteur_FactureID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Usine_FactureID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_ErreurCalcul]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_ErreurDescription]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_LotID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Taux_Transporteur_Override]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_PaieTransporteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_VolumeSurcharge_Override]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_SurchargeManuel]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Code]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_NombrePermis]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_ZoneID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_MunicipaliteID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_ChargeurID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_Chargeur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_ChargeurAuProducteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_ChargeurAuTransporteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_AutresAuProducteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_AutresAuProducteurDescription]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_AutresAuTransporteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_AutresAuTransporteurDescription]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_CompensationDeDeplacement]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Chargeur_FactureID]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Commentaires_Producteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Commentaires_Transporteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Commentaires_Chargeur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_TauxChargeurAuProducteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_TauxChargeurAuTransporteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_AutresRevenusTransporteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_AutresRevenusTransporteurDescription]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_AutresRevenusProducteur]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Frais_AutresRevenusProducteurDescription]
		,[AjustementCalcule_Transporteur_Records].[LivraisonID_Montant_SurchargeProducteur]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_ID]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_CleTri]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Nom]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_AuSoinsDe]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Rue]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Ville]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_PaysID]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Code_postal]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Telephone]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Telephone_Poste]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Telecopieur]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Telephone2]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Telephone2_Desc]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Telephone2_Poste]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Telephone3]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Telephone3_Desc]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Telephone3_Poste]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_No_membre]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Resident]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Email]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_WWW]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Commentaires]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_AfficherCommentaires]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_DepotDirect]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_InstitutionBanquaireID]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Banque_transit]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Banque_folio]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_No_TPS]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_No_TVQ]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_PayerA]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_PayerAID]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Statut]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Rep_Nom]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Rep_Telephone]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Rep_Telephone_Poste]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Rep_Email]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_EnAnglais]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Actif]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_MRCProducteurID]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_PaiementManuel]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Journal]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_RecoitTPS]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_RecoitTVQ]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_ModifierTrigger]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_IsProducteur]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_IsTransporteur]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_IsChargeur]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_IsAutre]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_AfficherCommentairesSurPermit]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_PasEmissionPermis]
		,[AjustementCalcule_Transporteur_Records].[TransporteurID_Generique]
		,[AjustementCalcule_Transporteur_Records].[FactureID_ID]
		,[AjustementCalcule_Transporteur_Records].[FactureID_NoFacture]
		,[AjustementCalcule_Transporteur_Records].[FactureID_DateFacture]
		,[AjustementCalcule_Transporteur_Records].[FactureID_Annee]
		,[AjustementCalcule_Transporteur_Records].[FactureID_TypeFactureFournisseur]
		,[AjustementCalcule_Transporteur_Records].[FactureID_TypeFacture]
		,[AjustementCalcule_Transporteur_Records].[FactureID_TypeInvoiceAcomba]
		,[AjustementCalcule_Transporteur_Records].[FactureID_FournisseurID]
		,[AjustementCalcule_Transporteur_Records].[FactureID_PayerAID]
		,[AjustementCalcule_Transporteur_Records].[FactureID_Montant_Total]
		,[AjustementCalcule_Transporteur_Records].[FactureID_Montant_TPS]
		,[AjustementCalcule_Transporteur_Records].[FactureID_Montant_TVQ]
		,[AjustementCalcule_Transporteur_Records].[FactureID_Description]
		,[AjustementCalcule_Transporteur_Records].[FactureID_Status]
		,[AjustementCalcule_Transporteur_Records].[FactureID_StatusDescription]
		,[AjustementCalcule_Transporteur_Records].[FactureID_NumeroCheque]
		,[AjustementCalcule_Transporteur_Records].[FactureID_NumeroPaiement]
		,[AjustementCalcule_Transporteur_Records].[FactureID_NumeroPaiementUnique]
		,[AjustementCalcule_Transporteur_Records].[FactureID_DateFactureAcomba]
		,[AjustementCalcule_Transporteur_Records].[FactureID_DatePaiementAcomba]
		,[AjustementCalcule_Transporteur_Records].[ZoneID_AjustementID]
		,[AjustementCalcule_Transporteur_Records].[ZoneID_UniteID]
		,[AjustementCalcule_Transporteur_Records].[ZoneID_MunicipaliteID]
		,[AjustementCalcule_Transporteur_Records].[ZoneID_ContratID]
		,[AjustementCalcule_Transporteur_Records].[ZoneID_Taux_transporteur]
		,[AjustementCalcule_Transporteur_Records].[ZoneID_Date_Modification]
		,[AjustementCalcule_Transporteur_Records].[ZoneID_ZoneID]

		From [fnAjustementCalcule_Transporteur_Full](@ID, @AjustementID, @UniteID, @MunicipaliteID, @LivraisonID, @TransporteurID, @FactureID, @ZoneID) As [AjustementCalcule_Transporteur_Records]

		For XML Auto, Elements, XMLData, BINARY BASE64
	End

Return(@@RowCount)


