Create Procedure [dbo].[spS_AjustementCalcule_TransporteurEssence_Full]

/*
Retrieve specific records from the [AjustementCalcule_TransporteurEssence] table, as well as all its foreign tables, depending on the input parameters you supply:
	[Ajustement_EssenceUnite] (via [AjustementID])
	[Ajustement_EssenceUnite] (via [EssenceID])
	[Ajustement_EssenceUnite] (via [UniteID])
	[Livraison_Detail] (via [LivraisonDetailID])
	[Fournisseur] (via [TransporteurID])
	[FactureFournisseur] (via [FactureID])
	[Ajustement_EssenceUnite] (via [Code])
*/

(
 @ID [int] = Null -- for [AjustementCalcule_TransporteurEssence].[ID] column
,@AjustementID [int] = Null -- for [AjustementCalcule_TransporteurEssence].[AjustementID] column
,@EssenceID [varchar](6) = Null -- for [AjustementCalcule_TransporteurEssence].[EssenceID] column
,@UniteID [varchar](6) = Null -- for [AjustementCalcule_TransporteurEssence].[UniteID] column
,@LivraisonDetailID [int] = Null -- for [AjustementCalcule_TransporteurEssence].[LivraisonDetailID] column
,@TransporteurID [varchar](15) = Null -- for [AjustementCalcule_TransporteurEssence].[TransporteurID] column
,@FactureID [int] = Null -- for [AjustementCalcule_TransporteurEssence].[FactureID] column
,@Code [char](4) = Null -- for [AjustementCalcule_TransporteurEssence].[Code] column
,@ReturnXML [bit] = 0 -- Indicates if we want to get back XML content instead of normal resultset (@ReturnXML = 1 to get XML back)
)

-- Returns the number of records found

As


--	IMPORTANT:
--	Changes to this SQL code may cause incorrect behavior
--	and will be lost if the code is regenerated. 


If @ReturnXML Is Null
	Set @ReturnXML = 0

If @ReturnXML = 0
	Begin
		Select

		 [AjustementCalcule_TransporteurEssence_Records].[ID]
		,[AjustementCalcule_TransporteurEssence_Records].[DateCalcul]
		,[AjustementCalcule_TransporteurEssence_Records].[AjustementID]
		,[AjustementCalcule_TransporteurEssence_Records].[EssenceID]
		,[AjustementCalcule_TransporteurEssence_Records].[UniteID]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID]
		,[AjustementCalcule_TransporteurEssence_Records].[Volume]
		,[AjustementCalcule_TransporteurEssence_Records].[Taux]
		,[AjustementCalcule_TransporteurEssence_Records].[Montant]
		,[AjustementCalcule_TransporteurEssence_Records].[Facture]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID]
		,[AjustementCalcule_TransporteurEssence_Records].[ErreurCalcul]
		,[AjustementCalcule_TransporteurEssence_Records].[ErreurDescription]
		,[AjustementCalcule_TransporteurEssence_Records].[Code]
		,[AjustementCalcule_TransporteurEssence_Records].[AjustementID_AjustementID]
		,[AjustementCalcule_TransporteurEssence_Records].[AjustementID_EssenceID]
		,[AjustementCalcule_TransporteurEssence_Records].[AjustementID_UniteID]
		,[AjustementCalcule_TransporteurEssence_Records].[AjustementID_ContratID]
		,[AjustementCalcule_TransporteurEssence_Records].[AjustementID_Taux_usine]
		,[AjustementCalcule_TransporteurEssence_Records].[AjustementID_Taux_producteur]
		,[AjustementCalcule_TransporteurEssence_Records].[AjustementID_Taux_transporteur]
		,[AjustementCalcule_TransporteurEssence_Records].[AjustementID_Date_Modification]
		,[AjustementCalcule_TransporteurEssence_Records].[AjustementID_Code]
		,[AjustementCalcule_TransporteurEssence_Records].[EssenceID_AjustementID]
		,[AjustementCalcule_TransporteurEssence_Records].[EssenceID_EssenceID]
		,[AjustementCalcule_TransporteurEssence_Records].[EssenceID_UniteID]
		,[AjustementCalcule_TransporteurEssence_Records].[EssenceID_ContratID]
		,[AjustementCalcule_TransporteurEssence_Records].[EssenceID_Taux_usine]
		,[AjustementCalcule_TransporteurEssence_Records].[EssenceID_Taux_producteur]
		,[AjustementCalcule_TransporteurEssence_Records].[EssenceID_Taux_transporteur]
		,[AjustementCalcule_TransporteurEssence_Records].[EssenceID_Date_Modification]
		,[AjustementCalcule_TransporteurEssence_Records].[EssenceID_Code]
		,[AjustementCalcule_TransporteurEssence_Records].[UniteID_AjustementID]
		,[AjustementCalcule_TransporteurEssence_Records].[UniteID_EssenceID]
		,[AjustementCalcule_TransporteurEssence_Records].[UniteID_UniteID]
		,[AjustementCalcule_TransporteurEssence_Records].[UniteID_ContratID]
		,[AjustementCalcule_TransporteurEssence_Records].[UniteID_Taux_usine]
		,[AjustementCalcule_TransporteurEssence_Records].[UniteID_Taux_producteur]
		,[AjustementCalcule_TransporteurEssence_Records].[UniteID_Taux_transporteur]
		,[AjustementCalcule_TransporteurEssence_Records].[UniteID_Date_Modification]
		,[AjustementCalcule_TransporteurEssence_Records].[UniteID_Code]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_ID]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_LivraisonID]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_ContratID]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_EssenceID]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_UniteMesureID]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_ProducteurID]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Droit_Coupe]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_VolumeBrut]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_VolumeReduction]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_VolumeNet]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_VolumeContingente]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_ContingentementID]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_DateCalcul]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Taux_Usine]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Montant_Usine]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Taux_Producteur]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Montant_ProducteurBrut]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Taux_TransporteurMoyen]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Taux_TransporteurMoyen_Override]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Montant_TransporteurMoyen]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Taux_Preleve_Plan_Conjoint]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Montant_Preleve_Plan_Conjoint]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Taux_Preleve_Fond_Roulement]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Montant_Preleve_Fond_Roulement]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Taux_Preleve_Fond_Forestier]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Montant_Preleve_Fond_Forestier]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Taux_Preleve_Divers]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Montant_Preleve_Divers]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Montant_ProducteurNet]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Taux_Producteur_Override]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Taux_Usine_Override]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Code]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_UsePreleveMontant]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_ID]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_CleTri]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Nom]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_AuSoinsDe]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Rue]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Ville]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_PaysID]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Code_postal]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Telephone]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Telephone_Poste]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Telecopieur]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Telephone2]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Telephone2_Desc]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Telephone2_Poste]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Telephone3]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Telephone3_Desc]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Telephone3_Poste]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_No_membre]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Resident]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Email]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_WWW]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Commentaires]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_AfficherCommentaires]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_DepotDirect]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_InstitutionBanquaireID]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Banque_transit]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Banque_folio]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_No_TPS]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_No_TVQ]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_PayerA]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_PayerAID]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Statut]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Rep_Nom]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Rep_Telephone]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Rep_Telephone_Poste]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Rep_Email]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_EnAnglais]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Actif]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_MRCProducteurID]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_PaiementManuel]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Journal]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_RecoitTPS]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_RecoitTVQ]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_ModifierTrigger]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_IsProducteur]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_IsTransporteur]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_IsChargeur]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_IsAutre]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_AfficherCommentairesSurPermit]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_PasEmissionPermis]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Generique]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Membre_OGC]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_InscritTPS]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_InscritTVQ]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_IsOGC]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Rep2_Nom]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Rep2_Telephone]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Rep2_Telephone_Poste]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Rep2_Email]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Rep2_Commentaires]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_ID]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_NoFacture]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_DateFacture]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_Annee]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_TypeFactureFournisseur]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_TypeFacture]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_TypeInvoiceAcomba]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_FournisseurID]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_PayerAID]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_Montant_Total]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_Montant_TPS]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_Montant_TVQ]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_Description]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_Status]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_StatusDescription]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_NumeroCheque]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_NumeroPaiement]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_NumeroPaiementUnique]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_DateFactureAcomba]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_DatePaiementAcomba]
		,[AjustementCalcule_TransporteurEssence_Records].[Code_AjustementID]
		,[AjustementCalcule_TransporteurEssence_Records].[Code_EssenceID]
		,[AjustementCalcule_TransporteurEssence_Records].[Code_UniteID]
		,[AjustementCalcule_TransporteurEssence_Records].[Code_ContratID]
		,[AjustementCalcule_TransporteurEssence_Records].[Code_Taux_usine]
		,[AjustementCalcule_TransporteurEssence_Records].[Code_Taux_producteur]
		,[AjustementCalcule_TransporteurEssence_Records].[Code_Taux_transporteur]
		,[AjustementCalcule_TransporteurEssence_Records].[Code_Date_Modification]
		,[AjustementCalcule_TransporteurEssence_Records].[Code_Code]

		From [fnAjustementCalcule_TransporteurEssence_Full](@ID, @AjustementID, @EssenceID, @UniteID, @LivraisonDetailID, @TransporteurID, @FactureID, @Code) As [AjustementCalcule_TransporteurEssence_Records]
	End

Else

	Begin
		Select

		 [AjustementCalcule_TransporteurEssence_Records].[ID]
		,[AjustementCalcule_TransporteurEssence_Records].[DateCalcul]
		,[AjustementCalcule_TransporteurEssence_Records].[AjustementID]
		,[AjustementCalcule_TransporteurEssence_Records].[EssenceID]
		,[AjustementCalcule_TransporteurEssence_Records].[UniteID]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID]
		,[AjustementCalcule_TransporteurEssence_Records].[Volume]
		,[AjustementCalcule_TransporteurEssence_Records].[Taux]
		,[AjustementCalcule_TransporteurEssence_Records].[Montant]
		,[AjustementCalcule_TransporteurEssence_Records].[Facture]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID]
		,[AjustementCalcule_TransporteurEssence_Records].[ErreurCalcul]
		,[AjustementCalcule_TransporteurEssence_Records].[ErreurDescription]
		,[AjustementCalcule_TransporteurEssence_Records].[Code]
		,[AjustementCalcule_TransporteurEssence_Records].[AjustementID_AjustementID]
		,[AjustementCalcule_TransporteurEssence_Records].[AjustementID_EssenceID]
		,[AjustementCalcule_TransporteurEssence_Records].[AjustementID_UniteID]
		,[AjustementCalcule_TransporteurEssence_Records].[AjustementID_ContratID]
		,[AjustementCalcule_TransporteurEssence_Records].[AjustementID_Taux_usine]
		,[AjustementCalcule_TransporteurEssence_Records].[AjustementID_Taux_producteur]
		,[AjustementCalcule_TransporteurEssence_Records].[AjustementID_Taux_transporteur]
		,[AjustementCalcule_TransporteurEssence_Records].[AjustementID_Date_Modification]
		,[AjustementCalcule_TransporteurEssence_Records].[AjustementID_Code]
		,[AjustementCalcule_TransporteurEssence_Records].[EssenceID_AjustementID]
		,[AjustementCalcule_TransporteurEssence_Records].[EssenceID_EssenceID]
		,[AjustementCalcule_TransporteurEssence_Records].[EssenceID_UniteID]
		,[AjustementCalcule_TransporteurEssence_Records].[EssenceID_ContratID]
		,[AjustementCalcule_TransporteurEssence_Records].[EssenceID_Taux_usine]
		,[AjustementCalcule_TransporteurEssence_Records].[EssenceID_Taux_producteur]
		,[AjustementCalcule_TransporteurEssence_Records].[EssenceID_Taux_transporteur]
		,[AjustementCalcule_TransporteurEssence_Records].[EssenceID_Date_Modification]
		,[AjustementCalcule_TransporteurEssence_Records].[EssenceID_Code]
		,[AjustementCalcule_TransporteurEssence_Records].[UniteID_AjustementID]
		,[AjustementCalcule_TransporteurEssence_Records].[UniteID_EssenceID]
		,[AjustementCalcule_TransporteurEssence_Records].[UniteID_UniteID]
		,[AjustementCalcule_TransporteurEssence_Records].[UniteID_ContratID]
		,[AjustementCalcule_TransporteurEssence_Records].[UniteID_Taux_usine]
		,[AjustementCalcule_TransporteurEssence_Records].[UniteID_Taux_producteur]
		,[AjustementCalcule_TransporteurEssence_Records].[UniteID_Taux_transporteur]
		,[AjustementCalcule_TransporteurEssence_Records].[UniteID_Date_Modification]
		,[AjustementCalcule_TransporteurEssence_Records].[UniteID_Code]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_ID]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_LivraisonID]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_ContratID]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_EssenceID]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_UniteMesureID]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_ProducteurID]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Droit_Coupe]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_VolumeBrut]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_VolumeReduction]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_VolumeNet]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_VolumeContingente]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_ContingentementID]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_DateCalcul]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Taux_Usine]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Montant_Usine]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Taux_Producteur]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Montant_ProducteurBrut]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Taux_TransporteurMoyen]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Taux_TransporteurMoyen_Override]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Montant_TransporteurMoyen]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Taux_Preleve_Plan_Conjoint]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Montant_Preleve_Plan_Conjoint]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Taux_Preleve_Fond_Roulement]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Montant_Preleve_Fond_Roulement]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Taux_Preleve_Fond_Forestier]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Montant_Preleve_Fond_Forestier]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Taux_Preleve_Divers]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Montant_Preleve_Divers]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Montant_ProducteurNet]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Taux_Producteur_Override]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Taux_Usine_Override]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_Code]
		,[AjustementCalcule_TransporteurEssence_Records].[LivraisonDetailID_UsePreleveMontant]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_ID]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_CleTri]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Nom]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_AuSoinsDe]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Rue]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Ville]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_PaysID]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Code_postal]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Telephone]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Telephone_Poste]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Telecopieur]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Telephone2]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Telephone2_Desc]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Telephone2_Poste]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Telephone3]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Telephone3_Desc]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Telephone3_Poste]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_No_membre]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Resident]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Email]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_WWW]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Commentaires]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_AfficherCommentaires]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_DepotDirect]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_InstitutionBanquaireID]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Banque_transit]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Banque_folio]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_No_TPS]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_No_TVQ]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_PayerA]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_PayerAID]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Statut]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Rep_Nom]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Rep_Telephone]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Rep_Telephone_Poste]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Rep_Email]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_EnAnglais]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Actif]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_MRCProducteurID]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_PaiementManuel]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Journal]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_RecoitTPS]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_RecoitTVQ]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_ModifierTrigger]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_IsProducteur]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_IsTransporteur]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_IsChargeur]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_IsAutre]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_AfficherCommentairesSurPermit]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_PasEmissionPermis]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Generique]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Membre_OGC]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_InscritTPS]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_InscritTVQ]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_IsOGC]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Rep2_Nom]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Rep2_Telephone]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Rep2_Telephone_Poste]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Rep2_Email]
		,[AjustementCalcule_TransporteurEssence_Records].[TransporteurID_Rep2_Commentaires]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_ID]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_NoFacture]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_DateFacture]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_Annee]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_TypeFactureFournisseur]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_TypeFacture]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_TypeInvoiceAcomba]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_FournisseurID]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_PayerAID]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_Montant_Total]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_Montant_TPS]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_Montant_TVQ]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_Description]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_Status]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_StatusDescription]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_NumeroCheque]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_NumeroPaiement]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_NumeroPaiementUnique]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_DateFactureAcomba]
		,[AjustementCalcule_TransporteurEssence_Records].[FactureID_DatePaiementAcomba]
		,[AjustementCalcule_TransporteurEssence_Records].[Code_AjustementID]
		,[AjustementCalcule_TransporteurEssence_Records].[Code_EssenceID]
		,[AjustementCalcule_TransporteurEssence_Records].[Code_UniteID]
		,[AjustementCalcule_TransporteurEssence_Records].[Code_ContratID]
		,[AjustementCalcule_TransporteurEssence_Records].[Code_Taux_usine]
		,[AjustementCalcule_TransporteurEssence_Records].[Code_Taux_producteur]
		,[AjustementCalcule_TransporteurEssence_Records].[Code_Taux_transporteur]
		,[AjustementCalcule_TransporteurEssence_Records].[Code_Date_Modification]
		,[AjustementCalcule_TransporteurEssence_Records].[Code_Code]

		From [fnAjustementCalcule_TransporteurEssence_Full](@ID, @AjustementID, @EssenceID, @UniteID, @LivraisonDetailID, @TransporteurID, @FactureID, @Code) As [AjustementCalcule_TransporteurEssence_Records]

		For XML Auto, Elements, XMLData, BINARY BASE64
	End

Return(@@RowCount)
