CREATE PROCEDURE [dbo].[spS_Livraison]
@ID INT=Null, @ContratID VARCHAR (10)=Null, @UniteMesureID VARCHAR (6)=Null, @EssenceID VARCHAR (6)=Null, @DroitCoupeID VARCHAR (15)=Null, @EntentePaiementID VARCHAR (15)=Null, @TransporteurID VARCHAR (15)=Null, @Annee INT=Null, @Periode INT=Null, @Producteur1_FactureID INT=Null, @Producteur2_FactureID INT=Null, @Transporteur_FactureID INT=Null, @Usine_FactureID INT=Null, @LotID INT=Null, @ZoneID VARCHAR (2)=Null, @MunicipaliteID VARCHAR (6)=Null, @ChargeurID VARCHAR (15)=Null, @Chargeur_FactureID INT=Null, @ReturnXML BIT=0
AS
If @ReturnXML Is Null
	Set @ReturnXML = 0

If @ReturnXML = 0
	Begin
		Select

		 [Livraison_Records].[ID]
		,[Livraison_Records].[DateLivraison]
		,[Livraison_Records].[DatePaye]
		,[Livraison_Records].[ContratID]
		,[Livraison_Records].[UniteMesureID]
		,[Livraison_Records].[EssenceID]
		,[Livraison_Records].[Sciage]
		,[Livraison_Records].[NumeroFactureUsine]
		,[Livraison_Records].[DroitCoupeID]
		,[Livraison_Records].[EntentePaiementID]
		,[Livraison_Records].[TransporteurID]
		,[Livraison_Records].[VR]
		,[Livraison_Records].[MasseLimite]
		,[Livraison_Records].[VolumeBrut]
		,[Livraison_Records].[VolumeTare]
		,[Livraison_Records].[VolumeTransporte]
		,[Livraison_Records].[VolumeSurcharge]
		,[Livraison_Records].[VolumeAPayer]
		,[Livraison_Records].[Annee]
		,[Livraison_Records].[Periode]
		,[Livraison_Records].[DateCalcul]
		,[Livraison_Records].[Taux_Transporteur]
		,[Livraison_Records].[Montant_Transporteur]
		,[Livraison_Records].[Montant_Usine]
		,[Livraison_Records].[Montant_Producteur1]
		,[Livraison_Records].[Montant_Producteur2]
		,[Livraison_Records].[Montant_Preleve_Plan_Conjoint]
		,[Livraison_Records].[Montant_Preleve_Fond_Roulement]
		,[Livraison_Records].[Montant_Preleve_Fond_Forestier]
		,[Livraison_Records].[Montant_Preleve_Divers]
		,[Livraison_Records].[Montant_Surcharge]
		,[Livraison_Records].[Montant_MiseEnCommun]
		,[Livraison_Records].[Facture]
		,[Livraison_Records].[Producteur1_FactureID]
		,[Livraison_Records].[Producteur2_FactureID]
		,[Livraison_Records].[Transporteur_FactureID]
		,[Livraison_Records].[Usine_FactureID]
		,[Livraison_Records].[ErreurCalcul]
		,[Livraison_Records].[ErreurDescription]
		,[Livraison_Records].[LotID]
		,[Livraison_Records].[Taux_Transporteur_Override]
		,[Livraison_Records].[PaieTransporteur]
		,[Livraison_Records].[VolumeSurcharge_Override]
		,[Livraison_Records].[SurchargeManuel]
		,[Livraison_Records].[Code]
		,[Livraison_Records].[NombrePermis]
		,[Livraison_Records].[ZoneID]
		,[Livraison_Records].[MunicipaliteID]
		,[Livraison_Records].[ChargeurID]
		,[Livraison_Records].[Montant_Chargeur]
		,[Livraison_Records].[Frais_ChargeurAuProducteur]
		,[Livraison_Records].[Frais_ChargeurAuTransporteur]
		,[Livraison_Records].[Frais_AutresAuProducteur]
		,[Livraison_Records].[Frais_AutresAuProducteurDescription]
		,[Livraison_Records].[Frais_AutresAuProducteurTransportSciage]
		,[Livraison_Records].[Frais_AutresAuTransporteur]
		,[Livraison_Records].[Frais_AutresAuTransporteurDescription]
		,[Livraison_Records].[Frais_CompensationDeDeplacement]
		,[Livraison_Records].[Chargeur_FactureID]
		,[Livraison_Records].[Commentaires_Producteur]
		,[Livraison_Records].[Commentaires_Transporteur]
		,[Livraison_Records].[Commentaires_Chargeur]
		,[Livraison_Records].[TauxChargeurAuProducteur]
		,[Livraison_Records].[TauxChargeurAuTransporteur]
		,[Livraison_Records].[Frais_AutresRevenusTransporteur]
		,[Livraison_Records].[Frais_AutresRevenusTransporteurDescription]
		,[Livraison_Records].[Frais_AutresRevenusProducteur]
		,[Livraison_Records].[Frais_AutresRevenusProducteurDescription]
		,[Livraison_Records].[Montant_SurchargeProducteur]
		,[Livraison_Records].[KgVert_Brut]
		,[Livraison_Records].[KgVert_Tare]
		,[Livraison_Records].[KgVert_Net]
		,[Livraison_Records].[KgVert_Rejets]
		,[Livraison_Records].[KgVert_Paye]
		,[Livraison_Records].[Pourcent_Sec_Producteur]
		,[Livraison_Records].[Pourcent_Sec_Producteur_Override]
		,[Livraison_Records].[TMA_Producteur]
		,[Livraison_Records].[Pourcent_Sec_Transport]
		,[Livraison_Records].[Pourcent_Sec_Transport_Override]
		,[Livraison_Records].[TMA_Transport]
		,[Livraison_Records].[IsTMA]
		,[Livraison_Records].[SuspendrePaiement]
		,[Livraison_Records].[BonCommande]

		From [fnLivraison](@ID, @ContratID, @UniteMesureID, @EssenceID, @DroitCoupeID, @EntentePaiementID, @TransporteurID, @Annee, @Periode, @Producteur1_FactureID, @Producteur2_FactureID, @Transporteur_FactureID, @Usine_FactureID, @LotID, @ZoneID, @MunicipaliteID, @ChargeurID, @Chargeur_FactureID) As [Livraison_Records]
	End

Else

	Begin
		Select

		 [Livraison_Records].[ID]
		,[Livraison_Records].[DateLivraison]
		,[Livraison_Records].[DatePaye]
		,[Livraison_Records].[ContratID]
		,[Livraison_Records].[UniteMesureID]
		,[Livraison_Records].[EssenceID]
		,[Livraison_Records].[Sciage]
		,[Livraison_Records].[NumeroFactureUsine]
		,[Livraison_Records].[DroitCoupeID]
		,[Livraison_Records].[EntentePaiementID]
		,[Livraison_Records].[TransporteurID]
		,[Livraison_Records].[VR]
		,[Livraison_Records].[MasseLimite]
		,[Livraison_Records].[VolumeBrut]
		,[Livraison_Records].[VolumeTare]
		,[Livraison_Records].[VolumeTransporte]
		,[Livraison_Records].[VolumeSurcharge]
		,[Livraison_Records].[VolumeAPayer]
		,[Livraison_Records].[Annee]
		,[Livraison_Records].[Periode]
		,[Livraison_Records].[DateCalcul]
		,[Livraison_Records].[Taux_Transporteur]
		,[Livraison_Records].[Montant_Transporteur]
		,[Livraison_Records].[Montant_Usine]
		,[Livraison_Records].[Montant_Producteur1]
		,[Livraison_Records].[Montant_Producteur2]
		,[Livraison_Records].[Montant_Preleve_Plan_Conjoint]
		,[Livraison_Records].[Montant_Preleve_Fond_Roulement]
		,[Livraison_Records].[Montant_Preleve_Fond_Forestier]
		,[Livraison_Records].[Montant_Preleve_Divers]
		,[Livraison_Records].[Montant_Surcharge]
		,[Livraison_Records].[Montant_MiseEnCommun]
		,[Livraison_Records].[Facture]
		,[Livraison_Records].[Producteur1_FactureID]
		,[Livraison_Records].[Producteur2_FactureID]
		,[Livraison_Records].[Transporteur_FactureID]
		,[Livraison_Records].[Usine_FactureID]
		,[Livraison_Records].[ErreurCalcul]
		,[Livraison_Records].[ErreurDescription]
		,[Livraison_Records].[LotID]
		,[Livraison_Records].[Taux_Transporteur_Override]
		,[Livraison_Records].[PaieTransporteur]
		,[Livraison_Records].[VolumeSurcharge_Override]
		,[Livraison_Records].[SurchargeManuel]
		,[Livraison_Records].[Code]
		,[Livraison_Records].[NombrePermis]
		,[Livraison_Records].[ZoneID]
		,[Livraison_Records].[MunicipaliteID]
		,[Livraison_Records].[ChargeurID]
		,[Livraison_Records].[Montant_Chargeur]
		,[Livraison_Records].[Frais_ChargeurAuProducteur]
		,[Livraison_Records].[Frais_ChargeurAuTransporteur]
		,[Livraison_Records].[Frais_AutresAuProducteur]
		,[Livraison_Records].[Frais_AutresAuProducteurDescription]
		,[Livraison_Records].[Frais_AutresAuProducteurTransportSciage]
		,[Livraison_Records].[Frais_AutresAuTransporteur]
		,[Livraison_Records].[Frais_AutresAuTransporteurDescription]
		,[Livraison_Records].[Frais_CompensationDeDeplacement]
		,[Livraison_Records].[Chargeur_FactureID]
		,[Livraison_Records].[Commentaires_Producteur]
		,[Livraison_Records].[Commentaires_Transporteur]
		,[Livraison_Records].[Commentaires_Chargeur]
		,[Livraison_Records].[TauxChargeurAuProducteur]
		,[Livraison_Records].[TauxChargeurAuTransporteur]
		,[Livraison_Records].[Frais_AutresRevenusTransporteur]
		,[Livraison_Records].[Frais_AutresRevenusTransporteurDescription]
		,[Livraison_Records].[Frais_AutresRevenusProducteur]
		,[Livraison_Records].[Frais_AutresRevenusProducteurDescription]
		,[Livraison_Records].[Montant_SurchargeProducteur]
		,[Livraison_Records].[KgVert_Brut]
		,[Livraison_Records].[KgVert_Tare]
		,[Livraison_Records].[KgVert_Net]
		,[Livraison_Records].[KgVert_Rejets]
		,[Livraison_Records].[KgVert_Paye]
		,[Livraison_Records].[Pourcent_Sec_Producteur]
		,[Livraison_Records].[Pourcent_Sec_Producteur_Override]
		,[Livraison_Records].[TMA_Producteur]
		,[Livraison_Records].[Pourcent_Sec_Transport]
		,[Livraison_Records].[Pourcent_Sec_Transport_Override]
		,[Livraison_Records].[TMA_Transport]
		,[Livraison_Records].[IsTMA]
		,[Livraison_Records].[SuspendrePaiement]
		,[Livraison_Records].[BonCommande]

		From [fnLivraison](@ID, @ContratID, @UniteMesureID, @EssenceID, @DroitCoupeID, @EntentePaiementID, @TransporteurID, @Annee, @Periode, @Producteur1_FactureID, @Producteur2_FactureID, @Transporteur_FactureID, @Usine_FactureID, @LotID, @ZoneID, @MunicipaliteID, @ChargeurID, @Chargeur_FactureID) As [Livraison_Records]

		For XML Auto, Elements, XMLData, BINARY BASE64
	End

Return(@@RowCount)


