

Create Procedure [spS_IndexationCalcule_Producteur_Full]

/*
Retrieve specific records from the [IndexationCalcule_Producteur] table, as well as all its foreign tables, depending on the input parameters you supply:
	[TypeIndexation] (via [TypeIndexation])
	[Indexation] (via [IndexationID])
	[Indexation_EssenceUnite] (via [IndexationDetailID])
	[Livraison] (via [LivraisonID])
	[Livraison_Detail] (via [LivraisonDetailID])
	[Fournisseur] (via [ProducteurID])
	[Contrat_EssenceUnite] (via [ContratID])
	[Contrat_EssenceUnite] (via [EssenceID])
	[Contrat_EssenceUnite] (via [Code])
	[Contrat_EssenceUnite] (via [UniteID])
	[FactureFournisseur] (via [FactureID])
*/

(
 @ID [int] = Null -- for [IndexationCalcule_Producteur].[ID] column
,@TypeIndexation [char](1) = Null -- for [IndexationCalcule_Producteur].[TypeIndexation] column
,@IndexationID [int] = Null -- for [IndexationCalcule_Producteur].[IndexationID] column
,@IndexationDetailID [int] = Null -- for [IndexationCalcule_Producteur].[IndexationDetailID] column
,@LivraisonID [int] = Null -- for [IndexationCalcule_Producteur].[LivraisonID] column
,@LivraisonDetailID [int] = Null -- for [IndexationCalcule_Producteur].[LivraisonDetailID] column
,@ProducteurID [varchar](15) = Null -- for [IndexationCalcule_Producteur].[ProducteurID] column
,@ContratID [varchar](10) = Null -- for [IndexationCalcule_Producteur].[ContratID] column
,@EssenceID [varchar](6) = Null -- for [IndexationCalcule_Producteur].[EssenceID] column
,@Code [char](4) = Null -- for [IndexationCalcule_Producteur].[Code] column
,@UniteID [varchar](6) = Null -- for [IndexationCalcule_Producteur].[UniteID] column
,@FactureID [int] = Null -- for [IndexationCalcule_Producteur].[FactureID] column
,@ReturnXML [bit] = 0 -- Indicates if we want to get back XML content instead of normal resultset (@ReturnXML = 1 to get XML back)
)

-- Returns the number of records found

As


--	IMPORTANT:
--	Changes to this SQL code may cause incorrect behavior
--	and will be lost if the code is regenerated. 


If @ReturnXML Is Null
	Set @ReturnXML = 0

If @ReturnXML = 0
	Begin
		Select

		 [IndexationCalcule_Producteur_Records].[ID]
		,[IndexationCalcule_Producteur_Records].[DateCalcul]
		,[IndexationCalcule_Producteur_Records].[TypeIndexation]
		,[IndexationCalcule_Producteur_Records].[IndexationID]
		,[IndexationCalcule_Producteur_Records].[IndexationDetailID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID]
		,[IndexationCalcule_Producteur_Records].[ProducteurID]
		,[IndexationCalcule_Producteur_Records].[ContratID]
		,[IndexationCalcule_Producteur_Records].[EssenceID]
		,[IndexationCalcule_Producteur_Records].[Code]
		,[IndexationCalcule_Producteur_Records].[UniteID]
		,[IndexationCalcule_Producteur_Records].[Volume]
		,[IndexationCalcule_Producteur_Records].[MontantDejaPaye]
		,[IndexationCalcule_Producteur_Records].[PourcentageDuMontant]
		,[IndexationCalcule_Producteur_Records].[Taux]
		,[IndexationCalcule_Producteur_Records].[Montant]
		,[IndexationCalcule_Producteur_Records].[Facture]
		,[IndexationCalcule_Producteur_Records].[FactureID]
		,[IndexationCalcule_Producteur_Records].[ErreurCalcul]
		,[IndexationCalcule_Producteur_Records].[ErreurDescription]
		,[IndexationCalcule_Producteur_Records].[TypeIndexation_ID]
		,[IndexationCalcule_Producteur_Records].[TypeIndexation_Description]
		,[IndexationCalcule_Producteur_Records].[IndexationID_ID]
		,[IndexationCalcule_Producteur_Records].[IndexationID_DateIndexation]
		,[IndexationCalcule_Producteur_Records].[IndexationID_ContratID]
		,[IndexationCalcule_Producteur_Records].[IndexationID_Periode_Debut]
		,[IndexationCalcule_Producteur_Records].[IndexationID_Periode_Fin]
		,[IndexationCalcule_Producteur_Records].[IndexationID_TypeIndexation]
		,[IndexationCalcule_Producteur_Records].[IndexationID_PourcentageDuMontant]
		,[IndexationCalcule_Producteur_Records].[IndexationID_Facture]
		,[IndexationCalcule_Producteur_Records].[IndexationID_IndexationTransporteur]
		,[IndexationCalcule_Producteur_Records].[IndexationID_Date_Debut]
		,[IndexationCalcule_Producteur_Records].[IndexationID_Date_Fin]
		,[IndexationCalcule_Producteur_Records].[IndexationID_IndexationManuelle]
		,[IndexationCalcule_Producteur_Records].[IndexationDetailID_ID]
		,[IndexationCalcule_Producteur_Records].[IndexationDetailID_IndexationID]
		,[IndexationCalcule_Producteur_Records].[IndexationDetailID_ContratID]
		,[IndexationCalcule_Producteur_Records].[IndexationDetailID_EssenceID]
		,[IndexationCalcule_Producteur_Records].[IndexationDetailID_Code]
		,[IndexationCalcule_Producteur_Records].[IndexationDetailID_UniteID]
		,[IndexationCalcule_Producteur_Records].[IndexationDetailID_Taux]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_ID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_DateLivraison]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_DatePaye]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_ContratID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_UniteMesureID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_EssenceID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Sciage]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_NumeroFactureUsine]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_DroitCoupeID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_EntentePaiementID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_TransporteurID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_VR]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_MasseLimite]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_VolumeBrut]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_VolumeTare]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_VolumeTransporte]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_VolumeSurcharge]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_VolumeAPayer]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Annee]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Periode]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_DateCalcul]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Taux_Transporteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_Transporteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_Usine]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_Producteur1]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_Producteur2]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_Preleve_Plan_Conjoint]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_Preleve_Fond_Roulement]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_Preleve_Fond_Forestier]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_Preleve_Divers]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_Surcharge]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_MiseEnCommun]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Facture]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Producteur1_FactureID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Producteur2_FactureID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Transporteur_FactureID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Usine_FactureID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_ErreurCalcul]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_ErreurDescription]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_LotID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Taux_Transporteur_Override]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_PaieTransporteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_VolumeSurcharge_Override]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_SurchargeManuel]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Code]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_NombrePermis]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_ZoneID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_MunicipaliteID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_ChargeurID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_Chargeur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_ChargeurAuProducteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_ChargeurAuTransporteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_AutresAuProducteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_AutresAuProducteurDescription]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_AutresAuTransporteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_AutresAuTransporteurDescription]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_CompensationDeDeplacement]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Chargeur_FactureID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Commentaires_Producteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Commentaires_Transporteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Commentaires_Chargeur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_TauxChargeurAuProducteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_TauxChargeurAuTransporteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_AutresRevenusTransporteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_AutresRevenusTransporteurDescription]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_AutresRevenusProducteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_AutresRevenusProducteurDescription]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_SurchargeProducteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_ID]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_LivraisonID]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_ContratID]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_EssenceID]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_UniteMesureID]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_ProducteurID]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Droit_Coupe]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_VolumeBrut]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_VolumeReduction]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_VolumeNet]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_VolumeContingente]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_ContingentementID]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_DateCalcul]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Taux_Usine]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Montant_Usine]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Taux_Producteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Montant_ProducteurBrut]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Taux_TransporteurMoyen]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Taux_TransporteurMoyen_Override]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Montant_TransporteurMoyen]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Taux_Preleve_Plan_Conjoint]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Montant_Preleve_Plan_Conjoint]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Taux_Preleve_Fond_Roulement]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Montant_Preleve_Fond_Roulement]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Taux_Preleve_Fond_Forestier]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Montant_Preleve_Fond_Forestier]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Taux_Preleve_Divers]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Montant_Preleve_Divers]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Montant_ProducteurNet]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Taux_Producteur_Override]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Taux_Usine_Override]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Code]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_UsePreleveMontant]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_ID]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_CleTri]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Nom]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_AuSoinsDe]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Rue]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Ville]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_PaysID]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Code_postal]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Telephone]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Telephone_Poste]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Telecopieur]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Telephone2]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Telephone2_Desc]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Telephone2_Poste]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Telephone3]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Telephone3_Desc]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Telephone3_Poste]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_No_membre]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Resident]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Email]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_WWW]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Commentaires]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_AfficherCommentaires]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_DepotDirect]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_InstitutionBanquaireID]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Banque_transit]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Banque_folio]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_No_TPS]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_No_TVQ]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_PayerA]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_PayerAID]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Statut]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Rep_Nom]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Rep_Telephone]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Rep_Telephone_Poste]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Rep_Email]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_EnAnglais]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Actif]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_MRCProducteurID]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_PaiementManuel]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Journal]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_RecoitTPS]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_RecoitTVQ]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_ModifierTrigger]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_IsProducteur]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_IsTransporteur]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_IsChargeur]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_IsAutre]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_AfficherCommentairesSurPermit]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_PasEmissionPermis]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Generique]
		,[IndexationCalcule_Producteur_Records].[ContratID_ContratID]
		,[IndexationCalcule_Producteur_Records].[ContratID_EssenceID]
		,[IndexationCalcule_Producteur_Records].[ContratID_UniteID]
		,[IndexationCalcule_Producteur_Records].[ContratID_Code]
		,[IndexationCalcule_Producteur_Records].[ContratID_Quantite_prevue]
		,[IndexationCalcule_Producteur_Records].[ContratID_Taux_usine]
		,[IndexationCalcule_Producteur_Records].[ContratID_Taux_producteur]
		,[IndexationCalcule_Producteur_Records].[ContratID_Actif]
		,[IndexationCalcule_Producteur_Records].[ContratID_Description]
		,[IndexationCalcule_Producteur_Records].[EssenceID_ContratID]
		,[IndexationCalcule_Producteur_Records].[EssenceID_EssenceID]
		,[IndexationCalcule_Producteur_Records].[EssenceID_UniteID]
		,[IndexationCalcule_Producteur_Records].[EssenceID_Code]
		,[IndexationCalcule_Producteur_Records].[EssenceID_Quantite_prevue]
		,[IndexationCalcule_Producteur_Records].[EssenceID_Taux_usine]
		,[IndexationCalcule_Producteur_Records].[EssenceID_Taux_producteur]
		,[IndexationCalcule_Producteur_Records].[EssenceID_Actif]
		,[IndexationCalcule_Producteur_Records].[EssenceID_Description]
		,[IndexationCalcule_Producteur_Records].[Code_ContratID]
		,[IndexationCalcule_Producteur_Records].[Code_EssenceID]
		,[IndexationCalcule_Producteur_Records].[Code_UniteID]
		,[IndexationCalcule_Producteur_Records].[Code_Code]
		,[IndexationCalcule_Producteur_Records].[Code_Quantite_prevue]
		,[IndexationCalcule_Producteur_Records].[Code_Taux_usine]
		,[IndexationCalcule_Producteur_Records].[Code_Taux_producteur]
		,[IndexationCalcule_Producteur_Records].[Code_Actif]
		,[IndexationCalcule_Producteur_Records].[Code_Description]
		,[IndexationCalcule_Producteur_Records].[UniteID_ContratID]
		,[IndexationCalcule_Producteur_Records].[UniteID_EssenceID]
		,[IndexationCalcule_Producteur_Records].[UniteID_UniteID]
		,[IndexationCalcule_Producteur_Records].[UniteID_Code]
		,[IndexationCalcule_Producteur_Records].[UniteID_Quantite_prevue]
		,[IndexationCalcule_Producteur_Records].[UniteID_Taux_usine]
		,[IndexationCalcule_Producteur_Records].[UniteID_Taux_producteur]
		,[IndexationCalcule_Producteur_Records].[UniteID_Actif]
		,[IndexationCalcule_Producteur_Records].[UniteID_Description]
		,[IndexationCalcule_Producteur_Records].[FactureID_ID]
		,[IndexationCalcule_Producteur_Records].[FactureID_NoFacture]
		,[IndexationCalcule_Producteur_Records].[FactureID_DateFacture]
		,[IndexationCalcule_Producteur_Records].[FactureID_Annee]
		,[IndexationCalcule_Producteur_Records].[FactureID_TypeFactureFournisseur]
		,[IndexationCalcule_Producteur_Records].[FactureID_TypeFacture]
		,[IndexationCalcule_Producteur_Records].[FactureID_TypeInvoiceAcomba]
		,[IndexationCalcule_Producteur_Records].[FactureID_FournisseurID]
		,[IndexationCalcule_Producteur_Records].[FactureID_PayerAID]
		,[IndexationCalcule_Producteur_Records].[FactureID_Montant_Total]
		,[IndexationCalcule_Producteur_Records].[FactureID_Montant_TPS]
		,[IndexationCalcule_Producteur_Records].[FactureID_Montant_TVQ]
		,[IndexationCalcule_Producteur_Records].[FactureID_Description]
		,[IndexationCalcule_Producteur_Records].[FactureID_Status]
		,[IndexationCalcule_Producteur_Records].[FactureID_StatusDescription]
		,[IndexationCalcule_Producteur_Records].[FactureID_NumeroCheque]
		,[IndexationCalcule_Producteur_Records].[FactureID_NumeroPaiement]
		,[IndexationCalcule_Producteur_Records].[FactureID_NumeroPaiementUnique]
		,[IndexationCalcule_Producteur_Records].[FactureID_DateFactureAcomba]
		,[IndexationCalcule_Producteur_Records].[FactureID_DatePaiementAcomba]

		From [fnIndexationCalcule_Producteur_Full](@ID, @TypeIndexation, @IndexationID, @IndexationDetailID, @LivraisonID, @LivraisonDetailID, @ProducteurID, @ContratID, @EssenceID, @Code, @UniteID, @FactureID) As [IndexationCalcule_Producteur_Records]
	End

Else

	Begin
		Select

		 [IndexationCalcule_Producteur_Records].[ID]
		,[IndexationCalcule_Producteur_Records].[DateCalcul]
		,[IndexationCalcule_Producteur_Records].[TypeIndexation]
		,[IndexationCalcule_Producteur_Records].[IndexationID]
		,[IndexationCalcule_Producteur_Records].[IndexationDetailID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID]
		,[IndexationCalcule_Producteur_Records].[ProducteurID]
		,[IndexationCalcule_Producteur_Records].[ContratID]
		,[IndexationCalcule_Producteur_Records].[EssenceID]
		,[IndexationCalcule_Producteur_Records].[Code]
		,[IndexationCalcule_Producteur_Records].[UniteID]
		,[IndexationCalcule_Producteur_Records].[Volume]
		,[IndexationCalcule_Producteur_Records].[MontantDejaPaye]
		,[IndexationCalcule_Producteur_Records].[PourcentageDuMontant]
		,[IndexationCalcule_Producteur_Records].[Taux]
		,[IndexationCalcule_Producteur_Records].[Montant]
		,[IndexationCalcule_Producteur_Records].[Facture]
		,[IndexationCalcule_Producteur_Records].[FactureID]
		,[IndexationCalcule_Producteur_Records].[ErreurCalcul]
		,[IndexationCalcule_Producteur_Records].[ErreurDescription]
		,[IndexationCalcule_Producteur_Records].[TypeIndexation_ID]
		,[IndexationCalcule_Producteur_Records].[TypeIndexation_Description]
		,[IndexationCalcule_Producteur_Records].[IndexationID_ID]
		,[IndexationCalcule_Producteur_Records].[IndexationID_DateIndexation]
		,[IndexationCalcule_Producteur_Records].[IndexationID_ContratID]
		,[IndexationCalcule_Producteur_Records].[IndexationID_Periode_Debut]
		,[IndexationCalcule_Producteur_Records].[IndexationID_Periode_Fin]
		,[IndexationCalcule_Producteur_Records].[IndexationID_TypeIndexation]
		,[IndexationCalcule_Producteur_Records].[IndexationID_PourcentageDuMontant]
		,[IndexationCalcule_Producteur_Records].[IndexationID_Facture]
		,[IndexationCalcule_Producteur_Records].[IndexationID_IndexationTransporteur]
		,[IndexationCalcule_Producteur_Records].[IndexationID_Date_Debut]
		,[IndexationCalcule_Producteur_Records].[IndexationID_Date_Fin]
		,[IndexationCalcule_Producteur_Records].[IndexationID_IndexationManuelle]
		,[IndexationCalcule_Producteur_Records].[IndexationDetailID_ID]
		,[IndexationCalcule_Producteur_Records].[IndexationDetailID_IndexationID]
		,[IndexationCalcule_Producteur_Records].[IndexationDetailID_ContratID]
		,[IndexationCalcule_Producteur_Records].[IndexationDetailID_EssenceID]
		,[IndexationCalcule_Producteur_Records].[IndexationDetailID_Code]
		,[IndexationCalcule_Producteur_Records].[IndexationDetailID_UniteID]
		,[IndexationCalcule_Producteur_Records].[IndexationDetailID_Taux]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_ID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_DateLivraison]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_DatePaye]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_ContratID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_UniteMesureID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_EssenceID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Sciage]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_NumeroFactureUsine]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_DroitCoupeID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_EntentePaiementID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_TransporteurID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_VR]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_MasseLimite]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_VolumeBrut]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_VolumeTare]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_VolumeTransporte]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_VolumeSurcharge]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_VolumeAPayer]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Annee]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Periode]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_DateCalcul]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Taux_Transporteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_Transporteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_Usine]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_Producteur1]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_Producteur2]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_Preleve_Plan_Conjoint]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_Preleve_Fond_Roulement]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_Preleve_Fond_Forestier]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_Preleve_Divers]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_Surcharge]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_MiseEnCommun]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Facture]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Producteur1_FactureID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Producteur2_FactureID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Transporteur_FactureID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Usine_FactureID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_ErreurCalcul]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_ErreurDescription]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_LotID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Taux_Transporteur_Override]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_PaieTransporteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_VolumeSurcharge_Override]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_SurchargeManuel]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Code]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_NombrePermis]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_ZoneID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_MunicipaliteID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_ChargeurID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_Chargeur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_ChargeurAuProducteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_ChargeurAuTransporteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_AutresAuProducteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_AutresAuProducteurDescription]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_AutresAuTransporteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_AutresAuTransporteurDescription]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_CompensationDeDeplacement]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Chargeur_FactureID]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Commentaires_Producteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Commentaires_Transporteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Commentaires_Chargeur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_TauxChargeurAuProducteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_TauxChargeurAuTransporteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_AutresRevenusTransporteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_AutresRevenusTransporteurDescription]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_AutresRevenusProducteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Frais_AutresRevenusProducteurDescription]
		,[IndexationCalcule_Producteur_Records].[LivraisonID_Montant_SurchargeProducteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_ID]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_LivraisonID]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_ContratID]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_EssenceID]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_UniteMesureID]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_ProducteurID]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Droit_Coupe]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_VolumeBrut]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_VolumeReduction]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_VolumeNet]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_VolumeContingente]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_ContingentementID]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_DateCalcul]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Taux_Usine]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Montant_Usine]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Taux_Producteur]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Montant_ProducteurBrut]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Taux_TransporteurMoyen]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Taux_TransporteurMoyen_Override]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Montant_TransporteurMoyen]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Taux_Preleve_Plan_Conjoint]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Montant_Preleve_Plan_Conjoint]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Taux_Preleve_Fond_Roulement]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Montant_Preleve_Fond_Roulement]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Taux_Preleve_Fond_Forestier]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Montant_Preleve_Fond_Forestier]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Taux_Preleve_Divers]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Montant_Preleve_Divers]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Montant_ProducteurNet]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Taux_Producteur_Override]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Taux_Usine_Override]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_Code]
		,[IndexationCalcule_Producteur_Records].[LivraisonDetailID_UsePreleveMontant]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_ID]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_CleTri]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Nom]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_AuSoinsDe]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Rue]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Ville]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_PaysID]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Code_postal]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Telephone]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Telephone_Poste]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Telecopieur]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Telephone2]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Telephone2_Desc]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Telephone2_Poste]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Telephone3]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Telephone3_Desc]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Telephone3_Poste]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_No_membre]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Resident]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Email]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_WWW]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Commentaires]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_AfficherCommentaires]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_DepotDirect]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_InstitutionBanquaireID]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Banque_transit]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Banque_folio]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_No_TPS]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_No_TVQ]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_PayerA]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_PayerAID]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Statut]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Rep_Nom]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Rep_Telephone]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Rep_Telephone_Poste]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Rep_Email]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_EnAnglais]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Actif]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_MRCProducteurID]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_PaiementManuel]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Journal]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_RecoitTPS]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_RecoitTVQ]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_ModifierTrigger]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_IsProducteur]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_IsTransporteur]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_IsChargeur]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_IsAutre]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_AfficherCommentairesSurPermit]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_PasEmissionPermis]
		,[IndexationCalcule_Producteur_Records].[ProducteurID_Generique]
		,[IndexationCalcule_Producteur_Records].[ContratID_ContratID]
		,[IndexationCalcule_Producteur_Records].[ContratID_EssenceID]
		,[IndexationCalcule_Producteur_Records].[ContratID_UniteID]
		,[IndexationCalcule_Producteur_Records].[ContratID_Code]
		,[IndexationCalcule_Producteur_Records].[ContratID_Quantite_prevue]
		,[IndexationCalcule_Producteur_Records].[ContratID_Taux_usine]
		,[IndexationCalcule_Producteur_Records].[ContratID_Taux_producteur]
		,[IndexationCalcule_Producteur_Records].[ContratID_Actif]
		,[IndexationCalcule_Producteur_Records].[ContratID_Description]
		,[IndexationCalcule_Producteur_Records].[EssenceID_ContratID]
		,[IndexationCalcule_Producteur_Records].[EssenceID_EssenceID]
		,[IndexationCalcule_Producteur_Records].[EssenceID_UniteID]
		,[IndexationCalcule_Producteur_Records].[EssenceID_Code]
		,[IndexationCalcule_Producteur_Records].[EssenceID_Quantite_prevue]
		,[IndexationCalcule_Producteur_Records].[EssenceID_Taux_usine]
		,[IndexationCalcule_Producteur_Records].[EssenceID_Taux_producteur]
		,[IndexationCalcule_Producteur_Records].[EssenceID_Actif]
		,[IndexationCalcule_Producteur_Records].[EssenceID_Description]
		,[IndexationCalcule_Producteur_Records].[Code_ContratID]
		,[IndexationCalcule_Producteur_Records].[Code_EssenceID]
		,[IndexationCalcule_Producteur_Records].[Code_UniteID]
		,[IndexationCalcule_Producteur_Records].[Code_Code]
		,[IndexationCalcule_Producteur_Records].[Code_Quantite_prevue]
		,[IndexationCalcule_Producteur_Records].[Code_Taux_usine]
		,[IndexationCalcule_Producteur_Records].[Code_Taux_producteur]
		,[IndexationCalcule_Producteur_Records].[Code_Actif]
		,[IndexationCalcule_Producteur_Records].[Code_Description]
		,[IndexationCalcule_Producteur_Records].[UniteID_ContratID]
		,[IndexationCalcule_Producteur_Records].[UniteID_EssenceID]
		,[IndexationCalcule_Producteur_Records].[UniteID_UniteID]
		,[IndexationCalcule_Producteur_Records].[UniteID_Code]
		,[IndexationCalcule_Producteur_Records].[UniteID_Quantite_prevue]
		,[IndexationCalcule_Producteur_Records].[UniteID_Taux_usine]
		,[IndexationCalcule_Producteur_Records].[UniteID_Taux_producteur]
		,[IndexationCalcule_Producteur_Records].[UniteID_Actif]
		,[IndexationCalcule_Producteur_Records].[UniteID_Description]
		,[IndexationCalcule_Producteur_Records].[FactureID_ID]
		,[IndexationCalcule_Producteur_Records].[FactureID_NoFacture]
		,[IndexationCalcule_Producteur_Records].[FactureID_DateFacture]
		,[IndexationCalcule_Producteur_Records].[FactureID_Annee]
		,[IndexationCalcule_Producteur_Records].[FactureID_TypeFactureFournisseur]
		,[IndexationCalcule_Producteur_Records].[FactureID_TypeFacture]
		,[IndexationCalcule_Producteur_Records].[FactureID_TypeInvoiceAcomba]
		,[IndexationCalcule_Producteur_Records].[FactureID_FournisseurID]
		,[IndexationCalcule_Producteur_Records].[FactureID_PayerAID]
		,[IndexationCalcule_Producteur_Records].[FactureID_Montant_Total]
		,[IndexationCalcule_Producteur_Records].[FactureID_Montant_TPS]
		,[IndexationCalcule_Producteur_Records].[FactureID_Montant_TVQ]
		,[IndexationCalcule_Producteur_Records].[FactureID_Description]
		,[IndexationCalcule_Producteur_Records].[FactureID_Status]
		,[IndexationCalcule_Producteur_Records].[FactureID_StatusDescription]
		,[IndexationCalcule_Producteur_Records].[FactureID_NumeroCheque]
		,[IndexationCalcule_Producteur_Records].[FactureID_NumeroPaiement]
		,[IndexationCalcule_Producteur_Records].[FactureID_NumeroPaiementUnique]
		,[IndexationCalcule_Producteur_Records].[FactureID_DateFactureAcomba]
		,[IndexationCalcule_Producteur_Records].[FactureID_DatePaiementAcomba]

		From [fnIndexationCalcule_Producteur_Full](@ID, @TypeIndexation, @IndexationID, @IndexationDetailID, @LivraisonID, @LivraisonDetailID, @ProducteurID, @ContratID, @EssenceID, @Code, @UniteID, @FactureID) As [IndexationCalcule_Producteur_Records]

		For XML Auto, Elements, XMLData, BINARY BASE64
	End

Return(@@RowCount)


