CREATE PROCEDURE [dbo].[spS_Cert_Proprietaire_Full]
@Agence VARCHAR (10)=Null, @NO_ACT VARCHAR (10)=Null, @FournisseurID VARCHAR (15)=Null, @ReturnXML BIT=0
AS
If @ReturnXML Is Null
	Set @ReturnXML = 0

If @ReturnXML = 0
	Begin
		Select

		 [Cert_Proprietaire_Records].[Agence]
		,[Cert_Proprietaire_Records].[NO_ACT]
		,[Cert_Proprietaire_Records].[Nom]
		,[Cert_Proprietaire_Records].[Representant]
		,[Cert_Proprietaire_Records].[ADRESSE]
		,[Cert_Proprietaire_Records].[Ville]
		,[Cert_Proprietaire_Records].[CODE_POST]
		,[Cert_Proprietaire_Records].[TEL_RES]
		,[Cert_Proprietaire_Records].[TEL_BUR]
		,[Cert_Proprietaire_Records].[FournisseurID]
		,[Cert_Proprietaire_Records].[FournisseurNom]
		,[Cert_Proprietaire_Records].[Traite]
		,[Cert_Proprietaire_Records].[Methode]
		,[Cert_Proprietaire_Records].[FournisseurID_ID]
		,[Cert_Proprietaire_Records].[FournisseurID_CleTri]
		,[Cert_Proprietaire_Records].[FournisseurID_Nom]
		,[Cert_Proprietaire_Records].[FournisseurID_AuSoinsDe]
		,[Cert_Proprietaire_Records].[FournisseurID_Rue]
		,[Cert_Proprietaire_Records].[FournisseurID_Ville]
		,[Cert_Proprietaire_Records].[FournisseurID_PaysID]
		,[Cert_Proprietaire_Records].[FournisseurID_Code_postal]
		,[Cert_Proprietaire_Records].[FournisseurID_Telephone]
		,[Cert_Proprietaire_Records].[FournisseurID_Telephone_Poste]
		,[Cert_Proprietaire_Records].[FournisseurID_Telecopieur]
		,[Cert_Proprietaire_Records].[FournisseurID_Telephone2]
		,[Cert_Proprietaire_Records].[FournisseurID_Telephone2_Desc]
		,[Cert_Proprietaire_Records].[FournisseurID_Telephone2_Poste]
		,[Cert_Proprietaire_Records].[FournisseurID_Telephone3]
		,[Cert_Proprietaire_Records].[FournisseurID_Telephone3_Desc]
		,[Cert_Proprietaire_Records].[FournisseurID_Telephone3_Poste]
		,[Cert_Proprietaire_Records].[FournisseurID_No_membre]
		,[Cert_Proprietaire_Records].[FournisseurID_Resident]
		,[Cert_Proprietaire_Records].[FournisseurID_Email]
		,[Cert_Proprietaire_Records].[FournisseurID_WWW]
		,[Cert_Proprietaire_Records].[FournisseurID_Commentaires]
		,[Cert_Proprietaire_Records].[FournisseurID_AfficherCommentaires]
		,[Cert_Proprietaire_Records].[FournisseurID_DepotDirect]
		,[Cert_Proprietaire_Records].[FournisseurID_InstitutionBanquaireID]
		,[Cert_Proprietaire_Records].[FournisseurID_Banque_transit]
		,[Cert_Proprietaire_Records].[FournisseurID_Banque_folio]
		,[Cert_Proprietaire_Records].[FournisseurID_No_TPS]
		,[Cert_Proprietaire_Records].[FournisseurID_No_TVQ]
		,[Cert_Proprietaire_Records].[FournisseurID_PayerA]
		,[Cert_Proprietaire_Records].[FournisseurID_PayerAID]
		,[Cert_Proprietaire_Records].[FournisseurID_Statut]
		,[Cert_Proprietaire_Records].[FournisseurID_Rep_Nom]
		,[Cert_Proprietaire_Records].[FournisseurID_Rep_Telephone]
		,[Cert_Proprietaire_Records].[FournisseurID_Rep_Telephone_Poste]
		,[Cert_Proprietaire_Records].[FournisseurID_Rep_Email]
		,[Cert_Proprietaire_Records].[FournisseurID_EnAnglais]
		,[Cert_Proprietaire_Records].[FournisseurID_Actif]
		,[Cert_Proprietaire_Records].[FournisseurID_MRCProducteurID]
		,[Cert_Proprietaire_Records].[FournisseurID_PaiementManuel]
		,[Cert_Proprietaire_Records].[FournisseurID_Journal]
		,[Cert_Proprietaire_Records].[FournisseurID_RecoitTPS]
		,[Cert_Proprietaire_Records].[FournisseurID_RecoitTVQ]
		,[Cert_Proprietaire_Records].[FournisseurID_ModifierTrigger]
		,[Cert_Proprietaire_Records].[FournisseurID_IsProducteur]
		,[Cert_Proprietaire_Records].[FournisseurID_IsTransporteur]
		,[Cert_Proprietaire_Records].[FournisseurID_IsChargeur]
		,[Cert_Proprietaire_Records].[FournisseurID_IsAutre]
		,[Cert_Proprietaire_Records].[FournisseurID_AfficherCommentairesSurPermit]
		,[Cert_Proprietaire_Records].[FournisseurID_PasEmissionPermis]
		,[Cert_Proprietaire_Records].[FournisseurID_Generique]
		,[Cert_Proprietaire_Records].[FournisseurID_Membre_OGC]
		,[Cert_Proprietaire_Records].[FournisseurID_InscritTPS]
		,[Cert_Proprietaire_Records].[FournisseurID_InscritTVQ]
		,[Cert_Proprietaire_Records].[FournisseurID_IsOGC]

		From [fnCert_Proprietaire_Full](@Agence, @NO_ACT, @FournisseurID) As [Cert_Proprietaire_Records]
	End

Else

	Begin
		Select

		 [Cert_Proprietaire_Records].[Agence]
		,[Cert_Proprietaire_Records].[NO_ACT]
		,[Cert_Proprietaire_Records].[Nom]
		,[Cert_Proprietaire_Records].[Representant]
		,[Cert_Proprietaire_Records].[ADRESSE]
		,[Cert_Proprietaire_Records].[Ville]
		,[Cert_Proprietaire_Records].[CODE_POST]
		,[Cert_Proprietaire_Records].[TEL_RES]
		,[Cert_Proprietaire_Records].[TEL_BUR]
		,[Cert_Proprietaire_Records].[FournisseurID]
		,[Cert_Proprietaire_Records].[FournisseurNom]
		,[Cert_Proprietaire_Records].[Traite]
		,[Cert_Proprietaire_Records].[Methode]
		,[Cert_Proprietaire_Records].[FournisseurID_ID]
		,[Cert_Proprietaire_Records].[FournisseurID_CleTri]
		,[Cert_Proprietaire_Records].[FournisseurID_Nom]
		,[Cert_Proprietaire_Records].[FournisseurID_AuSoinsDe]
		,[Cert_Proprietaire_Records].[FournisseurID_Rue]
		,[Cert_Proprietaire_Records].[FournisseurID_Ville]
		,[Cert_Proprietaire_Records].[FournisseurID_PaysID]
		,[Cert_Proprietaire_Records].[FournisseurID_Code_postal]
		,[Cert_Proprietaire_Records].[FournisseurID_Telephone]
		,[Cert_Proprietaire_Records].[FournisseurID_Telephone_Poste]
		,[Cert_Proprietaire_Records].[FournisseurID_Telecopieur]
		,[Cert_Proprietaire_Records].[FournisseurID_Telephone2]
		,[Cert_Proprietaire_Records].[FournisseurID_Telephone2_Desc]
		,[Cert_Proprietaire_Records].[FournisseurID_Telephone2_Poste]
		,[Cert_Proprietaire_Records].[FournisseurID_Telephone3]
		,[Cert_Proprietaire_Records].[FournisseurID_Telephone3_Desc]
		,[Cert_Proprietaire_Records].[FournisseurID_Telephone3_Poste]
		,[Cert_Proprietaire_Records].[FournisseurID_No_membre]
		,[Cert_Proprietaire_Records].[FournisseurID_Resident]
		,[Cert_Proprietaire_Records].[FournisseurID_Email]
		,[Cert_Proprietaire_Records].[FournisseurID_WWW]
		,[Cert_Proprietaire_Records].[FournisseurID_Commentaires]
		,[Cert_Proprietaire_Records].[FournisseurID_AfficherCommentaires]
		,[Cert_Proprietaire_Records].[FournisseurID_DepotDirect]
		,[Cert_Proprietaire_Records].[FournisseurID_InstitutionBanquaireID]
		,[Cert_Proprietaire_Records].[FournisseurID_Banque_transit]
		,[Cert_Proprietaire_Records].[FournisseurID_Banque_folio]
		,[Cert_Proprietaire_Records].[FournisseurID_No_TPS]
		,[Cert_Proprietaire_Records].[FournisseurID_No_TVQ]
		,[Cert_Proprietaire_Records].[FournisseurID_PayerA]
		,[Cert_Proprietaire_Records].[FournisseurID_PayerAID]
		,[Cert_Proprietaire_Records].[FournisseurID_Statut]
		,[Cert_Proprietaire_Records].[FournisseurID_Rep_Nom]
		,[Cert_Proprietaire_Records].[FournisseurID_Rep_Telephone]
		,[Cert_Proprietaire_Records].[FournisseurID_Rep_Telephone_Poste]
		,[Cert_Proprietaire_Records].[FournisseurID_Rep_Email]
		,[Cert_Proprietaire_Records].[FournisseurID_EnAnglais]
		,[Cert_Proprietaire_Records].[FournisseurID_Actif]
		,[Cert_Proprietaire_Records].[FournisseurID_MRCProducteurID]
		,[Cert_Proprietaire_Records].[FournisseurID_PaiementManuel]
		,[Cert_Proprietaire_Records].[FournisseurID_Journal]
		,[Cert_Proprietaire_Records].[FournisseurID_RecoitTPS]
		,[Cert_Proprietaire_Records].[FournisseurID_RecoitTVQ]
		,[Cert_Proprietaire_Records].[FournisseurID_ModifierTrigger]
		,[Cert_Proprietaire_Records].[FournisseurID_IsProducteur]
		,[Cert_Proprietaire_Records].[FournisseurID_IsTransporteur]
		,[Cert_Proprietaire_Records].[FournisseurID_IsChargeur]
		,[Cert_Proprietaire_Records].[FournisseurID_IsAutre]
		,[Cert_Proprietaire_Records].[FournisseurID_AfficherCommentairesSurPermit]
		,[Cert_Proprietaire_Records].[FournisseurID_PasEmissionPermis]
		,[Cert_Proprietaire_Records].[FournisseurID_Generique]
		,[Cert_Proprietaire_Records].[FournisseurID_Membre_OGC]
		,[Cert_Proprietaire_Records].[FournisseurID_InscritTPS]
		,[Cert_Proprietaire_Records].[FournisseurID_InscritTVQ]
		,[Cert_Proprietaire_Records].[FournisseurID_IsOGC]

		From [fnCert_Proprietaire_Full](@Agence, @NO_ACT, @FournisseurID) As [Cert_Proprietaire_Records]

		For XML Auto, Elements, XMLData, BINARY BASE64
	End

Return(@@RowCount)


