

Create Procedure [spS_AjustementCalcule_Producteur_Full]

/*
Retrieve specific records from the [AjustementCalcule_Producteur] table, as well as all its foreign tables, depending on the input parameters you supply:
	[Ajustement_EssenceUnite] (via [AjustementID])
	[Ajustement_EssenceUnite] (via [EssenceID])
	[Ajustement_EssenceUnite] (via [UniteID])
	[Livraison_Detail] (via [LivraisonDetailID])
	[Fournisseur] (via [ProducteurID])
	[FactureFournisseur] (via [FactureID])
	[Ajustement_EssenceUnite] (via [Code])
*/

(
 @ID [int] = Null -- for [AjustementCalcule_Producteur].[ID] column
,@AjustementID [int] = Null -- for [AjustementCalcule_Producteur].[AjustementID] column
,@EssenceID [varchar](6) = Null -- for [AjustementCalcule_Producteur].[EssenceID] column
,@UniteID [varchar](6) = Null -- for [AjustementCalcule_Producteur].[UniteID] column
,@LivraisonDetailID [int] = Null -- for [AjustementCalcule_Producteur].[LivraisonDetailID] column
,@ProducteurID [varchar](15) = Null -- for [AjustementCalcule_Producteur].[ProducteurID] column
,@FactureID [int] = Null -- for [AjustementCalcule_Producteur].[FactureID] column
,@Code [char](4) = Null -- for [AjustementCalcule_Producteur].[Code] column
,@ReturnXML [bit] = 0 -- Indicates if we want to get back XML content instead of normal resultset (@ReturnXML = 1 to get XML back)
)

-- Returns the number of records found

As


--	IMPORTANT:
--	Changes to this SQL code may cause incorrect behavior
--	and will be lost if the code is regenerated. 


If @ReturnXML Is Null
	Set @ReturnXML = 0

If @ReturnXML = 0
	Begin
		Select

		 [AjustementCalcule_Producteur_Records].[ID]
		,[AjustementCalcule_Producteur_Records].[DateCalcul]
		,[AjustementCalcule_Producteur_Records].[AjustementID]
		,[AjustementCalcule_Producteur_Records].[EssenceID]
		,[AjustementCalcule_Producteur_Records].[UniteID]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID]
		,[AjustementCalcule_Producteur_Records].[ProducteurID]
		,[AjustementCalcule_Producteur_Records].[Volume]
		,[AjustementCalcule_Producteur_Records].[Taux]
		,[AjustementCalcule_Producteur_Records].[Montant]
		,[AjustementCalcule_Producteur_Records].[Facture]
		,[AjustementCalcule_Producteur_Records].[FactureID]
		,[AjustementCalcule_Producteur_Records].[ErreurCalcul]
		,[AjustementCalcule_Producteur_Records].[ErreurDescription]
		,[AjustementCalcule_Producteur_Records].[Code]
		,[AjustementCalcule_Producteur_Records].[AjustementID_AjustementID]
		,[AjustementCalcule_Producteur_Records].[AjustementID_EssenceID]
		,[AjustementCalcule_Producteur_Records].[AjustementID_UniteID]
		,[AjustementCalcule_Producteur_Records].[AjustementID_ContratID]
		,[AjustementCalcule_Producteur_Records].[AjustementID_Taux_usine]
		,[AjustementCalcule_Producteur_Records].[AjustementID_Taux_producteur]
		,[AjustementCalcule_Producteur_Records].[AjustementID_Date_Modification]
		,[AjustementCalcule_Producteur_Records].[AjustementID_Code]
		,[AjustementCalcule_Producteur_Records].[EssenceID_AjustementID]
		,[AjustementCalcule_Producteur_Records].[EssenceID_EssenceID]
		,[AjustementCalcule_Producteur_Records].[EssenceID_UniteID]
		,[AjustementCalcule_Producteur_Records].[EssenceID_ContratID]
		,[AjustementCalcule_Producteur_Records].[EssenceID_Taux_usine]
		,[AjustementCalcule_Producteur_Records].[EssenceID_Taux_producteur]
		,[AjustementCalcule_Producteur_Records].[EssenceID_Date_Modification]
		,[AjustementCalcule_Producteur_Records].[EssenceID_Code]
		,[AjustementCalcule_Producteur_Records].[UniteID_AjustementID]
		,[AjustementCalcule_Producteur_Records].[UniteID_EssenceID]
		,[AjustementCalcule_Producteur_Records].[UniteID_UniteID]
		,[AjustementCalcule_Producteur_Records].[UniteID_ContratID]
		,[AjustementCalcule_Producteur_Records].[UniteID_Taux_usine]
		,[AjustementCalcule_Producteur_Records].[UniteID_Taux_producteur]
		,[AjustementCalcule_Producteur_Records].[UniteID_Date_Modification]
		,[AjustementCalcule_Producteur_Records].[UniteID_Code]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_ID]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_LivraisonID]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_ContratID]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_EssenceID]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_UniteMesureID]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_ProducteurID]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Droit_Coupe]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_VolumeBrut]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_VolumeReduction]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_VolumeNet]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_VolumeContingente]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_ContingentementID]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_DateCalcul]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Taux_Usine]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Montant_Usine]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Taux_Producteur]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Montant_ProducteurBrut]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Taux_TransporteurMoyen]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Taux_TransporteurMoyen_Override]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Montant_TransporteurMoyen]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Taux_Preleve_Plan_Conjoint]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Montant_Preleve_Plan_Conjoint]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Taux_Preleve_Fond_Roulement]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Montant_Preleve_Fond_Roulement]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Taux_Preleve_Fond_Forestier]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Montant_Preleve_Fond_Forestier]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Taux_Preleve_Divers]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Montant_Preleve_Divers]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Montant_ProducteurNet]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Taux_Producteur_Override]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Taux_Usine_Override]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Code]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_UsePreleveMontant]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_ID]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_CleTri]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Nom]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_AuSoinsDe]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Rue]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Ville]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_PaysID]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Code_postal]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Telephone]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Telephone_Poste]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Telecopieur]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Telephone2]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Telephone2_Desc]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Telephone2_Poste]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Telephone3]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Telephone3_Desc]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Telephone3_Poste]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_No_membre]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Resident]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Email]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_WWW]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Commentaires]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_AfficherCommentaires]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_DepotDirect]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_InstitutionBanquaireID]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Banque_transit]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Banque_folio]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_No_TPS]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_No_TVQ]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_PayerA]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_PayerAID]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Statut]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Rep_Nom]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Rep_Telephone]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Rep_Telephone_Poste]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Rep_Email]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_EnAnglais]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Actif]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_MRCProducteurID]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_PaiementManuel]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Journal]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_RecoitTPS]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_RecoitTVQ]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_ModifierTrigger]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_IsProducteur]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_IsTransporteur]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_IsChargeur]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_IsAutre]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_AfficherCommentairesSurPermit]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_PasEmissionPermis]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Generique]
		,[AjustementCalcule_Producteur_Records].[FactureID_ID]
		,[AjustementCalcule_Producteur_Records].[FactureID_NoFacture]
		,[AjustementCalcule_Producteur_Records].[FactureID_DateFacture]
		,[AjustementCalcule_Producteur_Records].[FactureID_Annee]
		,[AjustementCalcule_Producteur_Records].[FactureID_TypeFactureFournisseur]
		,[AjustementCalcule_Producteur_Records].[FactureID_TypeFacture]
		,[AjustementCalcule_Producteur_Records].[FactureID_TypeInvoiceAcomba]
		,[AjustementCalcule_Producteur_Records].[FactureID_FournisseurID]
		,[AjustementCalcule_Producteur_Records].[FactureID_PayerAID]
		,[AjustementCalcule_Producteur_Records].[FactureID_Montant_Total]
		,[AjustementCalcule_Producteur_Records].[FactureID_Montant_TPS]
		,[AjustementCalcule_Producteur_Records].[FactureID_Montant_TVQ]
		,[AjustementCalcule_Producteur_Records].[FactureID_Description]
		,[AjustementCalcule_Producteur_Records].[FactureID_Status]
		,[AjustementCalcule_Producteur_Records].[FactureID_StatusDescription]
		,[AjustementCalcule_Producteur_Records].[FactureID_NumeroCheque]
		,[AjustementCalcule_Producteur_Records].[FactureID_NumeroPaiement]
		,[AjustementCalcule_Producteur_Records].[FactureID_NumeroPaiementUnique]
		,[AjustementCalcule_Producteur_Records].[FactureID_DateFactureAcomba]
		,[AjustementCalcule_Producteur_Records].[FactureID_DatePaiementAcomba]
		,[AjustementCalcule_Producteur_Records].[Code_AjustementID]
		,[AjustementCalcule_Producteur_Records].[Code_EssenceID]
		,[AjustementCalcule_Producteur_Records].[Code_UniteID]
		,[AjustementCalcule_Producteur_Records].[Code_ContratID]
		,[AjustementCalcule_Producteur_Records].[Code_Taux_usine]
		,[AjustementCalcule_Producteur_Records].[Code_Taux_producteur]
		,[AjustementCalcule_Producteur_Records].[Code_Date_Modification]
		,[AjustementCalcule_Producteur_Records].[Code_Code]

		From [fnAjustementCalcule_Producteur_Full](@ID, @AjustementID, @EssenceID, @UniteID, @LivraisonDetailID, @ProducteurID, @FactureID, @Code) As [AjustementCalcule_Producteur_Records]
	End

Else

	Begin
		Select

		 [AjustementCalcule_Producteur_Records].[ID]
		,[AjustementCalcule_Producteur_Records].[DateCalcul]
		,[AjustementCalcule_Producteur_Records].[AjustementID]
		,[AjustementCalcule_Producteur_Records].[EssenceID]
		,[AjustementCalcule_Producteur_Records].[UniteID]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID]
		,[AjustementCalcule_Producteur_Records].[ProducteurID]
		,[AjustementCalcule_Producteur_Records].[Volume]
		,[AjustementCalcule_Producteur_Records].[Taux]
		,[AjustementCalcule_Producteur_Records].[Montant]
		,[AjustementCalcule_Producteur_Records].[Facture]
		,[AjustementCalcule_Producteur_Records].[FactureID]
		,[AjustementCalcule_Producteur_Records].[ErreurCalcul]
		,[AjustementCalcule_Producteur_Records].[ErreurDescription]
		,[AjustementCalcule_Producteur_Records].[Code]
		,[AjustementCalcule_Producteur_Records].[AjustementID_AjustementID]
		,[AjustementCalcule_Producteur_Records].[AjustementID_EssenceID]
		,[AjustementCalcule_Producteur_Records].[AjustementID_UniteID]
		,[AjustementCalcule_Producteur_Records].[AjustementID_ContratID]
		,[AjustementCalcule_Producteur_Records].[AjustementID_Taux_usine]
		,[AjustementCalcule_Producteur_Records].[AjustementID_Taux_producteur]
		,[AjustementCalcule_Producteur_Records].[AjustementID_Date_Modification]
		,[AjustementCalcule_Producteur_Records].[AjustementID_Code]
		,[AjustementCalcule_Producteur_Records].[EssenceID_AjustementID]
		,[AjustementCalcule_Producteur_Records].[EssenceID_EssenceID]
		,[AjustementCalcule_Producteur_Records].[EssenceID_UniteID]
		,[AjustementCalcule_Producteur_Records].[EssenceID_ContratID]
		,[AjustementCalcule_Producteur_Records].[EssenceID_Taux_usine]
		,[AjustementCalcule_Producteur_Records].[EssenceID_Taux_producteur]
		,[AjustementCalcule_Producteur_Records].[EssenceID_Date_Modification]
		,[AjustementCalcule_Producteur_Records].[EssenceID_Code]
		,[AjustementCalcule_Producteur_Records].[UniteID_AjustementID]
		,[AjustementCalcule_Producteur_Records].[UniteID_EssenceID]
		,[AjustementCalcule_Producteur_Records].[UniteID_UniteID]
		,[AjustementCalcule_Producteur_Records].[UniteID_ContratID]
		,[AjustementCalcule_Producteur_Records].[UniteID_Taux_usine]
		,[AjustementCalcule_Producteur_Records].[UniteID_Taux_producteur]
		,[AjustementCalcule_Producteur_Records].[UniteID_Date_Modification]
		,[AjustementCalcule_Producteur_Records].[UniteID_Code]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_ID]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_LivraisonID]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_ContratID]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_EssenceID]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_UniteMesureID]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_ProducteurID]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Droit_Coupe]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_VolumeBrut]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_VolumeReduction]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_VolumeNet]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_VolumeContingente]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_ContingentementID]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_DateCalcul]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Taux_Usine]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Montant_Usine]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Taux_Producteur]

		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Montant_ProducteurBrut]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Taux_TransporteurMoyen]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Taux_TransporteurMoyen_Override]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Montant_TransporteurMoyen]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Taux_Preleve_Plan_Conjoint]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Montant_Preleve_Plan_Conjoint]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Taux_Preleve_Fond_Roulement]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Montant_Preleve_Fond_Roulement]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Taux_Preleve_Fond_Forestier]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Montant_Preleve_Fond_Forestier]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Taux_Preleve_Divers]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Montant_Preleve_Divers]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Montant_ProducteurNet]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Taux_Producteur_Override]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Taux_Usine_Override]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_Code]
		,[AjustementCalcule_Producteur_Records].[LivraisonDetailID_UsePreleveMontant]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_ID]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_CleTri]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Nom]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_AuSoinsDe]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Rue]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Ville]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_PaysID]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Code_postal]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Telephone]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Telephone_Poste]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Telecopieur]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Telephone2]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Telephone2_Desc]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Telephone2_Poste]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Telephone3]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Telephone3_Desc]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Telephone3_Poste]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_No_membre]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Resident]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Email]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_WWW]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Commentaires]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_AfficherCommentaires]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_DepotDirect]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_InstitutionBanquaireID]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Banque_transit]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Banque_folio]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_No_TPS]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_No_TVQ]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_PayerA]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_PayerAID]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Statut]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Rep_Nom]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Rep_Telephone]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Rep_Telephone_Poste]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Rep_Email]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_EnAnglais]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Actif]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_MRCProducteurID]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_PaiementManuel]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Journal]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_RecoitTPS]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_RecoitTVQ]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_ModifierTrigger]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_IsProducteur]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_IsTransporteur]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_IsChargeur]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_IsAutre]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_AfficherCommentairesSurPermit]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_PasEmissionPermis]
		,[AjustementCalcule_Producteur_Records].[ProducteurID_Generique]
		,[AjustementCalcule_Producteur_Records].[FactureID_ID]
		,[AjustementCalcule_Producteur_Records].[FactureID_NoFacture]
		,[AjustementCalcule_Producteur_Records].[FactureID_DateFacture]
		,[AjustementCalcule_Producteur_Records].[FactureID_Annee]
		,[AjustementCalcule_Producteur_Records].[FactureID_TypeFactureFournisseur]
		,[AjustementCalcule_Producteur_Records].[FactureID_TypeFacture]
		,[AjustementCalcule_Producteur_Records].[FactureID_TypeInvoiceAcomba]
		,[AjustementCalcule_Producteur_Records].[FactureID_FournisseurID]
		,[AjustementCalcule_Producteur_Records].[FactureID_PayerAID]
		,[AjustementCalcule_Producteur_Records].[FactureID_Montant_Total]
		,[AjustementCalcule_Producteur_Records].[FactureID_Montant_TPS]
		,[AjustementCalcule_Producteur_Records].[FactureID_Montant_TVQ]
		,[AjustementCalcule_Producteur_Records].[FactureID_Description]
		,[AjustementCalcule_Producteur_Records].[FactureID_Status]
		,[AjustementCalcule_Producteur_Records].[FactureID_StatusDescription]
		,[AjustementCalcule_Producteur_Records].[FactureID_NumeroCheque]
		,[AjustementCalcule_Producteur_Records].[FactureID_NumeroPaiement]
		,[AjustementCalcule_Producteur_Records].[FactureID_NumeroPaiementUnique]
		,[AjustementCalcule_Producteur_Records].[FactureID_DateFactureAcomba]
		,[AjustementCalcule_Producteur_Records].[FactureID_DatePaiementAcomba]
		,[AjustementCalcule_Producteur_Records].[Code_AjustementID]
		,[AjustementCalcule_Producteur_Records].[Code_EssenceID]
		,[AjustementCalcule_Producteur_Records].[Code_UniteID]
		,[AjustementCalcule_Producteur_Records].[Code_ContratID]
		,[AjustementCalcule_Producteur_Records].[Code_Taux_usine]
		,[AjustementCalcule_Producteur_Records].[Code_Taux_producteur]
		,[AjustementCalcule_Producteur_Records].[Code_Date_Modification]
		,[AjustementCalcule_Producteur_Records].[Code_Code]

		From [fnAjustementCalcule_Producteur_Full](@ID, @AjustementID, @EssenceID, @UniteID, @LivraisonDetailID, @ProducteurID, @FactureID, @Code) As [AjustementCalcule_Producteur_Records]

		For XML Auto, Elements, XMLData, BINARY BASE64
	End

Return(@@RowCount)


