

Create Procedure [spS_AjustementCalcule_Usine_Full]

/*
Retrieve specific records from the [AjustementCalcule_Usine] table, as well as all its foreign tables, depending on the input parameters you supply:
	[Ajustement_EssenceUnite] (via [AjustementID])
	[Ajustement_EssenceUnite] (via [EssenceID])
	[Ajustement_EssenceUnite] (via [UniteID])
	[Livraison_Detail] (via [LivraisonDetailID])
	[Usine] (via [UsineID])
	[FactureClient] (via [FactureID])
	[Ajustement_EssenceUnite] (via [Code])
*/

(
 @ID [int] = Null -- for [AjustementCalcule_Usine].[ID] column
,@AjustementID [int] = Null -- for [AjustementCalcule_Usine].[AjustementID] column
,@EssenceID [varchar](6) = Null -- for [AjustementCalcule_Usine].[EssenceID] column
,@UniteID [varchar](6) = Null -- for [AjustementCalcule_Usine].[UniteID] column
,@LivraisonDetailID [int] = Null -- for [AjustementCalcule_Usine].[LivraisonDetailID] column
,@UsineID [varchar](6) = Null -- for [AjustementCalcule_Usine].[UsineID] column
,@FactureID [int] = Null -- for [AjustementCalcule_Usine].[FactureID] column
,@Code [char](4) = Null -- for [AjustementCalcule_Usine].[Code] column
,@ReturnXML [bit] = 0 -- Indicates if we want to get back XML content instead of normal resultset (@ReturnXML = 1 to get XML back)
)

-- Returns the number of records found

As


--	IMPORTANT:
--	Changes to this SQL code may cause incorrect behavior
--	and will be lost if the code is regenerated. 


If @ReturnXML Is Null
	Set @ReturnXML = 0

If @ReturnXML = 0
	Begin
		Select

		 [AjustementCalcule_Usine_Records].[ID]
		,[AjustementCalcule_Usine_Records].[DateCalcul]
		,[AjustementCalcule_Usine_Records].[AjustementID]
		,[AjustementCalcule_Usine_Records].[EssenceID]
		,[AjustementCalcule_Usine_Records].[UniteID]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID]
		,[AjustementCalcule_Usine_Records].[UsineID]
		,[AjustementCalcule_Usine_Records].[Volume]
		,[AjustementCalcule_Usine_Records].[Taux]
		,[AjustementCalcule_Usine_Records].[Montant]
		,[AjustementCalcule_Usine_Records].[Facture]
		,[AjustementCalcule_Usine_Records].[FactureID]
		,[AjustementCalcule_Usine_Records].[ErreurCalcul]
		,[AjustementCalcule_Usine_Records].[ErreurDescription]
		,[AjustementCalcule_Usine_Records].[Code]
		,[AjustementCalcule_Usine_Records].[AjustementID_AjustementID]
		,[AjustementCalcule_Usine_Records].[AjustementID_EssenceID]
		,[AjustementCalcule_Usine_Records].[AjustementID_UniteID]
		,[AjustementCalcule_Usine_Records].[AjustementID_ContratID]
		,[AjustementCalcule_Usine_Records].[AjustementID_Taux_usine]
		,[AjustementCalcule_Usine_Records].[AjustementID_Taux_producteur]
		,[AjustementCalcule_Usine_Records].[AjustementID_Date_Modification]
		,[AjustementCalcule_Usine_Records].[AjustementID_Code]
		,[AjustementCalcule_Usine_Records].[EssenceID_AjustementID]
		,[AjustementCalcule_Usine_Records].[EssenceID_EssenceID]
		,[AjustementCalcule_Usine_Records].[EssenceID_UniteID]
		,[AjustementCalcule_Usine_Records].[EssenceID_ContratID]
		,[AjustementCalcule_Usine_Records].[EssenceID_Taux_usine]
		,[AjustementCalcule_Usine_Records].[EssenceID_Taux_producteur]
		,[AjustementCalcule_Usine_Records].[EssenceID_Date_Modification]
		,[AjustementCalcule_Usine_Records].[EssenceID_Code]
		,[AjustementCalcule_Usine_Records].[UniteID_AjustementID]
		,[AjustementCalcule_Usine_Records].[UniteID_EssenceID]
		,[AjustementCalcule_Usine_Records].[UniteID_UniteID]
		,[AjustementCalcule_Usine_Records].[UniteID_ContratID]
		,[AjustementCalcule_Usine_Records].[UniteID_Taux_usine]
		,[AjustementCalcule_Usine_Records].[UniteID_Taux_producteur]
		,[AjustementCalcule_Usine_Records].[UniteID_Date_Modification]
		,[AjustementCalcule_Usine_Records].[UniteID_Code]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_ID]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_LivraisonID]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_ContratID]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_EssenceID]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_UniteMesureID]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_ProducteurID]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Droit_Coupe]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_VolumeBrut]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_VolumeReduction]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_VolumeNet]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_VolumeContingente]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_ContingentementID]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_DateCalcul]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Taux_Usine]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Montant_Usine]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Taux_Producteur]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Montant_ProducteurBrut]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Taux_TransporteurMoyen]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Taux_TransporteurMoyen_Override]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Montant_TransporteurMoyen]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Taux_Preleve_Plan_Conjoint]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Montant_Preleve_Plan_Conjoint]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Taux_Preleve_Fond_Roulement]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Montant_Preleve_Fond_Roulement]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Taux_Preleve_Fond_Forestier]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Montant_Preleve_Fond_Forestier]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Taux_Preleve_Divers]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Montant_Preleve_Divers]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Montant_ProducteurNet]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Taux_Producteur_Override]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Taux_Usine_Override]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Code]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_UsePreleveMontant]
		,[AjustementCalcule_Usine_Records].[UsineID_ID]
		,[AjustementCalcule_Usine_Records].[UsineID_Description]
		,[AjustementCalcule_Usine_Records].[UsineID_UtilisationID]
		,[AjustementCalcule_Usine_Records].[UsineID_Paye_producteur]
		,[AjustementCalcule_Usine_Records].[UsineID_Paye_transporteur]
		,[AjustementCalcule_Usine_Records].[UsineID_Specification]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_a_recevoir]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_ajustement]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_transporteur]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_producteur]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_preleve_plan_conjoint]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_preleve_fond_roulement]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_preleve_fond_forestier]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_preleve_divers]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_mise_en_commun]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_surcharge]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_indexation_carburant]
		,[AjustementCalcule_Usine_Records].[UsineID_Actif]
		,[AjustementCalcule_Usine_Records].[UsineID_NePaiePasTPS]
		,[AjustementCalcule_Usine_Records].[UsineID_NePaiePasTVQ]
		,[AjustementCalcule_Usine_Records].[UsineID_NoTPS]
		,[AjustementCalcule_Usine_Records].[UsineID_NoTVQ]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_chargeur]
		,[AjustementCalcule_Usine_Records].[UsineID_UsineGestionVolume]
		,[AjustementCalcule_Usine_Records].[UsineID_AuSoinsDe]
		,[AjustementCalcule_Usine_Records].[UsineID_Rue]
		,[AjustementCalcule_Usine_Records].[UsineID_Ville]
		,[AjustementCalcule_Usine_Records].[UsineID_PaysID]
		,[AjustementCalcule_Usine_Records].[UsineID_Code_postal]
		,[AjustementCalcule_Usine_Records].[UsineID_Telephone]
		,[AjustementCalcule_Usine_Records].[UsineID_Telephone_Poste]
		,[AjustementCalcule_Usine_Records].[UsineID_Telecopieur]
		,[AjustementCalcule_Usine_Records].[UsineID_Telephone2]
		,[AjustementCalcule_Usine_Records].[UsineID_Telephone2_Desc]
		,[AjustementCalcule_Usine_Records].[UsineID_Telephone2_Poste]
		,[AjustementCalcule_Usine_Records].[UsineID_Telephone3]
		,[AjustementCalcule_Usine_Records].[UsineID_Telephone3_Desc]
		,[AjustementCalcule_Usine_Records].[UsineID_Telephone3_Poste]
		,[AjustementCalcule_Usine_Records].[UsineID_Email]
		,[AjustementCalcule_Usine_Records].[FactureID_ID]
		,[AjustementCalcule_Usine_Records].[FactureID_NoFacture]
		,[AjustementCalcule_Usine_Records].[FactureID_DateFacture]
		,[AjustementCalcule_Usine_Records].[FactureID_Annee]
		,[AjustementCalcule_Usine_Records].[FactureID_TypeFacture]
		,[AjustementCalcule_Usine_Records].[FactureID_TypeInvoiceClientAcomba]
		,[AjustementCalcule_Usine_Records].[FactureID_ClientID]
		,[AjustementCalcule_Usine_Records].[FactureID_PayerAID]
		,[AjustementCalcule_Usine_Records].[FactureID_Montant_Total]
		,[AjustementCalcule_Usine_Records].[FactureID_Montant_TPS]
		,[AjustementCalcule_Usine_Records].[FactureID_Montant_TVQ]
		,[AjustementCalcule_Usine_Records].[FactureID_Description]
		,[AjustementCalcule_Usine_Records].[FactureID_Status]
		,[AjustementCalcule_Usine_Records].[FactureID_StatusDescription]
		,[AjustementCalcule_Usine_Records].[FactureID_DateFactureAcomba]
		,[AjustementCalcule_Usine_Records].[Code_AjustementID]
		,[AjustementCalcule_Usine_Records].[Code_EssenceID]
		,[AjustementCalcule_Usine_Records].[Code_UniteID]
		,[AjustementCalcule_Usine_Records].[Code_ContratID]
		,[AjustementCalcule_Usine_Records].[Code_Taux_usine]
		,[AjustementCalcule_Usine_Records].[Code_Taux_producteur]
		,[AjustementCalcule_Usine_Records].[Code_Date_Modification]
		,[AjustementCalcule_Usine_Records].[Code_Code]

		From [fnAjustementCalcule_Usine_Full](@ID, @AjustementID, @EssenceID, @UniteID, @LivraisonDetailID, @UsineID, @FactureID, @Code) As [AjustementCalcule_Usine_Records]
	End

Else

	Begin
		Select

		 [AjustementCalcule_Usine_Records].[ID]
		,[AjustementCalcule_Usine_Records].[DateCalcul]
		,[AjustementCalcule_Usine_Records].[AjustementID]
		,[AjustementCalcule_Usine_Records].[EssenceID]
		,[AjustementCalcule_Usine_Records].[UniteID]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID]
		,[AjustementCalcule_Usine_Records].[UsineID]
		,[AjustementCalcule_Usine_Records].[Volume]
		,[AjustementCalcule_Usine_Records].[Taux]
		,[AjustementCalcule_Usine_Records].[Montant]
		,[AjustementCalcule_Usine_Records].[Facture]
		,[AjustementCalcule_Usine_Records].[FactureID]
		,[AjustementCalcule_Usine_Records].[ErreurCalcul]
		,[AjustementCalcule_Usine_Records].[ErreurDescription]
		,[AjustementCalcule_Usine_Records].[Code]
		,[AjustementCalcule_Usine_Records].[AjustementID_AjustementID]
		,[AjustementCalcule_Usine_Records].[AjustementID_EssenceID]
		,[AjustementCalcule_Usine_Records].[AjustementID_UniteID]
		,[AjustementCalcule_Usine_Records].[AjustementID_ContratID]
		,[AjustementCalcule_Usine_Records].[AjustementID_Taux_usine]
		,[AjustementCalcule_Usine_Records].[AjustementID_Taux_producteur]
		,[AjustementCalcule_Usine_Records].[AjustementID_Date_Modification]
		,[AjustementCalcule_Usine_Records].[AjustementID_Code]
		,[AjustementCalcule_Usine_Records].[EssenceID_AjustementID]
		,[AjustementCalcule_Usine_Records].[EssenceID_EssenceID]
		,[AjustementCalcule_Usine_Records].[EssenceID_UniteID]
		,[AjustementCalcule_Usine_Records].[EssenceID_ContratID]
		,[AjustementCalcule_Usine_Records].[EssenceID_Taux_usine]
		,[AjustementCalcule_Usine_Records].[EssenceID_Taux_producteur]
		,[AjustementCalcule_Usine_Records].[EssenceID_Date_Modification]
		,[AjustementCalcule_Usine_Records].[EssenceID_Code]
		,[AjustementCalcule_Usine_Records].[UniteID_AjustementID]
		,[AjustementCalcule_Usine_Records].[UniteID_EssenceID]
		,[AjustementCalcule_Usine_Records].[UniteID_UniteID]
		,[AjustementCalcule_Usine_Records].[UniteID_ContratID]
		,[AjustementCalcule_Usine_Records].[UniteID_Taux_usine]
		,[AjustementCalcule_Usine_Records].[UniteID_Taux_producteur]
		,[AjustementCalcule_Usine_Records].[UniteID_Date_Modification]
		,[AjustementCalcule_Usine_Records].[UniteID_Code]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_ID]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_LivraisonID]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_ContratID]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_EssenceID]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_UniteMesureID]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_ProducteurID]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Droit_Coupe]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_VolumeBrut]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_VolumeReduction]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_VolumeNet]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_VolumeContingente]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_ContingentementID]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_DateCalcul]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Taux_Usine]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Montant_Usine]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Taux_Producteur]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Montant_ProducteurBrut]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Taux_TransporteurMoyen]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Taux_TransporteurMoyen_Override]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Montant_TransporteurMoyen]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Taux_Preleve_Plan_Conjoint]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Montant_Preleve_Plan_Conjoint]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Taux_Preleve_Fond_Roulement]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Montant_Preleve_Fond_Roulement]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Taux_Preleve_Fond_Forestier]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Montant_Preleve_Fond_Forestier]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Taux_Preleve_Divers]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Montant_Preleve_Divers]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Montant_ProducteurNet]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Taux_Producteur_Override]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Taux_Usine_Override]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_Code]
		,[AjustementCalcule_Usine_Records].[LivraisonDetailID_UsePreleveMontant]
		,[AjustementCalcule_Usine_Records].[UsineID_ID]
		,[AjustementCalcule_Usine_Records].[UsineID_Description]
		,[AjustementCalcule_Usine_Records].[UsineID_UtilisationID]
		,[AjustementCalcule_Usine_Records].[UsineID_Paye_producteur]
		,[AjustementCalcule_Usine_Records].[UsineID_Paye_transporteur]
		,[AjustementCalcule_Usine_Records].[UsineID_Specification]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_a_recevoir]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_ajustement]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_transporteur]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_producteur]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_preleve_plan_conjoint]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_preleve_fond_roulement]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_preleve_fond_forestier]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_preleve_divers]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_mise_en_commun]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_surcharge]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_indexation_carburant]
		,[AjustementCalcule_Usine_Records].[UsineID_Actif]
		,[AjustementCalcule_Usine_Records].[UsineID_NePaiePasTPS]
		,[AjustementCalcule_Usine_Records].[UsineID_NePaiePasTVQ]
		,[AjustementCalcule_Usine_Records].[UsineID_NoTPS]
		,[AjustementCalcule_Usine_Records].[UsineID_NoTVQ]
		,[AjustementCalcule_Usine_Records].[UsineID_Compte_chargeur]
		,[AjustementCalcule_Usine_Records].[UsineID_UsineGestionVolume]
		,[AjustementCalcule_Usine_Records].[UsineID_AuSoinsDe]
		,[AjustementCalcule_Usine_Records].[UsineID_Rue]
		,[AjustementCalcule_Usine_Records].[UsineID_Ville]
		,[AjustementCalcule_Usine_Records].[UsineID_PaysID]
		,[AjustementCalcule_Usine_Records].[UsineID_Code_postal]
		,[AjustementCalcule_Usine_Records].[UsineID_Telephone]
		,[AjustementCalcule_Usine_Records].[UsineID_Telephone_Poste]
		,[AjustementCalcule_Usine_Records].[UsineID_Telecopieur]
		,[AjustementCalcule_Usine_Records].[UsineID_Telephone2]
		,[AjustementCalcule_Usine_Records].[UsineID_Telephone2_Desc]
		,[AjustementCalcule_Usine_Records].[UsineID_Telephone2_Poste]
		,[AjustementCalcule_Usine_Records].[UsineID_Telephone3]
		,[AjustementCalcule_Usine_Records].[UsineID_Telephone3_Desc]
		,[AjustementCalcule_Usine_Records].[UsineID_Telephone3_Poste]
		,[AjustementCalcule_Usine_Records].[UsineID_Email]
		,[AjustementCalcule_Usine_Records].[FactureID_ID]
		,[AjustementCalcule_Usine_Records].[FactureID_NoFacture]
		,[AjustementCalcule_Usine_Records].[FactureID_DateFacture]
		,[AjustementCalcule_Usine_Records].[FactureID_Annee]
		,[AjustementCalcule_Usine_Records].[FactureID_TypeFacture]
		,[AjustementCalcule_Usine_Records].[FactureID_TypeInvoiceClientAcomba]
		,[AjustementCalcule_Usine_Records].[FactureID_ClientID]
		,[AjustementCalcule_Usine_Records].[FactureID_PayerAID]
		,[AjustementCalcule_Usine_Records].[FactureID_Montant_Total]
		,[AjustementCalcule_Usine_Records].[FactureID_Montant_TPS]
		,[AjustementCalcule_Usine_Records].[FactureID_Montant_TVQ]
		,[AjustementCalcule_Usine_Records].[FactureID_Description]
		,[AjustementCalcule_Usine_Records].[FactureID_Status]
		,[AjustementCalcule_Usine_Records].[FactureID_StatusDescription]
		,[AjustementCalcule_Usine_Records].[FactureID_DateFactureAcomba]
		,[AjustementCalcule_Usine_Records].[Code_AjustementID]
		,[AjustementCalcule_Usine_Records].[Code_EssenceID]
		,[AjustementCalcule_Usine_Records].[Code_UniteID]
		,[AjustementCalcule_Usine_Records].[Code_ContratID]
		,[AjustementCalcule_Usine_Records].[Code_Taux_usine]
		,[AjustementCalcule_Usine_Records].[Code_Taux_producteur]
		,[AjustementCalcule_Usine_Records].[Code_Date_Modification]
		,[AjustementCalcule_Usine_Records].[Code_Code]

		From [fnAjustementCalcule_Usine_Full](@ID, @AjustementID, @EssenceID, @UniteID, @LivraisonDetailID, @UsineID, @FactureID, @Code) As [AjustementCalcule_Usine_Records]

		For XML Auto, Elements, XMLData, BINARY BASE64
	End

Return(@@RowCount)


