
CREATE Procedure [spS_Contingentement_Demande_Full]

/*
Retrieve specific records from the [Contingentement_Demande] table, as well as all its foreign tables, depending on the input parameters you supply:
	[Fournisseur] (via [ProducteurID])
	[Fournisseur] (via [TransporteurID])
*/

(
 @ID [int] = Null -- for [Contingentement_Demande].[ID] column
,@ProducteurID [varchar](15) = Null -- for [Contingentement_Demande].[ProducteurID] column
,@TransporteurID [varchar](15) = Null -- for [Contingentement_Demande].[TransporteurID] column
,@ReturnXML [bit] = 0 -- Indicates if we want to get back XML content instead of normal resultset (@ReturnXML = 1 to get XML back)
)

-- Returns the number of records found

As


--	IMPORTANT:
--	Changes to this SQL code may cause incorrect behavior
--	and will be lost if the code is regenerated. 


If @ReturnXML Is Null
	Set @ReturnXML = 0

If @ReturnXML = 0
	Begin
		Select

		 [Contingentement_Demande_Records].[ID]
		,[Contingentement_Demande_Records].[Annee]
		,[Contingentement_Demande_Records].[ProducteurID]
		,[Contingentement_Demande_Records].[TransporteurID]
		,[Contingentement_Demande_Records].[Superficie_Boisee]
		,[Contingentement_Demande_Records].[Remarques]
		,[Contingentement_Demande_Records].[DateModification]
		,[Contingentement_Demande_Records].[ProducteurID_ID]
		,[Contingentement_Demande_Records].[ProducteurID_CleTri]
		,[Contingentement_Demande_Records].[ProducteurID_Nom]
		,[Contingentement_Demande_Records].[ProducteurID_AuSoinsDe]
		,[Contingentement_Demande_Records].[ProducteurID_Rue]
		,[Contingentement_Demande_Records].[ProducteurID_Ville]
		,[Contingentement_Demande_Records].[ProducteurID_PaysID]
		,[Contingentement_Demande_Records].[ProducteurID_Code_postal]
		,[Contingentement_Demande_Records].[ProducteurID_Telephone]
		,[Contingentement_Demande_Records].[ProducteurID_Telephone_Poste]
		,[Contingentement_Demande_Records].[ProducteurID_Telecopieur]
		,[Contingentement_Demande_Records].[ProducteurID_Telephone2]
		,[Contingentement_Demande_Records].[ProducteurID_Telephone2_Desc]
		,[Contingentement_Demande_Records].[ProducteurID_Telephone2_Poste]
		,[Contingentement_Demande_Records].[ProducteurID_Telephone3]
		,[Contingentement_Demande_Records].[ProducteurID_Telephone3_Desc]
		,[Contingentement_Demande_Records].[ProducteurID_Telephone3_Poste]
		,[Contingentement_Demande_Records].[ProducteurID_No_membre]
		,[Contingentement_Demande_Records].[ProducteurID_Resident]
		,[Contingentement_Demande_Records].[ProducteurID_Email]
		,[Contingentement_Demande_Records].[ProducteurID_WWW]
		,[Contingentement_Demande_Records].[ProducteurID_Commentaires]
		,[Contingentement_Demande_Records].[ProducteurID_AfficherCommentaires]
		,[Contingentement_Demande_Records].[ProducteurID_DepotDirect]
		,[Contingentement_Demande_Records].[ProducteurID_InstitutionBanquaireID]
		,[Contingentement_Demande_Records].[ProducteurID_Banque_transit]
		,[Contingentement_Demande_Records].[ProducteurID_Banque_folio]
		,[Contingentement_Demande_Records].[ProducteurID_No_TPS]
		,[Contingentement_Demande_Records].[ProducteurID_No_TVQ]
		,[Contingentement_Demande_Records].[ProducteurID_PayerA]
		,[Contingentement_Demande_Records].[ProducteurID_PayerAID]
		,[Contingentement_Demande_Records].[ProducteurID_Statut]
		,[Contingentement_Demande_Records].[ProducteurID_Rep_Nom]
		,[Contingentement_Demande_Records].[ProducteurID_Rep_Telephone]
		,[Contingentement_Demande_Records].[ProducteurID_Rep_Telephone_Poste]
		,[Contingentement_Demande_Records].[ProducteurID_Rep_Email]
		,[Contingentement_Demande_Records].[ProducteurID_EnAnglais]
		,[Contingentement_Demande_Records].[ProducteurID_Actif]
		,[Contingentement_Demande_Records].[ProducteurID_MRCProducteurID]
		,[Contingentement_Demande_Records].[ProducteurID_PaiementManuel]
		,[Contingentement_Demande_Records].[ProducteurID_Journal]
		,[Contingentement_Demande_Records].[ProducteurID_RecoitTPS]
		,[Contingentement_Demande_Records].[ProducteurID_RecoitTVQ]
		,[Contingentement_Demande_Records].[ProducteurID_ModifierTrigger]
		,[Contingentement_Demande_Records].[ProducteurID_IsProducteur]
		,[Contingentement_Demande_Records].[ProducteurID_IsTransporteur]
		,[Contingentement_Demande_Records].[ProducteurID_IsChargeur]
		,[Contingentement_Demande_Records].[ProducteurID_IsAutre]
		,[Contingentement_Demande_Records].[ProducteurID_AfficherCommentairesSurPermit]
		,[Contingentement_Demande_Records].[ProducteurID_PasEmissionPermis]
		,[Contingentement_Demande_Records].[ProducteurID_Generique]
		,[Contingentement_Demande_Records].[ProducteurID_Membre_OGC]
		,[Contingentement_Demande_Records].[ProducteurID_InscritTPS]
		,[Contingentement_Demande_Records].[ProducteurID_InscritTVQ]
		,[Contingentement_Demande_Records].[ProducteurID_IsOGC]
		,[Contingentement_Demande_Records].[TransporteurID_ID]
		,[Contingentement_Demande_Records].[TransporteurID_CleTri]
		,[Contingentement_Demande_Records].[TransporteurID_Nom]
		,[Contingentement_Demande_Records].[TransporteurID_AuSoinsDe]
		,[Contingentement_Demande_Records].[TransporteurID_Rue]
		,[Contingentement_Demande_Records].[TransporteurID_Ville]
		,[Contingentement_Demande_Records].[TransporteurID_PaysID]
		,[Contingentement_Demande_Records].[TransporteurID_Code_postal]
		,[Contingentement_Demande_Records].[TransporteurID_Telephone]
		,[Contingentement_Demande_Records].[TransporteurID_Telephone_Poste]
		,[Contingentement_Demande_Records].[TransporteurID_Telecopieur]
		,[Contingentement_Demande_Records].[TransporteurID_Telephone2]
		,[Contingentement_Demande_Records].[TransporteurID_Telephone2_Desc]
		,[Contingentement_Demande_Records].[TransporteurID_Telephone2_Poste]
		,[Contingentement_Demande_Records].[TransporteurID_Telephone3]
		,[Contingentement_Demande_Records].[TransporteurID_Telephone3_Desc]
		,[Contingentement_Demande_Records].[TransporteurID_Telephone3_Poste]
		,[Contingentement_Demande_Records].[TransporteurID_No_membre]
		,[Contingentement_Demande_Records].[TransporteurID_Resident]
		,[Contingentement_Demande_Records].[TransporteurID_Email]
		,[Contingentement_Demande_Records].[TransporteurID_WWW]
		,[Contingentement_Demande_Records].[TransporteurID_Commentaires]
		,[Contingentement_Demande_Records].[TransporteurID_AfficherCommentaires]
		,[Contingentement_Demande_Records].[TransporteurID_DepotDirect]
		,[Contingentement_Demande_Records].[TransporteurID_InstitutionBanquaireID]
		,[Contingentement_Demande_Records].[TransporteurID_Banque_transit]
		,[Contingentement_Demande_Records].[TransporteurID_Banque_folio]
		,[Contingentement_Demande_Records].[TransporteurID_No_TPS]
		,[Contingentement_Demande_Records].[TransporteurID_No_TVQ]
		,[Contingentement_Demande_Records].[TransporteurID_PayerA]
		,[Contingentement_Demande_Records].[TransporteurID_PayerAID]
		,[Contingentement_Demande_Records].[TransporteurID_Statut]
		,[Contingentement_Demande_Records].[TransporteurID_Rep_Nom]
		,[Contingentement_Demande_Records].[TransporteurID_Rep_Telephone]
		,[Contingentement_Demande_Records].[TransporteurID_Rep_Telephone_Poste]
		,[Contingentement_Demande_Records].[TransporteurID_Rep_Email]
		,[Contingentement_Demande_Records].[TransporteurID_EnAnglais]
		,[Contingentement_Demande_Records].[TransporteurID_Actif]
		,[Contingentement_Demande_Records].[TransporteurID_MRCProducteurID]
		,[Contingentement_Demande_Records].[TransporteurID_PaiementManuel]
		,[Contingentement_Demande_Records].[TransporteurID_Journal]
		,[Contingentement_Demande_Records].[TransporteurID_RecoitTPS]
		,[Contingentement_Demande_Records].[TransporteurID_RecoitTVQ]
		,[Contingentement_Demande_Records].[TransporteurID_ModifierTrigger]
		,[Contingentement_Demande_Records].[TransporteurID_IsProducteur]
		,[Contingentement_Demande_Records].[TransporteurID_IsTransporteur]
		,[Contingentement_Demande_Records].[TransporteurID_IsChargeur]
		,[Contingentement_Demande_Records].[TransporteurID_IsAutre]
		,[Contingentement_Demande_Records].[TransporteurID_AfficherCommentairesSurPermit]
		,[Contingentement_Demande_Records].[TransporteurID_PasEmissionPermis]
		,[Contingentement_Demande_Records].[TransporteurID_Generique]
		,[Contingentement_Demande_Records].[TransporteurID_Membre_OGC]
		,[Contingentement_Demande_Records].[TransporteurID_InscritTPS]
		,[Contingentement_Demande_Records].[TransporteurID_InscritTVQ]
		,[Contingentement_Demande_Records].[TransporteurID_IsOGC]

		From [fnContingentement_Demande_Full](@ID, @ProducteurID, @TransporteurID) As [Contingentement_Demande_Records]
	End

Else

	Begin
		Select

		 [Contingentement_Demande_Records].[ID]
		,[Contingentement_Demande_Records].[Annee]
		,[Contingentement_Demande_Records].[ProducteurID]
		,[Contingentement_Demande_Records].[TransporteurID]
		,[Contingentement_Demande_Records].[Superficie_Boisee]
		,[Contingentement_Demande_Records].[Remarques]
		,[Contingentement_Demande_Records].[DateModification]
		,[Contingentement_Demande_Records].[ProducteurID_ID]
		,[Contingentement_Demande_Records].[ProducteurID_CleTri]
		,[Contingentement_Demande_Records].[ProducteurID_Nom]
		,[Contingentement_Demande_Records].[ProducteurID_AuSoinsDe]
		,[Contingentement_Demande_Records].[ProducteurID_Rue]
		,[Contingentement_Demande_Records].[ProducteurID_Ville]
		,[Contingentement_Demande_Records].[ProducteurID_PaysID]
		,[Contingentement_Demande_Records].[ProducteurID_Code_postal]
		,[Contingentement_Demande_Records].[ProducteurID_Telephone]
		,[Contingentement_Demande_Records].[ProducteurID_Telephone_Poste]
		,[Contingentement_Demande_Records].[ProducteurID_Telecopieur]
		,[Contingentement_Demande_Records].[ProducteurID_Telephone2]
		,[Contingentement_Demande_Records].[ProducteurID_Telephone2_Desc]
		,[Contingentement_Demande_Records].[ProducteurID_Telephone2_Poste]
		,[Contingentement_Demande_Records].[ProducteurID_Telephone3]
		,[Contingentement_Demande_Records].[ProducteurID_Telephone3_Desc]
		,[Contingentement_Demande_Records].[ProducteurID_Telephone3_Poste]
		,[Contingentement_Demande_Records].[ProducteurID_No_membre]
		,[Contingentement_Demande_Records].[ProducteurID_Resident]
		,[Contingentement_Demande_Records].[ProducteurID_Email]
		,[Contingentement_Demande_Records].[ProducteurID_WWW]
		,[Contingentement_Demande_Records].[ProducteurID_Commentaires]
		,[Contingentement_Demande_Records].[ProducteurID_AfficherCommentaires]
		,[Contingentement_Demande_Records].[ProducteurID_DepotDirect]
		,[Contingentement_Demande_Records].[ProducteurID_InstitutionBanquaireID]
		,[Contingentement_Demande_Records].[ProducteurID_Banque_transit]
		,[Contingentement_Demande_Records].[ProducteurID_Banque_folio]
		,[Contingentement_Demande_Records].[ProducteurID_No_TPS]
		,[Contingentement_Demande_Records].[ProducteurID_No_TVQ]
		,[Contingentement_Demande_Records].[ProducteurID_PayerA]
		,[Contingentement_Demande_Records].[ProducteurID_PayerAID]
		,[Contingentement_Demande_Records].[ProducteurID_Statut]
		,[Contingentement_Demande_Records].[ProducteurID_Rep_Nom]
		,[Contingentement_Demande_Records].[ProducteurID_Rep_Telephone]
		,[Contingentement_Demande_Records].[ProducteurID_Rep_Telephone_Poste]
		,[Contingentement_Demande_Records].[ProducteurID_Rep_Email]
		,[Contingentement_Demande_Records].[ProducteurID_EnAnglais]
		,[Contingentement_Demande_Records].[ProducteurID_Actif]
		,[Contingentement_Demande_Records].[ProducteurID_MRCProducteurID]
		,[Contingentement_Demande_Records].[ProducteurID_PaiementManuel]
		,[Contingentement_Demande_Records].[ProducteurID_Journal]
		,[Contingentement_Demande_Records].[ProducteurID_RecoitTPS]
		,[Contingentement_Demande_Records].[ProducteurID_RecoitTVQ]
		,[Contingentement_Demande_Records].[ProducteurID_ModifierTrigger]
		,[Contingentement_Demande_Records].[ProducteurID_IsProducteur]
		,[Contingentement_Demande_Records].[ProducteurID_IsTransporteur]
		,[Contingentement_Demande_Records].[ProducteurID_IsChargeur]
		,[Contingentement_Demande_Records].[ProducteurID_IsAutre]
		,[Contingentement_Demande_Records].[ProducteurID_AfficherCommentairesSurPermit]
		,[Contingentement_Demande_Records].[ProducteurID_PasEmissionPermis]
		,[Contingentement_Demande_Records].[ProducteurID_Generique]
		,[Contingentement_Demande_Records].[ProducteurID_Membre_OGC]
		,[Contingentement_Demande_Records].[ProducteurID_InscritTPS]
		,[Contingentement_Demande_Records].[ProducteurID_InscritTVQ]
		,[Contingentement_Demande_Records].[ProducteurID_IsOGC]
		,[Contingentement_Demande_Records].[TransporteurID_ID]
		,[Contingentement_Demande_Records].[TransporteurID_CleTri]
		,[Contingentement_Demande_Records].[TransporteurID_Nom]
		,[Contingentement_Demande_Records].[TransporteurID_AuSoinsDe]
		,[Contingentement_Demande_Records].[TransporteurID_Rue]
		,[Contingentement_Demande_Records].[TransporteurID_Ville]
		,[Contingentement_Demande_Records].[TransporteurID_PaysID]
		,[Contingentement_Demande_Records].[TransporteurID_Code_postal]
		,[Contingentement_Demande_Records].[TransporteurID_Telephone]
		,[Contingentement_Demande_Records].[TransporteurID_Telephone_Poste]
		,[Contingentement_Demande_Records].[TransporteurID_Telecopieur]
		,[Contingentement_Demande_Records].[TransporteurID_Telephone2]
		,[Contingentement_Demande_Records].[TransporteurID_Telephone2_Desc]
		,[Contingentement_Demande_Records].[TransporteurID_Telephone2_Poste]
		,[Contingentement_Demande_Records].[TransporteurID_Telephone3]
		,[Contingentement_Demande_Records].[TransporteurID_Telephone3_Desc]
		,[Contingentement_Demande_Records].[TransporteurID_Telephone3_Poste]
		,[Contingentement_Demande_Records].[TransporteurID_No_membre]
		,[Contingentement_Demande_Records].[TransporteurID_Resident]
		,[Contingentement_Demande_Records].[TransporteurID_Email]
		,[Contingentement_Demande_Records].[TransporteurID_WWW]
		,[Contingentement_Demande_Records].[TransporteurID_Commentaires]
		,[Contingentement_Demande_Records].[TransporteurID_AfficherCommentaires]
		,[Contingentement_Demande_Records].[TransporteurID_DepotDirect]
		,[Contingentement_Demande_Records].[TransporteurID_InstitutionBanquaireID]
		,[Contingentement_Demande_Records].[TransporteurID_Banque_transit]
		,[Contingentement_Demande_Records].[TransporteurID_Banque_folio]
		,[Contingentement_Demande_Records].[TransporteurID_No_TPS]
		,[Contingentement_Demande_Records].[TransporteurID_No_TVQ]
		,[Contingentement_Demande_Records].[TransporteurID_PayerA]
		,[Contingentement_Demande_Records].[TransporteurID_PayerAID]
		,[Contingentement_Demande_Records].[TransporteurID_Statut]
		,[Contingentement_Demande_Records].[TransporteurID_Rep_Nom]
		,[Contingentement_Demande_Records].[TransporteurID_Rep_Telephone]
		,[Contingentement_Demande_Records].[TransporteurID_Rep_Telephone_Poste]
		,[Contingentement_Demande_Records].[TransporteurID_Rep_Email]
		,[Contingentement_Demande_Records].[TransporteurID_EnAnglais]
		,[Contingentement_Demande_Records].[TransporteurID_Actif]
		,[Contingentement_Demande_Records].[TransporteurID_MRCProducteurID]
		,[Contingentement_Demande_Records].[TransporteurID_PaiementManuel]
		,[Contingentement_Demande_Records].[TransporteurID_Journal]
		,[Contingentement_Demande_Records].[TransporteurID_RecoitTPS]
		,[Contingentement_Demande_Records].[TransporteurID_RecoitTVQ]
		,[Contingentement_Demande_Records].[TransporteurID_ModifierTrigger]
		,[Contingentement_Demande_Records].[TransporteurID_IsProducteur]
		,[Contingentement_Demande_Records].[TransporteurID_IsTransporteur]
		,[Contingentement_Demande_Records].[TransporteurID_IsChargeur]
		,[Contingentement_Demande_Records].[TransporteurID_IsAutre]
		,[Contingentement_Demande_Records].[TransporteurID_AfficherCommentairesSurPermit]
		,[Contingentement_Demande_Records].[TransporteurID_PasEmissionPermis]
		,[Contingentement_Demande_Records].[TransporteurID_Generique]
		,[Contingentement_Demande_Records].[TransporteurID_Membre_OGC]
		,[Contingentement_Demande_Records].[TransporteurID_InscritTPS]
		,[Contingentement_Demande_Records].[TransporteurID_InscritTVQ]
		,[Contingentement_Demande_Records].[TransporteurID_IsOGC]

		From [fnContingentement_Demande_Full](@ID, @ProducteurID, @TransporteurID) As [Contingentement_Demande_Records]

		For XML Auto, Elements, XMLData, BINARY BASE64
	End

Return(@@RowCount)

