CREATE PROCEDURE [dbo].[spX_xRebuildIndexes]

AS
Set NoCount On

DBCC DBREINDEX ('[dbo].[Agence]', '', 70)
DBCC DBREINDEX ('[dbo].[Ajustement]', '', 70)
DBCC DBREINDEX ('[dbo].[Ajustement_EssenceUnite]', '', 70)
DBCC DBREINDEX ('[dbo].[Ajustement_Transporteur]', '', 70)
DBCC DBREINDEX ('[dbo].[AjustementCalcule_Producteur]', '', 70)
DBCC DBREINDEX ('[dbo].[AjustementCalcule_Transporteur]', '', 70)
DBCC DBREINDEX ('[dbo].[AjustementCalcule_Usine]', '', 70)
DBCC DBREINDEX ('[dbo].[Canton]', '', 70)
DBCC DBREINDEX ('[dbo].[Cert_Lot]', '', 70)
DBCC DBREINDEX ('[dbo].[Cert_Proprietaire]', '', 70)
DBCC DBREINDEX ('[dbo].[Compte]', '', 70)
DBCC DBREINDEX ('[dbo].[CompteCategory]', '', 70)
DBCC DBREINDEX ('[dbo].[Contingentement]', '', 70)
DBCC DBREINDEX ('[dbo].[Contingentement_Demande]', '', 70)
DBCC DBREINDEX ('[dbo].[Contingentement_Producteur]', '', 70)
DBCC DBREINDEX ('[dbo].[Contingentement_Unite]', '', 70)
DBCC DBREINDEX ('[dbo].[Contingentement_VolumeFixe]', '', 70)
DBCC DBREINDEX ('[dbo].[Contrat]', '', 70)
DBCC DBREINDEX ('[dbo].[Contrat_EssenceUnite]', '', 70)
DBCC DBREINDEX ('[dbo].[Contrat_Transporteur]', '', 70)
DBCC DBREINDEX ('[dbo].[Essence]', '', 70)
DBCC DBREINDEX ('[dbo].[Essence_Unite]', '', 70)
DBCC DBREINDEX ('[dbo].[EssenceContingent]', '', 70)
DBCC DBREINDEX ('[dbo].[EssenceRegroupement]', '', 70)
DBCC DBREINDEX ('[dbo].[EssenceRepartition]', '', 70)
DBCC DBREINDEX ('[dbo].[EssenceSciage]', '', 70)
DBCC DBREINDEX ('[dbo].[Excel_Canton]', '', 70)
DBCC DBREINDEX ('[dbo].[Excel_Municipalite]', '', 70)
DBCC DBREINDEX ('[dbo].[FactureClient]', '', 70)
DBCC DBREINDEX ('[dbo].[FactureClient_Details]', '', 70)
DBCC DBREINDEX ('[dbo].[FactureClient_Sommaire]', '', 70)
DBCC DBREINDEX ('[dbo].[FactureFournisseur]', '', 70)
DBCC DBREINDEX ('[dbo].[FactureFournisseur_Details]', '', 70)
DBCC DBREINDEX ('[dbo].[FactureFournisseur_Sommaire]', '', 70)
DBCC DBREINDEX ('[dbo].[FactureStatus]', '', 70)
DBCC DBREINDEX ('[dbo].[FactureUsine]', '', 70)
DBCC DBREINDEX ('[dbo].[FactureUsine_Detail]', '', 70)
DBCC DBREINDEX ('[dbo].[FeuilletDomtar]', '', 70)
DBCC DBREINDEX ('[dbo].[Fournisseur]', '', 70)
DBCC DBREINDEX ('[dbo].[Fournisseur_Camion]', '', 70)
DBCC DBREINDEX ('[dbo].[FournisseurSearch]', '', 70)
DBCC DBREINDEX ('[dbo].[GestionVolume]', '', 70)
DBCC DBREINDEX ('[dbo].[GestionVolume_Detail]', '', 70)
DBCC DBREINDEX ('[dbo].[Indexation]', '', 70)
DBCC DBREINDEX ('[dbo].[Indexation_EssenceUnite]', '', 70)
DBCC DBREINDEX ('[dbo].[Indexation_Livraison]', '', 70)
DBCC DBREINDEX ('[dbo].[Indexation_Municipalite]', '', 70)
DBCC DBREINDEX ('[dbo].[IndexationCalcule_Producteur]', '', 70)
DBCC DBREINDEX ('[dbo].[IndexationCalcule_Transporteur]', '', 70)
DBCC DBREINDEX ('[dbo].[InstitutionBanquaire]', '', 70)
DBCC DBREINDEX ('[dbo].[jag_Profile]', '', 70)
DBCC DBREINDEX ('[dbo].[jag_ProfileSettings]', '', 70)
DBCC DBREINDEX ('[dbo].[jag_System]', '', 70)
DBCC DBREINDEX ('[dbo].[jag_SystemEx]', '', 70)
DBCC DBREINDEX ('[dbo].[Livraison]', '', 70)
DBCC DBREINDEX ('[dbo].[Livraison_Detail]', '', 70)
DBCC DBREINDEX ('[dbo].[Livraison_Permis]', '', 70)
DBCC DBREINDEX ('[dbo].[Lot]', '', 70)
DBCC DBREINDEX ('[dbo].[Lot_Proprietaire]', '', 70)
DBCC DBREINDEX ('[dbo].[Lot_SuperficieBoisee]', '', 70)
DBCC DBREINDEX ('[dbo].[LotContingente]', '', 70)
DBCC DBREINDEX ('[dbo].[LotImportation]', '', 70)
DBCC DBREINDEX ('[dbo].[MRC]', '', 70)
DBCC DBREINDEX ('[dbo].[MRCCorrection]', '', 70)
DBCC DBREINDEX ('[dbo].[Municipalite]', '', 70)
DBCC DBREINDEX ('[dbo].[Municipalite_Secteur]', '', 70)
DBCC DBREINDEX ('[dbo].[Municipalite_Zone]', '', 70)
DBCC DBREINDEX ('[dbo].[Pays]', '', 70)
DBCC DBREINDEX ('[dbo].[Periode]', '', 70)
DBCC DBREINDEX ('[dbo].[Permit]', '', 70)
DBCC DBREINDEX ('[dbo].[TypeFacture]', '', 70)
DBCC DBREINDEX ('[dbo].[TypeFactureFournisseur]', '', 70)
DBCC DBREINDEX ('[dbo].[TypeIndexation]', '', 70)
DBCC DBREINDEX ('[dbo].[TypeInvoiceAcomba]', '', 70)
DBCC DBREINDEX ('[dbo].[TypeInvoiceClientAcomba]', '', 70)
DBCC DBREINDEX ('[dbo].[UniteMesure]', '', 70)
DBCC DBREINDEX ('[dbo].[Usine]', '', 70)
DBCC DBREINDEX ('[dbo].[UsineUtilisation]', '', 70)

Set NoCount Off


