CREATE TABLE [dbo].[FactureUsine_Detail] (
    [ID]                          INT          IDENTITY (1, 1) NOT NULL,
    [FactureUsineID]              INT          NULL,
    [ContratID]                   VARCHAR (10) NULL,
    [ProducteurID]                VARCHAR (15) NULL,
    [ProducteurEntentePaiementID] VARCHAR (15) NULL,
    [ZoneID]                      VARCHAR (2)  NULL,
    [MunicipaliteID]              VARCHAR (6)  NULL,
    [LotID]                       INT          NULL,
    [UniteMesureID]               VARCHAR (6)  NOT NULL,
    [LivraisonID]                 INT          NULL,
    [EssenceID]                   VARCHAR (6)  NULL,
    [Code]                        CHAR (4)     NULL,
    [Volume]                      FLOAT (53)   NULL,
    [Taux]                        FLOAT (53)   NULL,
    [Montant]                     FLOAT (53)   NULL,
    [Taux_Usine_Override]         BIT          NULL,
    [PermisID]                    INT          NULL,
    CONSTRAINT [PK_FactureUsine_Detail] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_FactureUsine_Detail_Essence] FOREIGN KEY ([EssenceID]) REFERENCES [dbo].[Essence] ([ID]),
    CONSTRAINT [FK_FactureUsine_Detail_FactureUsine] FOREIGN KEY ([FactureUsineID]) REFERENCES [dbo].[FactureUsine] ([ID]),
    CONSTRAINT [FK_FactureUsine_Detail_Fournisseur] FOREIGN KEY ([ProducteurID]) REFERENCES [dbo].[Fournisseur] ([ID]),
    CONSTRAINT [FK_FactureUsine_Detail_Fournisseur2] FOREIGN KEY ([ProducteurEntentePaiementID]) REFERENCES [dbo].[Fournisseur] ([ID]),
    CONSTRAINT [FK_FactureUsine_Detail_Livraison] FOREIGN KEY ([LivraisonID]) REFERENCES [dbo].[Livraison] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_FactureUsine_Detail_Lot] FOREIGN KEY ([LotID]) REFERENCES [dbo].[Lot] ([ID]),
    CONSTRAINT [FK_FactureUsine_Detail_Municipalite_Zone] FOREIGN KEY ([ZoneID], [MunicipaliteID]) REFERENCES [dbo].[Municipalite_Zone] ([ID], [MunicipaliteID]),
    CONSTRAINT [FK_FactureUsine_Detail_UniteMesure] FOREIGN KEY ([UniteMesureID]) REFERENCES [dbo].[UniteMesure] ([ID])
);

