CREATE TABLE [dbo].[FeuilletDomtar] (
    [Transaction]         VARCHAR (15)  NOT NULL,
    [TransactionType]     VARCHAR (3)   NULL,
    [Fournisseur]         VARCHAR (15)  NULL,
    [Contrat]             VARCHAR (25)  NULL,
    [Produit]             VARCHAR (10)  NULL,
    [DateLivraison]       SMALLDATETIME NULL,
    [Carte]               VARCHAR (15)  NULL,
    [License]             VARCHAR (15)  NULL,
    [Transporteur_Camion] VARCHAR (15)  NULL,
    [Producteur]          VARCHAR (15)  NULL,
    [Municipalite]        VARCHAR (15)  NULL,
    [Brut]                INT           NULL,
    [Tare]                INT           NULL,
    [Net]                 INT           NULL,
    [Rejets]              INT           NULL,
    [KgVert_Paye]         INT           NULL,
    [Pourcent_Sec]        FLOAT (53)    NULL,
    [KgSec_Paye]          INT           NULL,
    [Validation]          VARCHAR (255) NULL,
    [Transfert]           BIT           NOT NULL,
    [EssenceID]           VARCHAR (6)   NULL,
    [UniteID]             VARCHAR (6)   NULL,
    [Code]                CHAR (4)      NULL,
    [TransporteurID]      VARCHAR (15)  NULL,
    [BonCommande]         VARCHAR (25)  NULL,
    CONSTRAINT [PK_FeuilletDomtar] PRIMARY KEY CLUSTERED ([Transaction] ASC)
);

