CREATE TABLE [dbo].[Fournisseur] (
    [ID]                            VARCHAR (15)  NOT NULL,
    [CleTri]                        VARCHAR (15)  NULL,
    [Nom]                           VARCHAR (40)  NULL,
    [AuSoinsDe]                     VARCHAR (30)  NULL,
    [Rue]                           VARCHAR (30)  NULL,
    [Ville]                         VARCHAR (30)  NULL,
    [PaysID]                        VARCHAR (2)   NULL,
    [Code_postal]                   VARCHAR (7)   NULL,
    [Telephone]                     VARCHAR (12)  NULL,
    [Telephone_Poste]               VARCHAR (4)   NULL,
    [Telecopieur]                   VARCHAR (12)  NULL,
    [Telephone2]                    VARCHAR (12)  NULL,
    [Telephone2_Desc]               VARCHAR (20)  NULL,
    [Telephone2_Poste]              VARCHAR (4)   NULL,
    [Telephone3]                    VARCHAR (12)  NULL,
    [Telephone3_Desc]               VARCHAR (20)  NULL,
    [Telephone3_Poste]              VARCHAR (4)   NULL,
    [No_membre]                     VARCHAR (10)  NULL,
    [Resident]                      CHAR (1)      NULL,
    [Email]                         VARCHAR (80)  NULL,
    [WWW]                           VARCHAR (80)  NULL,
    [Commentaires]                  VARCHAR (255) NULL,
    [AfficherCommentaires]          BIT           CONSTRAINT [DF_Fournisseur_AfficherCommentaires] DEFAULT (0) NULL,
    [DepotDirect]                   BIT           NULL,
    [InstitutionBanquaireID]        VARCHAR (3)   NULL,
    [Banque_transit]                VARCHAR (5)   NULL,
    [Banque_folio]                  VARCHAR (12)  NULL,
    [No_TPS]                        VARCHAR (25)  NULL,
    [No_TVQ]                        VARCHAR (25)  NULL,
    [PayerA]                        BIT           NULL,
    [PayerAID]                      VARCHAR (15)  NULL,
    [Statut]                        VARCHAR (50)  NULL,
    [Rep_Nom]                       VARCHAR (30)  NULL,
    [Rep_Telephone]                 VARCHAR (12)  NULL,
    [Rep_Telephone_Poste]           VARCHAR (4)   NULL,
    [Rep_Email]                     VARCHAR (80)  NULL,
    [EnAnglais]                     BIT           NULL,
    [Actif]                         BIT           NULL,
    [MRCProducteurID]               INT           NULL,
    [PaiementManuel]                BIT           NULL,
    [Journal]                       BIT           NULL,
    [RecoitTPS]                     BIT           NULL,
    [RecoitTVQ]                     BIT           NULL,
    [ModifierTrigger]               BIT           NULL,
    [IsProducteur]                  BIT           NULL,
    [IsTransporteur]                BIT           NULL,
    [IsChargeur]                    BIT           NULL,
    [IsAutre]                       BIT           NULL,
    [AfficherCommentairesSurPermit] BIT           DEFAULT (0) NOT NULL,
    [PasEmissionPermis]             BIT           NULL,
    [Generique]                     BIT           NULL,
    [Membre_OGC]                    BIT           NULL,
    [InscritTPS]                    BIT           NULL,
    [InscritTVQ]                    BIT           NULL,
    [IsOGC]                         BIT           DEFAULT (0) NOT NULL,
    [Rep2_Nom]                      VARCHAR (80)  NULL,
    [Rep2_Telephone]                VARCHAR (12)  NULL,
    [Rep2_Telephone_Poste]          VARCHAR (4)   NULL,
    [Rep2_Email]                    VARCHAR (80)  NULL,
    [Rep2_Commentaires]             VARCHAR (255) NULL,
    CONSTRAINT [PK_Fournisseur] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Fournisseur_InstitutionBanquaire] FOREIGN KEY ([InstitutionBanquaireID]) REFERENCES [dbo].[InstitutionBanquaire] ([ID]),
    CONSTRAINT [FK_Fournisseur_Pays] FOREIGN KEY ([PaysID]) REFERENCES [dbo].[Pays] ([ID])
);

