CREATE TABLE [dbo].[IndexationCalcule_Producteur] (
    [ID]                   INT           IDENTITY (1, 1) NOT NULL,
    [DateCalcul]           DATETIME      NULL,
    [TypeIndexation]       CHAR (1)      NULL,
    [IndexationID]         INT           NULL,
    [IndexationDetailID]   INT           NULL,
    [LivraisonID]          INT           NULL,
    [LivraisonDetailID]    INT           NULL,
    [ProducteurID]         VARCHAR (15)  NULL,
    [ContratID]            VARCHAR (10)  NULL,
    [EssenceID]            VARCHAR (6)   NULL,
    [Code]                 CHAR (4)      NULL,
    [UniteID]              VARCHAR (6)   NULL,
    [Volume]               FLOAT (53)    NULL,
    [MontantDejaPaye]      FLOAT (53)    NULL,
    [PourcentageDuMontant] FLOAT (53)    NULL,
    [Taux]                 FLOAT (53)    NULL,
    [Montant]              FLOAT (53)    NULL,
    [Facture]              BIT           NULL,
    [FactureID]            INT           NULL,
    [ErreurCalcul]         BIT           NULL,
    [ErreurDescription]    VARCHAR (300) NULL,
    CONSTRAINT [PK_IndexationCalcule_Producteur] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_IndexationCalcule_Producteur_Contrat_EssenceUnite] FOREIGN KEY ([ContratID], [EssenceID], [UniteID], [Code]) REFERENCES [dbo].[Contrat_EssenceUnite] ([ContratID], [EssenceID], [UniteID], [Code]) ON UPDATE CASCADE,
    CONSTRAINT [FK_IndexationCalcule_Producteur_FactureFournisseur] FOREIGN KEY ([FactureID]) REFERENCES [dbo].[FactureFournisseur] ([ID]),
    CONSTRAINT [FK_IndexationCalcule_Producteur_Fournisseur] FOREIGN KEY ([ProducteurID]) REFERENCES [dbo].[Fournisseur] ([ID]),
    CONSTRAINT [FK_IndexationCalcule_Producteur_Indexation] FOREIGN KEY ([IndexationID]) REFERENCES [dbo].[Indexation] ([ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_IndexationCalcule_Producteur_Indexation_EssenceUnite] FOREIGN KEY ([IndexationDetailID]) REFERENCES [dbo].[Indexation_EssenceUnite] ([ID]),
    CONSTRAINT [FK_IndexationCalcule_Producteur_Livraison] FOREIGN KEY ([LivraisonID]) REFERENCES [dbo].[Livraison] ([ID]),
    CONSTRAINT [FK_IndexationCalcule_Producteur_Livraison_Detail] FOREIGN KEY ([LivraisonDetailID]) REFERENCES [dbo].[Livraison_Detail] ([ID]),
    CONSTRAINT [FK_IndexationCalcule_Producteur_TypeIndexation] FOREIGN KEY ([TypeIndexation]) REFERENCES [dbo].[TypeIndexation] ([ID])
);

