CREATE TABLE [dbo].[Livraison_Archive] (
    [ID]                                         INT            NOT NULL,
    [DateLivraison]                              SMALLDATETIME  NULL,
    [DatePaye]                                   SMALLDATETIME  NULL,
    [ContratID]                                  VARCHAR (10)   NULL,
    [UniteMesureID]                              VARCHAR (6)    NULL,
    [EssenceID]                                  VARCHAR (6)    NULL,
    [Sciage]                                     BIT            NULL,
    [NumeroFactureUsine]                         VARCHAR (25)   NULL,
    [DroitCoupeID]                               VARCHAR (15)   NULL,
    [EntentePaiementID]                          VARCHAR (15)   NULL,
    [TransporteurID]                             VARCHAR (15)   NULL,
    [VR]                                         VARCHAR (10)   NULL,
    [MasseLimite]                                FLOAT (53)     NULL,
    [VolumeBrut]                                 FLOAT (53)     NULL,
    [VolumeTare]                                 FLOAT (53)     NULL,
    [VolumeTransporte]                           FLOAT (53)     NULL,
    [VolumeSurcharge]                            FLOAT (53)     NULL,
    [VolumeAPayer]                               FLOAT (53)     NULL,
    [Annee]                                      INT            NULL,
    [Periode]                                    INT            NULL,
    [DateCalcul]                                 DATETIME       NULL,
    [Taux_Transporteur]                          FLOAT (53)     NULL,
    [Montant_Transporteur]                       FLOAT (53)     NULL,
    [Montant_Usine]                              FLOAT (53)     NULL,
    [Montant_Producteur1]                        FLOAT (53)     NULL,
    [Montant_Producteur2]                        FLOAT (53)     NULL,
    [Montant_Preleve_Plan_Conjoint]              FLOAT (53)     NULL,
    [Montant_Preleve_Fond_Roulement]             FLOAT (53)     NULL,
    [Montant_Preleve_Fond_Forestier]             FLOAT (53)     NULL,
    [Montant_Preleve_Divers]                     FLOAT (53)     NULL,
    [Montant_Surcharge]                          FLOAT (53)     NULL,
    [Montant_MiseEnCommun]                       REAL           NULL,
    [Facture]                                    BIT            NULL,
    [Producteur1_FactureID]                      INT            NULL,
    [Producteur2_FactureID]                      INT            NULL,
    [Transporteur_FactureID]                     INT            NULL,
    [Usine_FactureID]                            INT            NULL,
    [ErreurCalcul]                               BIT            NULL,
    [ErreurDescription]                          VARCHAR (4000) NULL,
    [LotID]                                      INT            NULL,
    [Taux_Transporteur_Override]                 BIT            NULL,
    [PaieTransporteur]                           BIT            NULL,
    [VolumeSurcharge_Override]                   BIT            NULL,
    [SurchargeManuel]                            BIT            NULL,
    [Code]                                       CHAR (4)       NULL,
    [NombrePermis]                               INT            NULL,
    [ZoneID]                                     VARCHAR (2)    NULL,
    [MunicipaliteID]                             VARCHAR (6)    NULL,
    [ChargeurID]                                 VARCHAR (15)   NULL,
    [Montant_Chargeur]                           FLOAT (53)     NULL,
    [Frais_ChargeurAuProducteur]                 FLOAT (53)     NULL,
    [Frais_ChargeurAuTransporteur]               FLOAT (53)     NULL,
    [Frais_AutresAuProducteur]                   FLOAT (53)     NULL,
    [Frais_AutresAuProducteurDescription]        VARCHAR (50)   NULL,
    [Frais_AutresAuProducteurTransportSciage]    FLOAT (53)     NULL,
    [Frais_AutresAuTransporteur]                 FLOAT (53)     NULL,
    [Frais_AutresAuTransporteurDescription]      VARCHAR (50)   NULL,
    [Frais_CompensationDeDeplacement]            FLOAT (53)     NULL,
    [Chargeur_FactureID]                         INT            NULL,
    [Commentaires_Producteur]                    VARCHAR (500)  NULL,
    [Commentaires_Transporteur]                  VARCHAR (500)  NULL,
    [Commentaires_Chargeur]                      VARCHAR (500)  NULL,
    [TauxChargeurAuProducteur]                   FLOAT (53)     NULL,
    [TauxChargeurAuTransporteur]                 FLOAT (53)     NULL,
    [Frais_AutresRevenusTransporteur]            FLOAT (53)     NULL,
    [Frais_AutresRevenusTransporteurDescription] VARCHAR (50)   NULL,
    [Frais_AutresRevenusProducteur]              FLOAT (53)     NULL,
    [Frais_AutresRevenusProducteurDescription]   VARCHAR (50)   NULL,
    [Montant_SurchargeProducteur]                FLOAT (53)     NULL,
    [KgVert_Brut]                                INT            NULL,
    [KgVert_Tare]                                INT            NULL,
    [KgVert_Net]                                 INT            NULL,
    [KgVert_Rejets]                              INT            NULL,
    [KgVert_Paye]                                INT            NULL,
    [Pourcent_Sec_Producteur]                    FLOAT (53)     NULL,
    [Pourcent_Sec_Producteur_Override]           BIT            NULL,
    [TMA_Producteur]                             FLOAT (53)     NULL,
    [Pourcent_Sec_Transport]                     FLOAT (53)     NULL,
    [Pourcent_Sec_Transport_Override]            BIT            NULL,
    [TMA_Transport]                              FLOAT (53)     NULL,
    [IsTMA]                                      BIT            NULL,
    [SuspendrePaiement]                          BIT            NOT NULL,
    [BonCommande]                                VARCHAR (25)   NULL
);

