CREATE TABLE [dbo].[Livraison_Detail_Archive] (
    [ID]                              INT          NOT NULL,
    [LivraisonID]                     INT          NOT NULL,
    [ContratID]                       VARCHAR (10) NOT NULL,
    [EssenceID]                       VARCHAR (6)  NOT NULL,
    [UniteMesureID]                   VARCHAR (6)  NOT NULL,
    [ProducteurID]                    VARCHAR (15) NOT NULL,
    [Droit_Coupe]                     BIT          NULL,
    [VolumeBrut]                      FLOAT (53)   NULL,
    [VolumeReduction]                 FLOAT (53)   NULL,
    [VolumeNet]                       FLOAT (53)   NULL,
    [VolumeContingente]               FLOAT (53)   NULL,
    [ContingentementID]               INT          NULL,
    [DateCalcul]                      DATETIME     NULL,
    [Taux_Usine]                      FLOAT (53)   NULL,
    [Montant_Usine]                   FLOAT (53)   NULL,
    [Taux_Producteur]                 FLOAT (53)   NULL,
    [Montant_ProducteurBrut]          FLOAT (53)   NULL,
    [Taux_TransporteurMoyen]          FLOAT (53)   NULL,
    [Taux_TransporteurMoyen_Override] BIT          NULL,
    [Montant_TransporteurMoyen]       FLOAT (53)   NULL,
    [Taux_Preleve_Plan_Conjoint]      FLOAT (53)   NULL,
    [Montant_Preleve_Plan_Conjoint]   FLOAT (53)   NULL,
    [Taux_Preleve_Fond_Roulement]     FLOAT (53)   NULL,
    [Montant_Preleve_Fond_Roulement]  FLOAT (53)   NULL,
    [Taux_Preleve_Fond_Forestier]     FLOAT (53)   NULL,
    [Montant_Preleve_Fond_Forestier]  FLOAT (53)   NULL,
    [Taux_Preleve_Divers]             FLOAT (53)   NULL,
    [Montant_Preleve_Divers]          FLOAT (53)   NULL,
    [Montant_ProducteurNet]           FLOAT (53)   NULL,
    [Taux_Producteur_Override]        BIT          NULL,
    [Taux_Usine_Override]             BIT          NULL,
    [Code]                            CHAR (4)     NULL,
    [UsePreleveMontant]               BIT          NULL
);

