CREATE TABLE [dbo].[Permit] (
    [ID]                          INT            NOT NULL,
    [DatePermit]                  SMALLDATETIME  NULL,
    [DateDebut]                   SMALLDATETIME  NULL,
    [DateFin]                     SMALLDATETIME  NULL,
    [Annee]                       INT            NULL,
    [Periode]                     INT            NULL,
    [ContratID]                   VARCHAR (10)   NULL,
    [EssenceID]                   VARCHAR (6)    NULL,
    [PermitSciage]                BIT            NULL,
    [TransporteurID]              VARCHAR (15)   NULL,
    [VR]                          VARCHAR (10)   NULL,
    [ProducteurDroitCoupeID]      VARCHAR (15)   NULL,
    [ProducteurEntentePaiementID] VARCHAR (15)   NULL,
    [PermitLivre]                 BIT            NULL,
    [PermitImprime]               BIT            NULL,
    [PermitAnnule]                BIT            NULL,
    [LotID]                       INT            NULL,
    [EssenceSciage]               VARCHAR (25)   NULL,
    [Code]                        CHAR (4)       NULL,
    [Remarques]                   VARCHAR (2000) NULL,
    [ChargeurID]                  VARCHAR (15)   NULL,
    [ZoneID]                      VARCHAR (2)    NULL,
    [MunicipaliteID]              VARCHAR (6)    NULL,
    CONSTRAINT [PK_Permit] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_Permit_Contrat] FOREIGN KEY ([ContratID]) REFERENCES [dbo].[Contrat] ([ID]),
    CONSTRAINT [FK_Permit_Essence] FOREIGN KEY ([EssenceID]) REFERENCES [dbo].[Essence] ([ID]),
    CONSTRAINT [FK_Permit_Fournisseur] FOREIGN KEY ([TransporteurID]) REFERENCES [dbo].[Fournisseur] ([ID]),
    CONSTRAINT [FK_Permit_Fournisseur1] FOREIGN KEY ([ProducteurDroitCoupeID]) REFERENCES [dbo].[Fournisseur] ([ID]),
    CONSTRAINT [FK_Permit_Fournisseur2] FOREIGN KEY ([ProducteurEntentePaiementID]) REFERENCES [dbo].[Fournisseur] ([ID]),
    CONSTRAINT [FK_Permit_Fournisseur3] FOREIGN KEY ([ChargeurID]) REFERENCES [dbo].[Fournisseur] ([ID]),
    CONSTRAINT [FK_Permit_Lot] FOREIGN KEY ([LotID]) REFERENCES [dbo].[Lot] ([ID]),
    CONSTRAINT [FK_Permit_Municipalite_Zone] FOREIGN KEY ([ZoneID], [MunicipaliteID]) REFERENCES [dbo].[Municipalite_Zone] ([ID], [MunicipaliteID]) ON UPDATE CASCADE
);

